/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.Backup;
import br.com.bar.dao.Log;
import br.com.bar.model.DadosEmpresa;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerDadosEmpresa;
import br.com.br.controler.ControlerParametro;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author elias
 */
public class TelaCadastroEmpresa extends javax.swing.JFrame {

    ControlerDadosEmpresa dados = new ControlerDadosEmpresa();
    ControlerParametro p = new ControlerParametro();
    DadosEmpresa d = dados.selecionaDados();
    TelaAutenticaBackup authBkp = new TelaAutenticaBackup();
    Util u = new Util();
    Log l = new Log();

    /**
     * Creates new form TelaCadastroEmpresa
     */
    public TelaCadastroEmpresa() {
        initComponents();

        txtIdEmpresa.setVisible(false);
        // Instancia o objeto e executa o método retornando um objetodo tipo
        // Dados empresa
        radioVisualizar.setSelected(true);
        txtUrlBackup.setVisible(false);

        d = dados.selecionaDados();
        // Oculta o botão adicionar se o dados da empresa for diferente de vazio
        //if (d.getNome_empresa().isEmpty()){
        //  lblAdicionar.setVisible(true);
        // }

        txtNomeEmpresa.setText(d.getNome_empresa());
        txtEndereco.setText(d.getEndereco());
        txtNumero.setText(String.valueOf(d.getNumero()));
        txtBairro.setText(d.getBairro());
        txtCep.setText(d.getCep());
        txtCidade.setText(d.getCidade());
        txtTelefone.setText(d.getTelefone());
        txtCelular.setText(d.getCelular());
        txtEmail.setText(d.getEmail());
        txtCnpj.setText(d.getCnpj());
        txtUrlBackup.setText(d.getUrlbackup());
        lblCaminho.setText(txtUrlBackup.getText());
        txturlLogo.setText(d.getLogo());
        txtIdEmpresa.setText(String.valueOf(d.getId()));
        comboUf.setSelectedItem(d.getUf());
        lblLogo.setIcon(u.carregaLogo());
        //Desabilita itens
        btnSelecionarArquivo.setVisible(true);
        lblTextocaminhoBanco.setVisible(true);
        txturlLogo.setVisible(false);
        lblCaminho.setVisible(true);
        //u.setIcon(this);
        lblOperador.setVisible(false);
        lblPerfil.setVisible(false);
        lblCarregaLogo.setVisible(false);
        labelCarregaLogo.setVisible(false);
        lblRealizarBackup.setVisible(false);
        
        if (d.getBkp_auto() == 0) {
            radioManual.setSelected(true);
            lblRealizarBackup.setVisible(true);           
        } else {
            radioAutomatico.setSelected(true);            
        }
        
       
    }

    // Recebe dados para identificação do operador
    public void recebeOperador(String operador, String perfil) {

        lblOperador.setText(operador);
        lblPerfil.setText(perfil);

    }
    public void selecionaComponente(JRadioButton radio){
        if ("Manual".equals(radio.getText())){            
           
             radioAutomatico.setSelected(true);
        }else {
            radioManual.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        labelCarregaLogo = new javax.swing.JLabel();
        lblCarregaLogo = new javax.swing.JLabel();
        txturlLogo = new javax.swing.JTextField();
        txtIdEmpresa = new javax.swing.JTextField();
        txtUrlBackup = new javax.swing.JFormattedTextField();
        lblPerfil = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        lblNomeEmpresa = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        lblUf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        lblCelular = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        lblExcluir = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        jpanelImpressao = new javax.swing.JPanel();
        radioDireto = new javax.swing.JRadioButton();
        radioVisualizar = new javax.swing.JRadioButton();
        lblTextocaminhoBanco = new javax.swing.JLabel();
        lblCaminho = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        btnSelecionarArquivo = new javax.swing.JButton();
        comboUf = new javax.swing.JComboBox<>();
        txtCep = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JFormattedTextField();
        lblMsg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        radioAutomatico = new javax.swing.JRadioButton();
        radioManual = new javax.swing.JRadioButton();
        lblRealizarBackup = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(38, 53, 61));
        jPanel1.setForeground(new java.awt.Color(52, 73, 94));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelCarregaLogo.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        labelCarregaLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelCarregaLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCarregaLogo.setText("Carrega Logo do Sistema");
        labelCarregaLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCarregaLogoMouseClicked(evt);
            }
        });

        lblCarregaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/foto (2).png"))); // NOI18N
        lblCarregaLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarregaLogoMouseClicked(evt);
            }
        });

        txturlLogo.setText("C:\\SysBar\\logo4MasterFood.png");

        txtUrlBackup.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        lblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblPerfil.setText("Perfil");

        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblOperador.setText("operador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(txtIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrlBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCarregaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(txturlLogo)))
                        .addGap(68, 68, 68))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCarregaLogo)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCarregaLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCarregaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOperador)
                    .addComponent(lblPerfil))
                .addGap(70, 70, 70)
                .addComponent(txturlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUrlBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 354, 590);

        jPanel2.setBackground(new java.awt.Color(38, 53, 61));

        lblFechar.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(255, 255, 255));
        lblFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fecharWhite24x24.png"))); // NOI18N
        lblFechar.setPreferredSize(new java.awt.Dimension(40, 40));
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(857, 0, 46, 40);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel3.setText("Dados da Empresa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 20, 310, 50);

        txtNomeEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeEmpresaKeyReleased(evt);
            }
        });
        getContentPane().add(txtNomeEmpresa);
        txtNomeEmpresa.setBounds(360, 110, 330, 30);

        lblNomeEmpresa.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNomeEmpresa.setText("Nome da Empresa");
        getContentPane().add(lblNomeEmpresa);
        lblNomeEmpresa.setBounds(360, 90, 180, 16);

        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyReleased(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(360, 170, 270, 30);

        lblEndereco.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblEndereco.setText("Endereço");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(360, 150, 180, 16);

        lblBairro.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBairro.setText("Bairro");
        getContentPane().add(lblBairro);
        lblBairro.setBounds(360, 210, 140, 16);

        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCidadeKeyReleased(evt);
            }
        });
        getContentPane().add(txtCidade);
        txtCidade.setBounds(610, 230, 210, 30);

        lblComplemento.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblComplemento.setText("Complemento");
        getContentPane().add(lblComplemento);
        lblComplemento.setBounds(700, 150, 110, 16);

        lblCidade.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblCidade.setText("Cidade");
        getContentPane().add(lblCidade);
        lblCidade.setBounds(610, 210, 60, 16);

        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroKeyReleased(evt);
            }
        });
        getContentPane().add(txtBairro);
        txtBairro.setBounds(360, 230, 140, 30);

        lblCEP.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblCEP.setText("CEP");
        getContentPane().add(lblCEP);
        lblCEP.setBounds(510, 210, 70, 16);

        lblUf.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblUf.setText("UF");
        getContentPane().add(lblUf);
        lblUf.setBounds(830, 210, 60, 16);

        lblEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblEmail.setText("E-mail");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(640, 270, 60, 16);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyReleased(evt);
            }
        });
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(360, 290, 130, 30);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCelular);
        txtCelular.setBounds(500, 290, 130, 30);

        lblCelular.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblCelular.setText("Celular");
        getContentPane().add(lblCelular);
        lblCelular.setBounds(500, 270, 60, 16);

        lblCNPJ.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblCNPJ.setText("CNPJ");
        getContentPane().add(lblCNPJ);
        lblCNPJ.setBounds(700, 90, 60, 16);

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCnpjKeyReleased(evt);
            }
        });
        getContentPane().add(txtCnpj);
        txtCnpj.setBounds(700, 110, 190, 30);

        lblExcluir.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fechar.png"))); // NOI18N
        lblExcluir.setText("Limpar");
        lblExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(lblExcluir);
        lblExcluir.setBounds(800, 490, 90, 50);

        lblEditar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/salvar32x32.png"))); // NOI18N
        lblEditar.setText("Salvar");
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarMouseClicked(evt);
            }
        });
        getContentPane().add(lblEditar);
        lblEditar.setBounds(710, 490, 80, 50);

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(640, 290, 250, 30);

        lblTelefone.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(360, 270, 120, 16);

        jpanelImpressao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo de Impressão - Recibo")));

        buttonGroup1.add(radioDireto);
        radioDireto.setText("Imprimir Direto");

        buttonGroup1.add(radioVisualizar);
        radioVisualizar.setText("Visualizar Primeiro");
        radioVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelImpressaoLayout = new javax.swing.GroupLayout(jpanelImpressao);
        jpanelImpressao.setLayout(jpanelImpressaoLayout);
        jpanelImpressaoLayout.setHorizontalGroup(
            jpanelImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelImpressaoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpanelImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioDireto)
                    .addComponent(radioVisualizar))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jpanelImpressaoLayout.setVerticalGroup(
            jpanelImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelImpressaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioDireto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVisualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpanelImpressao);
        jpanelImpressao.setBounds(640, 330, 250, 80);

        lblTextocaminhoBanco.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblTextocaminhoBanco.setText("Local de Backup:");
        getContentPane().add(lblTextocaminhoBanco);
        lblTextocaminhoBanco.setBounds(360, 430, 210, 16);

        lblCaminho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/bd.png"))); // NOI18N
        lblCaminho.setText("Caminho");
        getContentPane().add(lblCaminho);
        lblCaminho.setBounds(370, 450, 510, 40);

        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplementoKeyReleased(evt);
            }
        });
        getContentPane().add(txtComplemento);
        txtComplemento.setBounds(700, 170, 190, 30);

        lblNumero.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNumero.setText("Número");
        getContentPane().add(lblNumero);
        lblNumero.setBounds(640, 150, 60, 16);

        btnSelecionarArquivo.setText("Selecionar ...");
        btnSelecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarArquivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionarArquivo);
        btnSelecionarArquivo.setBounds(460, 420, 100, 30);

        comboUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE" }));
        comboUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUfActionPerformed(evt);
            }
        });
        getContentPane().add(comboUf);
        comboUf.setBounds(830, 230, 60, 30);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCepKeyReleased(evt);
            }
        });
        getContentPane().add(txtCep);
        txtCep.setBounds(510, 230, 90, 30);

        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });
        getContentPane().add(txtNumero);
        txtNumero.setBounds(640, 170, 46, 30);

        lblMsg.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblMsg);
        lblMsg.setBounds(360, 550, 410, 20);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo de Backup")));

        buttonGroup2.add(radioAutomatico);
        radioAutomatico.setText("Automático");
        radioAutomatico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAutomaticoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radioAutomaticoMouseEntered(evt);
            }
        });

        buttonGroup2.add(radioManual);
        radioManual.setText("Manual");
        radioManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioManualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioManual, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioAutomatico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioManual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(360, 330, 272, 80);

        lblRealizarBackup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRealizarBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btnBackup.png"))); // NOI18N
        lblRealizarBackup.setText("Realizar Backup Manual");
        lblRealizarBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRealizarBackupMouseClicked(evt);
            }
        });
        getContentPane().add(lblRealizarBackup);
        lblRealizarBackup.setBounds(360, 490, 270, 48);

        setSize(new java.awt.Dimension(903, 585));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        // Fecha Janela
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void btnSelecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarArquivoActionPerformed
        //Seleciona local do Arquivo

        JFileChooser chooser = new JFileChooser("c:/");
        chooser.setDialogTitle("Selecionar Logo");
        chooser.showOpenDialog(this);

        File file = chooser.getCurrentDirectory();
        String caminho = file.getAbsolutePath();
        txtUrlBackup.setText(caminho);
        lblCaminho.setText(caminho);

    }//GEN-LAST:event_btnSelecionarArquivoActionPerformed

    private void lblExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseClicked

        limpaform();
    }//GEN-LAST:event_lblExcluirMouseClicked

    private void labelCarregaLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCarregaLogoMouseClicked


    }//GEN-LAST:event_labelCarregaLogoMouseClicked

    private void lblCarregaLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarregaLogoMouseClicked
        // Seleciona logo do sistema
        //Seleciona local do Arquivo

        JFileChooser chooser = new JFileChooser(p.getCAMINHO_FOTO_FUNCIONARIO());
        chooser.setDialogTitle("Selecionar Logo do Sistema");
        chooser.showOpenDialog(this);

        File file = chooser.getSelectedFile();
        // Captura Exceção duranete  a seleção do arquivo de logo no cadastro da
        // Empresa
        try {

            String caminho = file.getAbsolutePath();
            txturlLogo.setText(caminho);
            ImageIcon imageIcon = new ImageIcon(caminho);
            Icon i = new ImageIcon(imageIcon.getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH));
            lblLogo.setIcon(i);
        } catch (NullPointerException e) {
            System.out.println("br.com.bar.view.TelaCadastroEmpresa.jLabel2MouseClicked()");
        }

    }//GEN-LAST:event_lblCarregaLogoMouseClicked

    private void lblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseClicked
        DadosEmpresa novoDadosEmpesa = new DadosEmpresa();
        // Instancia objeto dados
        novoDadosEmpesa.setId(Integer.parseInt(txtIdEmpresa.getText()));
        novoDadosEmpesa.setNome_empresa(txtNomeEmpresa.getText());
        novoDadosEmpesa.setEndereco(txtEndereco.getText());
        novoDadosEmpesa.setBairro(txtBairro.getText());
        novoDadosEmpesa.setComplemento(txtComplemento.getText());
        try {
            novoDadosEmpesa.setNumero(Integer.parseInt(txtNumero.getText()));
        } catch (NumberFormatException e) {
            mudaCor(lblNumero);
            txtNumero.requestFocus();

        }
        novoDadosEmpesa.setCep(txtCep.getText());
        novoDadosEmpesa.setCidade(txtCidade.getText());
        novoDadosEmpesa.setTelefone(txtTelefone.getText());
        novoDadosEmpesa.setCelular(txtCelular.getText());
        novoDadosEmpesa.setEmail(txtEmail.getText());
        String cnpj = txtCnpj.getText();
        //Retira ponto do CNPJ
        String cnpjSemPonto = cnpj.replace(".", "");
        cnpj = cnpjSemPonto.replace("/", "");
        cnpjSemPonto = cnpj.replace("-", "");
        novoDadosEmpesa.setCnpj(cnpjSemPonto);

        novoDadosEmpesa.setUrlbackup(txtUrlBackup.getText());
        novoDadosEmpesa.setUf(comboUf.getSelectedItem().toString());
        novoDadosEmpesa.setLogo(txturlLogo.getText());

        if ((radioDireto.isSelected())) {
            // 1 - Imprime na Tela 0 - Imprime Direto
            novoDadosEmpesa.setImprimir_na_tela(1); // Direto para impressora
        } else {
            novoDadosEmpesa.setImprimir_na_tela(0); // Na tela
        }

        if (valida(novoDadosEmpesa)) {
            // Devolve os caracteres especiais removidos durante a validação.
            novoDadosEmpesa.setCnpj(u.imprimeCNPJ(novoDadosEmpesa.getCnpj()));
            //Log
            Date dtAtual = new Date();
            l.setData(u.formataDataBanco(dtAtual));
            l.setFuncionalidade("Alteração");
            l.setDescricao("Alterou os dados da empresa->" + d.getNome_empresa() + " para->" + novoDadosEmpesa.getNome_empresa());
            l.gravaLog(l);

            int op = JOptionPane.showConfirmDialog(null, "Confirma a alteração dos dados?", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {
                if (dados.alteraDados(novoDadosEmpesa)) {
                    JOptionPane.showMessageDialog(this, "Alteração realizada com sucesso!");
                    dispose();
                } else {
                    lblMsg.setText("Não foi possível alterar os dados! Contate o SUPORTE!");
                }
            }
        }


    }//GEN-LAST:event_lblEditarMouseClicked

    private void radioVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioVisualizarActionPerformed

    private void comboUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUfActionPerformed
        if (!"Selecione...".equals(comboUf.getSelectedItem().toString())) {
            lblMsg.setText(null);
            lblUf.setForeground(Color.black);
        }
    }//GEN-LAST:event_comboUfActionPerformed

    private void txtNomeEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeEmpresaKeyReleased
        // Limita Tamanho do Campo ENDEREÇO
        u.tamanhoMaximo(txtEndereco.getText(), 45);
        lblMsg.setText(null);
        lblNomeEmpresa.setForeground(Color.black);
    }//GEN-LAST:event_txtNomeEmpresaKeyReleased

    private void txtComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyReleased
        // Limita Tamanho do Campo COMPLEMENTO
        u.tamanhoMaximo(txtComplemento.getText(), 30);
    }//GEN-LAST:event_txtComplementoKeyReleased

    private void txtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyReleased
        // Limita Tamanho do Campo BAIRRO
        u.tamanhoMaximo(txtBairro.getText(), 35);
        lblMsg.setText(null);
        lblBairro.setForeground(Color.black);
    }//GEN-LAST:event_txtBairroKeyReleased

    private void txtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyReleased
        // Limita Tamanho do Campo CIDADE
        u.tamanhoMaximo(txtCidade.getText(), 45);
        lblMsg.setText(null);
        lblCidade.setForeground(Color.black);
    }//GEN-LAST:event_txtCidadeKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // Limita Tamanho do Campo
        u.tamanhoMaximo(txtEmail.getText(), 245);
        lblMsg.setText(null);
        lblEmail.setForeground(Color.black);

    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost

    }//GEN-LAST:event_txtEmailFocusLost

    private void txtCnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnpjKeyReleased
        lblMsg.setText(null);
        lblCNPJ.setForeground(Color.black);
    }//GEN-LAST:event_txtCnpjKeyReleased

    private void txtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyReleased
        lblMsg.setText(null);
        lblEndereco.setForeground(Color.black);
    }//GEN-LAST:event_txtEnderecoKeyReleased

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        lblMsg.setText(null);
        lblNumero.setForeground(Color.black);
    }//GEN-LAST:event_txtNumeroKeyReleased

    private void txtCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepKeyReleased
        lblMsg.setText(null);
        lblCEP.setForeground(Color.black);
    }//GEN-LAST:event_txtCepKeyReleased

    private void txtTelefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyReleased

    }//GEN-LAST:event_txtTelefoneKeyReleased

    private void radioAutomaticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAutomaticoMouseClicked

        authBkp.setAlwaysOnTop(true);
        authBkp.recebeTela(this, "1",radioAutomatico);
        authBkp.setVisible(true);
    }//GEN-LAST:event_radioAutomaticoMouseClicked

    private void radioManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioManualMouseClicked
        authBkp.setAlwaysOnTop(true);
        authBkp.recebeTela(this, "0",radioManual);
        authBkp.setVisible(true);
    }//GEN-LAST:event_radioManualMouseClicked

    private void lblRealizarBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRealizarBackupMouseClicked
        // Realiza Backup Manualmente
        Backup bkp = new Backup();
        try {
            bkp.realizaBackup();
        } catch (IOException e) {
            System.out.println("br.com.bar.view.TelaCadastroEmpresa.lblRealizarBackupMouseClicked()"+e);
        }

    }//GEN-LAST:event_lblRealizarBackupMouseClicked

    private void radioAutomaticoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAutomaticoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAutomaticoMouseEntered

    public void ativarBackup(String valor) {
        dados.ativaBackup(valor);
        System.out.println(valor);

        if (valor.equals("1")) {
            radioAutomatico.setSelected(true);
            lblRealizarBackup.setVisible(false);
        } else {
            radioManual.setSelected(true);
            lblRealizarBackup.setVisible(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionarArquivo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpanelImpressao;
    private javax.swing.JLabel labelCarregaLogo;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCaminho;
    private javax.swing.JLabel lblCarregaLogo;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblRealizarBackup;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTextocaminhoBanco;
    private javax.swing.JLabel lblUf;
    private javax.swing.JRadioButton radioAutomatico;
    private javax.swing.JRadioButton radioDireto;
    private javax.swing.JRadioButton radioManual;
    private javax.swing.JRadioButton radioVisualizar;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIdEmpresa;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JFormattedTextField txtUrlBackup;
    private javax.swing.JTextField txturlLogo;
    // End of variables declaration//GEN-END:variables

    private void limpaform() {
        txtNomeEmpresa.setText(null);
        txtCnpj.setText(null);
        txtEndereco.setText(null);
        txtNumero.setText(null);
        txtComplemento.setText(null);
        txtBairro.setText(null);
        txtCep.setText(null);
        txtCidade.setText(null);
        comboUf.setSelectedItem("Selecione...");
        txtTelefone.setText(null);
        txtCelular.setText(null);
        txtEmail.setText(null);
        radioVisualizar.setSelected(true);
        lblCaminho.setText(null);
        //lblLogo.setIcon(null);

    }

    private boolean valida(DadosEmpresa d) {
        // Seta  resposta padrão com TRUE.
        boolean resp = true;

        if ("".equals(d.getNome_empresa())) {
            lblMsg.setText("*Informe o NOME DA EMPRESA para continuar!");
            txtNomeEmpresa.requestFocus();
            mudaCor(lblNomeEmpresa);
            resp = false;
        } else if ("  .   .   /    -  ".equals(d.getCnpj()) || !u.isCNPJ(d.getCnpj())) {// 00.000.000/0001-00
            lblMsg.setText("*Informe o CNPJ para continuar!");
            mudaCor(lblCNPJ);
            txtCnpj.requestFocus();
            resp = false;
        } else if ("".equals(d.getEndereco())) {
            lblMsg.setText("*Informe o ENDEREÇO para continuar!");
            mudaCor(lblEndereco);
            txtEndereco.requestFocus();
            resp = false;
        } else if ("".equals(txtNumero.getText())) {
            lblMsg.setText("*Informe o NÚMERO para continuar!");
            mudaCor(lblNumero);
            txtNumero.requestFocus();
            resp = false;
        } else if ("".equals(d.getBairro())) {
            lblMsg.setText("*Informe o BAIRRO para continuar!");
            mudaCor(lblBairro);
            txtBairro.requestFocus();
            resp = false;
        } else if (d.getCep().equals("     -   ")
                || d.getCep().equals("00000-000") || d.getCep().equals("11111-111")
                || d.getCep().equals("22222-222") || d.getCep().equals("33333-333")
                || d.getCep().equals("44444-444") || d.getCep().equals("55555-555")
                || d.getCep().equals("66666-666") || d.getCep().equals("77777-777")
                || d.getCep().equals("88888-888") || d.getCep().equals("99999-999")
                || (d.getCep().length() != 9)) {
            lblMsg.setText("*Informe um CEP válido para continuar!");
            mudaCor(lblCEP);
            txtCep.requestFocus();
            resp = false;
        } else if ("".equals(d.getCidade())) {
            lblMsg.setText("*Informe a CIDADE para continuar!");
            mudaCor(lblCidade);
            txtCidade.requestFocus();
            resp = false;
        } else if ("Selecione...".equals(comboUf.getSelectedItem().toString())) {
            lblMsg.setText("*Informe a UF para continuar!");
            mudaCor(lblUf);
            comboUf.requestFocus();
            resp = false;
        } else if ("".equals(d.getEmail())) {
            lblMsg.setText("*Informe o E-mail para continuar!");
            mudaCor(lblEmail);
            lblEmail.requestFocus();
            resp = false;
        }

        return resp;
    }

    private void mudaCor(JLabel label) {
        label.setForeground(Color.red);
    }
}
