/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.CriptoGrafa;
import br.com.bar.dao.Email;
import br.com.bar.model.DadosEmpresa;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerAtivacao;
import br.com.br.controler.ControlerDadosEmpresa;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Elias Santana
 */
public class TelaGerenciadorDeLicenca extends javax.swing.JFrame {

    ControlerDadosEmpresa empresa = new ControlerDadosEmpresa();
    CriptoGrafa cripto = new CriptoGrafa();
    ControlerAtivacao a = new ControlerAtivacao();
    DadosEmpresa d = empresa.selecionaDados();
    ControlerAtivacao ativacao = new ControlerAtivacao();
    Util u = new Util();

    public TelaGerenciadorDeLicenca() {
        initComponents();
        lblDias.setVisible(false);
        this.setAlwaysOnTop(true);   
       
        
    }
    
    public void recebeDias(long dias,String mensagem){
        lblDias.setText(String.valueOf(dias));
        lblMensagem.setText(mensagem);
        lblMensagem.setForeground(Color.RED);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSolicitaLicenca = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelInstalarChave = new javax.swing.JPanel();
        lblChave = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();

        jLabel5.setText("Para renovar sua licença entre em contato com o suporte da RESE7 soluções em TI");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(38, 53, 61));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MasterFood - Gerenciador de Licença");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 24, 460, 62);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(441, 0, 29, 33);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 110);

        lblMensagem.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblMensagem.setText("Sua licença expira em:  ");
        getContentPane().add(lblMensagem);
        lblMensagem.setBounds(30, 150, 400, 25);

        jLabel4.setText("Para renovar sua licença entre em contato com a área comercial.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 390, 20);

        btnSolicitaLicenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/email.png"))); // NOI18N
        btnSolicitaLicenca.setText("Solicitar nova licença agora");
        btnSolicitaLicenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitaLicencaMouseClicked(evt);
            }
        });
        btnSolicitaLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitaLicencaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitaLicenca);
        btnSolicitaLicenca.setBounds(30, 210, 420, 41);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("R. Amambaí, 246 - Candeias, Jaboatão dos Guararapes - PE, 54430-160");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 310, 420, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("Telefones: (81) 99749-6602 | (81) 99678-1659");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 370, 348, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("RESE7 Soluções em TI");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 270, 348, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("CNPJ  26.650.398/0001-03");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 330, 348, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("email: contato.rese7@gmai.com");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 350, 348, 15);

        panelInstalarChave.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblChave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChave.setText("Instalar Nova Chave");
        lblChave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelInstalarChaveLayout = new javax.swing.GroupLayout(panelInstalarChave);
        panelInstalarChave.setLayout(panelInstalarChaveLayout);
        panelInstalarChaveLayout.setHorizontalGroup(
            panelInstalarChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChave, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        panelInstalarChaveLayout.setVerticalGroup(
            panelInstalarChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        getContentPane().add(panelInstalarChave);
        panelInstalarChave.setBounds(310, 380, 140, 40);

        lblDias.setText("jLabel2");
        getContentPane().add(lblDias);
        lblDias.setBounds(30, 120, 34, 14);

        setSize(new java.awt.Dimension(470, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // Fecha Tela

        if (Integer.parseInt(lblDias.getText()) > 0) {
            dispose();
        } else {
            System.exit(0);
        }

    }//GEN-LAST:event_jLabel6MouseClicked

    private void lblChaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChaveMouseClicked
        // Chama Tela de Ativação
        dispose();
        TelaAtivacao a = new TelaAtivacao();
        a.setVisible(true);
    }//GEN-LAST:event_lblChaveMouseClicked

    private void btnSolicitaLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitaLicencaActionPerformed
        // Solicita nova Licennça
        Email email = new Email();
        ControlerDadosEmpresa ce = new ControlerDadosEmpresa();
        // Seleciona os dados do cadastro da empresa
        DadosEmpresa dados = ce.selecionaDados();
        
        
        String assunto = "MasterFood - Solicitação de Renovação de Licença: " + dados.getNome_empresa();
        String mensagem = "Solicitante: "
                + dados.getNome_empresa() + "\nCNPJ: " + dados.getCnpj()+ "\nLicença Atual: " + dados.getLicenca()+"\nTelefone: "+dados.getTelefone() 
                +"\nEndereço: " + dados.getEndereco()+","+dados.getNumero() + " \nBairro:" + dados.getBairro() + "CEP: "+dados.getCep() 
                + "  Cidade: "+dados.getCidade() + "  UF: "+dados.getUf()   + "\nStatus: "+ lblMensagem.getText();  
       
        if (email.enviaEmail("contato.rese7@gmail.com", assunto, mensagem)){
            btnSolicitaLicenca.setText("Solicitação enviada com sucesso!");
            btnSolicitaLicenca.setForeground(Color.GREEN);
        }
        
    }//GEN-LAST:event_btnSolicitaLicencaActionPerformed

    private void btnSolicitaLicencaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitaLicencaMouseClicked
        
    }//GEN-LAST:event_btnSolicitaLicencaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciadorDeLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciadorDeLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciadorDeLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciadorDeLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciadorDeLicenca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitaLicenca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChave;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JPanel panelInstalarChave;
    // End of variables declaration//GEN-END:variables
}
