/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.AutenticaUsuario;
import br.com.br.controler.ControlerFuncionario;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias Santana
 */
public class TelaAlteraSenha extends javax.swing.JFrame {

    ControlerFuncionario cf = new ControlerFuncionario();
    AutenticaUsuario auth = new AutenticaUsuario();
    String loginOperador;

    /**
     * Creates new form TelaBloqueio
     */
    public TelaAlteraSenha() {
        initComponents();
        estadoInicial();
        loginOperador="Admin";
       
    }

    private void estadoInicial() {
        lblSenhaAtualOK.setVisible(false);
        lblOkConfirma.setVisible(false);
        lblSenhaAtual.setEnabled(true);
        lblNovaSenha.setEnabled(false);
        lblSenhaConfirmada.setEnabled(false);
        txtConfirmaSnh.setEnabled(false);
        txtNovaSnh.setEnabled(false);
        btnAlterar.setEnabled(false);
        lblError.setVisible(false);

    }

    private void habilitaTroca() {
        txtSenhaAtual.setEnabled(false);
        lblSenhaAtualOK.setEnabled(true);
        lblNovaSenha.setEnabled(true);
        lblOkConfirma.setEnabled(true);
        txtNovaSnh.setEnabled(true);
        txtConfirmaSnh.setEnabled(true);
        lblSenhaConfirmada.setEnabled(true);
    }

    public void receberOperador(String operador) {
        this.loginOperador = operador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        lblSenhaConfirmada = new javax.swing.JLabel();
        txtSenhaAtual = new javax.swing.JPasswordField();
        btnAlterar = new javax.swing.JButton();
        txtConfirmaSnh = new javax.swing.JPasswordField();
        lblSenhaAtual = new javax.swing.JLabel();
        lblNovaSenha = new javax.swing.JLabel();
        txtNovaSnh = new javax.swing.JPasswordField();
        lblOkConfirma = new javax.swing.JLabel();
        lblSenhaAtualOK = new javax.swing.JLabel();
        btnAlterar1 = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 53, 61));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alteração de Senha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblMsg.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 280, 20));

        lblSenhaConfirmada.setText("Confirme a nova Senha");
        jPanel2.add(lblSenhaConfirmada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 130, 30));

        txtSenhaAtual.setToolTipText("Informe a senha e Presione [Enter]");
        txtSenhaAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaAtualKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaAtualKeyReleased(evt);
            }
        });
        jPanel2.add(txtSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 30));

        txtConfirmaSnh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmaSnhKeyPressed(evt);
            }
        });
        jPanel2.add(txtConfirmaSnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, 30));

        lblSenhaAtual.setText("Senha Atual");
        jPanel2.add(lblSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 30));

        lblNovaSenha.setText("Nova Senha");
        jPanel2.add(lblNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 30));

        txtNovaSnh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNovaSnhKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNovaSnhKeyReleased(evt);
            }
        });
        jPanel2.add(txtNovaSnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 30));

        lblOkConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/aplicar.png"))); // NOI18N
        jPanel2.add(lblOkConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 30, 30));

        lblSenhaAtualOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/aplicar.png"))); // NOI18N
        jPanel2.add(lblSenhaAtualOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 30));

        btnAlterar1.setText("Cancelar");
        btnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlterar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, 30));

        lblError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fechar_vermelho.png"))); // NOI18N
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 30));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 318, 230);

        setSize(new java.awt.Dimension(318, 231));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnAlterar1ActionPerformed

    private void txtSenhaAtualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaAtualKeyPressed
        String senha = txtSenhaAtual.getText().toLowerCase();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (auth.isExistsSenha(txtSenhaAtual.getText().toLowerCase())) {

                if (auth.autentica2(loginOperador, senha)) {                  
                 
                    lblSenhaAtualOK.setVisible(true);
                    habilitaTroca();
                    txtNovaSnh.requestFocus();
                }
            } else {
               
            }
        }
    }//GEN-LAST:event_txtSenhaAtualKeyPressed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String idOperador = cf.localizaIdLogin(loginOperador);
        if (txtSenhaAtual.getText().equals(txtConfirmaSnh.getText())){
             lblMsg.setText("*A nova senha não pode ser igual a anterior!");
        }else {
             
             if (cf.alteraSenha(txtConfirmaSnh.getText(),idOperador)){
                JOptionPane.showMessageDialog(this, "Senha alterada com sucesso!");
                dispose();
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtSenhaAtualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaAtualKeyReleased


    }//GEN-LAST:event_txtSenhaAtualKeyReleased

    private void txtNovaSnhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNovaSnhKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           txtConfirmaSnh.requestFocus();
        }
    }//GEN-LAST:event_txtNovaSnhKeyPressed

    private void txtConfirmaSnhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmaSnhKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           if (txtNovaSnh.getText().equals(txtConfirmaSnh.getText())){               
               btnAlterar.setEnabled(true);
               lblOkConfirma.setVisible(true);
               lblError.setVisible(false);
               lblMsg.setForeground(Color.BLUE);
               lblMsg.setText("*Clique em alterar para proseguir!");
           }else {
                lblOkConfirma.setVisible(false);
                lblError.setVisible(true);
                lblMsg.setForeground(Color.RED);
                lblMsg.setText("*As senhas informadas não são iguais!");
           }
        }
    }//GEN-LAST:event_txtConfirmaSnhKeyPressed

    private void txtNovaSnhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNovaSnhKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaSnhKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlteraSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblNovaSenha;
    private javax.swing.JLabel lblOkConfirma;
    private javax.swing.JLabel lblSenhaAtual;
    private javax.swing.JLabel lblSenhaAtualOK;
    private javax.swing.JLabel lblSenhaConfirmada;
    private javax.swing.JPasswordField txtConfirmaSnh;
    private javax.swing.JPasswordField txtNovaSnh;
    private javax.swing.JPasswordField txtSenhaAtual;
    // End of variables declaration//GEN-END:variables

    private void desbloquear() {
        if (auth.isExistsSenha(txtSenhaAtual.getText())) {
            if (auth.autentica2(loginOperador, txtSenhaAtual.getText())) {
                dispose();
            } else {
                lblMsg.setText("*Senha inválida!");
            }
        } else {
            lblMsg.setText("*Senha inválida!");
        }
    }

}
