/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.model.Mesa;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerMesa;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias Santana
 */
public class TelaPedido3 extends javax.swing.JFrame {

    ControlerMesa controlerMesa = new ControlerMesa();
    Util u = new Util();

    ResultSet rs;
    ArrayList<Mesa> listaDeMesas;

    public TelaPedido3() {
        initComponents();
        listaDeMesas = controlerMesa.listaTodasAsMesas();
        panelaMesas.setLayout(new GridLayout(3, 2));

        for (int i = 0; i < listaDeMesas.size(); i++) {
            JButton btn = new JButton();
            btn.setBounds(0, 0, 100, 50);
            btn.setFont(new Font("Arial", Font.PLAIN, 14));
            btn.setText(listaDeMesas.get(i).getNumeroMesa());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                    if (controlerMesa.estaLivre(btn.getText())) {
                        int op = JOptionPane.showConfirmDialog(null, "Deseja abrir um novo pedido para a mesa-> " + btn.getText(), "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
                        if (op == JOptionPane.YES_OPTION) {
                            JOptionPane.showMessageDialog(null, "Abrir novo Pedido");
                            btn.setForeground(Color.white);
                            btn.setBackground(Color.RED);
                        }
                    } else {
                        TelaDetalheMesa dtlMesa = new TelaDetalheMesa();
                        dtlMesa.recebeMesa(btn.getText());
                        dtlMesa.setVisible(true);
                    }
                }

                @Override
                public void mousePressed(MouseEvent me) {

                }

                @Override
                public void mouseReleased(MouseEvent me) {

                }

                @Override
                public void mouseEntered(MouseEvent me) {

                }

                @Override
                public void mouseExited(MouseEvent me) {

                }
            });
            if ("0".equals(listaDeMesas.get(i).getStatus())) {
                btn.setForeground(Color.BLACK);
                btn.setBackground(new Color(0, 255, 127));
            } else {
                btn.setForeground(Color.white);
                btn.setBackground(Color.RED);
            }
            panelaMesas.add(btn);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelaMesas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MasterFood - Pedidos - Listagem de Mesas");
        setExtendedState(6);

        javax.swing.GroupLayout panelaMesasLayout = new javax.swing.GroupLayout(panelaMesas);
        panelaMesas.setLayout(panelaMesasLayout);
        panelaMesasLayout.setHorizontalGroup(
            panelaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelaMesasLayout.setVerticalGroup(
            panelaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelaMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelaMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedido3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedido3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedido3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedido3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedido3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelaMesas;
    // End of variables declaration//GEN-END:variables
}
