/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.model.DadosEmpresa;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerDadosEmpresa;
import br.com.br.controler.ControlerParametro;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class TelaCadastroEmpresa extends javax.swing.JFrame {

    ControlerDadosEmpresa dados = new ControlerDadosEmpresa();
    ControlerParametro p = new ControlerParametro();
    DadosEmpresa d = dados.selecionaDados();
    Util u = new Util();

    /**
     * Creates new form TelaCadastroEmpresa
     */
    public TelaCadastroEmpresa() {
        initComponents();
         lblAdicionar.setVisible(false);
         txtIdEmpresa.setVisible(false);
        // Instancia o objeto e executa o método retornando um objetodo tipo
        // Dados empresa
        radioVisualizar.setSelected(true);
        txtUrlBackup.setVisible(false);

        d = dados.selecionaDados();
        // Oculta o botão adicionar se o dados da empresa for diferente de vazio
        if (d.getNome_empresa().isEmpty()){
            lblAdicionar.setVisible(true);
        }
        txtNomeEmpresa.setText(d.getNome_empresa());
        txtEndereco.setText(d.getEndereco());
        txtNumero.setText(String.valueOf(d.getNumero()));
        txtBairro.setText(d.getBairro());
        txtCep.setText(d.getCep());
        txtCidade.setText(d.getCidade());
        txtUF.setText(d.getUf());
        txtTelefone.setText(d.getTelefone());
        txtCelular.setText(d.getCelular());
        txtEmail.setText(d.getEmail());
        txtCnpj.setText(d.getCnpj());
        txtUrlBackup.setText(d.getUrlbackup());
        lblCaminho.setText(txtUrlBackup.getText());
        txturlLogo.setText(d.getLogo());
        txtIdEmpresa.setText(String.valueOf(d.getId()));      
        
        lblLogo.setIcon(u.carregaLogo());
        //Desabilita itens
        btnSelecionarArquivo.setVisible(true);
        lblTextocaminhoBanco.setVisible(true);
        txturlLogo.setVisible(true);
        lblCaminho.setVisible(true);
    }

    // Recebe dados para identificação do operador
    
    public void recebeOperador(String operador, String perfil) {

        lblOperador.setText(operador);
        lblPerfil.setText(perfil);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txturlLogo = new javax.swing.JTextField();
        txtIdEmpresa = new javax.swing.JTextField();
        txtUrlBackup = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        txtBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JFormattedTextField();
        lblExcluir = new javax.swing.JLabel();
        lblAdicionar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtUF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jpanelImpressao = new javax.swing.JPanel();
        radioDireto = new javax.swing.JRadioButton();
        radioVisualizar = new javax.swing.JRadioButton();
        lblTextocaminhoBanco = new javax.swing.JLabel();
        lblCaminho = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnSelecionarArquivo = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(38, 53, 61));
        jPanel1.setForeground(new java.awt.Color(52, 73, 94));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/logo.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dados Empresa");

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Carrega Logo do Sistema");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/foto (2).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        txtUrlBackup.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(txtIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUrlBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txturlLogo))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txturlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUrlBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 344, 590);

        jPanel2.setBackground(new java.awt.Color(38, 53, 61));

        lblFechar.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(255, 255, 255));
        lblFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechar.setText("X");
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(857, 0, 46, 43);

        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblOperador.setText("operador");
        getContentPane().add(lblOperador);
        lblOperador.setBounds(420, 40, 99, 32);

        lblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblPerfil.setText("Perfil");
        getContentPane().add(lblPerfil);
        lblPerfil.setBounds(520, 40, 110, 32);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel3.setText("Cadastro Empresa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 80, 310, 50);
        getContentPane().add(txtNomeEmpresa);
        txtNomeEmpresa.setBounds(360, 210, 227, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel5.setText("Nome da Empresa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 190, 180, 16);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(360, 270, 250, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel6.setText("Endereço");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 250, 180, 16);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel7.setText("Bairro");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 310, 140, 16);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(610, 330, 210, 30);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel8.setText("Complemento");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(680, 250, 110, 16);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel9.setText("Cidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(610, 310, 60, 16);
        getContentPane().add(txtCep);
        txtCep.setBounds(510, 330, 90, 30);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(360, 330, 140, 30);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel10.setText("CEP");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 310, 70, 16);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel11.setText("UF");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(830, 310, 60, 16);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel12.setText("e-mail");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(640, 370, 60, 16);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(360, 390, 130, 30);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCelular);
        txtCelular.setBounds(500, 390, 130, 30);

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel13.setText("Celular");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(500, 370, 60, 16);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel15.setText("CNPJ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(600, 190, 60, 16);

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCnpj);
        txtCnpj.setBounds(600, 210, 290, 30);

        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(txtNumero);
        txtNumero.setBounds(620, 270, 46, 30);

        lblExcluir.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Lixeira.png"))); // NOI18N
        lblExcluir.setText("Excluir");
        lblExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(lblExcluir);
        lblExcluir.setBounds(790, 140, 90, 50);

        lblAdicionar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/adicionas32x32.png"))); // NOI18N
        lblAdicionar.setText("Adicionar");
        lblAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdicionarMouseClicked(evt);
            }
        });
        getContentPane().add(lblAdicionar);
        lblAdicionar.setBounds(580, 142, 100, 50);

        lblEditar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/salvar32x32.png"))); // NOI18N
        lblEditar.setText("Salvar");
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarMouseClicked(evt);
            }
        });
        getContentPane().add(lblEditar);
        lblEditar.setBounds(700, 140, 80, 50);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(640, 390, 250, 30);
        getContentPane().add(txtUF);
        txtUF.setBounds(830, 330, 60, 30);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel14.setText("Telefone");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(360, 370, 120, 16);

        jpanelImpressao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo de Impressão - Recibo")));

        buttonGroup1.add(radioDireto);
        radioDireto.setText("Imprimir Direto");

        buttonGroup1.add(radioVisualizar);
        radioVisualizar.setText("Visualizar Primeiro");
        radioVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelImpressaoLayout = new javax.swing.GroupLayout(jpanelImpressao);
        jpanelImpressao.setLayout(jpanelImpressaoLayout);
        jpanelImpressaoLayout.setHorizontalGroup(
            jpanelImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelImpressaoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpanelImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioDireto)
                    .addComponent(radioVisualizar))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jpanelImpressaoLayout.setVerticalGroup(
            jpanelImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelImpressaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioDireto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVisualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpanelImpressao);
        jpanelImpressao.setBounds(640, 450, 250, 80);

        lblTextocaminhoBanco.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblTextocaminhoBanco.setText("Local de Backup");
        getContentPane().add(lblTextocaminhoBanco);
        lblTextocaminhoBanco.setBounds(360, 450, 210, 16);

        lblCaminho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/bd.png"))); // NOI18N
        lblCaminho.setText("Caminho");
        getContentPane().add(lblCaminho);
        lblCaminho.setBounds(360, 520, 190, 40);
        getContentPane().add(txtComplemento);
        txtComplemento.setBounds(680, 270, 210, 30);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel16.setText("Número");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(620, 250, 60, 16);

        btnSelecionarArquivo.setText("Selecionar ...");
        btnSelecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarArquivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionarArquivo);
        btnSelecionarArquivo.setBounds(360, 470, 100, 40);

        setSize(new java.awt.Dimension(902, 585));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        // Fecha Janela
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void lblAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdicionarMouseClicked

        // Instancia objeto dados
        d.setNome_empresa(txtNomeEmpresa.getText());
        d.setEndereco(txtEndereco.getText());
        d.setBairro(txtBairro.getText());
        try {

            d.setNumero(Integer.parseInt(txtNumero.getText()));
        } catch (NumberFormatException e) {
            System.out.println("br.com.bar.view.TelaCadastroEmpresa.lblAlterarMouseClicked()" + e);
        }
        d.setCep(txtCep.getText());
        d.setCidade(txtCidade.getText());
        d.setTelefone(txtTelefone.getText());
        d.setCelular(txtCelular.getText());
        d.setEmail(txtEmail.getText());
        d.setCnpj(txtCnpj.getText());
        d.setUrlbackup(txtUrlBackup.getText());
        d.setLogo(txturlLogo.getText());
        d.setUf(txtUF.getText());
        String btnSelecionado=buttonGroup1.getSelection().toString();
        
        if ("Imprimir Direto".equals(btnSelecionado)){
            // 1 - Imprime na Tela 0 - Imprime Direto
            d.setImprimir_na_tela(0); // Na tela
        }else {
            d.setImprimir_na_tela(1); // Direto para impressora
        }

        if ("".equals(txtNomeEmpresa.getText()) || txtNomeEmpresa.getText() == null) {
            JOptionPane.showMessageDialog(null, "Dados inválidos, preencha todos os campos para continuar!");
        } else {
            if (dados.adicionaDados(d)) {
                JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");

            } else {
                JOptionPane.showMessageDialog(null, "Impossível salvar dados");

            }
        }


    }//GEN-LAST:event_lblAdicionarMouseClicked

    private void btnSelecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarArquivoActionPerformed
        //Seleciona local do Arquivo

        JFileChooser chooser = new JFileChooser("c:/");
        chooser.setDialogTitle("Selecionar Logo");
        chooser.showOpenDialog(this);

        File file = chooser.getCurrentDirectory();
        String caminho = file.getAbsolutePath();
        txtUrlBackup.setText(caminho);
        lblCaminho.setText(caminho);

    }//GEN-LAST:event_btnSelecionarArquivoActionPerformed

    private void lblExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseClicked
        // Exclui empresa
        DadosEmpresa objEmpresa = dados.selecionaDados();
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir \n os dados da empresa?","Atenção!",JOptionPane.YES_NO_OPTION);
        if (op==JOptionPane.YES_OPTION){
            
            if (dados.excluiEmpresa(objEmpresa)) {
                JOptionPane.showMessageDialog(null, "Dados excluídos com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, " Não foi possível excluir os dados desta empresa!");
            }
        }else {
                JOptionPane.showMessageDialog(null, " Exclusão cancelada com sucesso!");
            
        }
    }//GEN-LAST:event_lblExcluirMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked


    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // Seleciona logo do sistema
        //Seleciona local do Arquivo

        JFileChooser chooser = new JFileChooser(p.getCAMINHO_FOTO_FUNCIONARIO());
        chooser.setDialogTitle("Selecionar Logo do Sistema");
        chooser.showOpenDialog(this);

        File file = chooser.getSelectedFile();
        String caminho = file.getAbsolutePath();
        txturlLogo.setText(caminho);
        ImageIcon imageIcon = new ImageIcon(caminho);
        Icon i = new ImageIcon(imageIcon.getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH));

        lblLogo.setIcon(i);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseClicked
        
         // Instancia objeto dados
        d.setId(Integer.parseInt(txtIdEmpresa.getText()));
        d.setNome_empresa(txtNomeEmpresa.getText());
        d.setEndereco(txtEndereco.getText());
        d.setBairro(txtBairro.getText());
        try {

            d.setNumero(Integer.parseInt(txtNumero.getText()));
        } catch (NumberFormatException e) {
            System.out.println("br.com.bar.view.TelaCadastroEmpresa.lblAlterarMouseClicked()" + e);
        }
        d.setCep(txtCep.getText());
        d.setCidade(txtCidade.getText());
        d.setTelefone(txtTelefone.getText());
        d.setCelular(txtCelular.getText());
        d.setEmail(txtEmail.getText());
        d.setCnpj(txtCnpj.getText());
        d.setUrlbackup(txtUrlBackup.getText());
        d.setUf(txtUF.getText());
        d.setLogo(txturlLogo.getText());
        
        System.out.println("nome Empresa" +d.getNome_empresa());
        if ((radioDireto.isSelected())){
            // 1 - Imprime na Tela 0 - Imprime Direto
            d.setImprimir_na_tela(1); // Direto para impressora
        }else {
            d.setImprimir_na_tela(0); // Na tela
        }
        
        if ("".equals(txtNomeEmpresa.getText()) || txtNomeEmpresa.getText() == null) {
            JOptionPane.showMessageDialog(null, "Dados inválidos, preencha todos os campos para continuar!");
        } else {
            int op = JOptionPane.showConfirmDialog(null,"Confirma a alteração?","Atenção",JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE );
            if (op == JOptionPane.YES_OPTION){
                
                if (dados.alteraDados(d)) {
                    JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível alterar os dados!");
                }
            }else {
                JOptionPane.showMessageDialog(null, "Alteração cancelada com sucesso!");
            }
        }
        
    }//GEN-LAST:event_lblEditarMouseClicked

    private void radioVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioVisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionarArquivo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpanelImpressao;
    private javax.swing.JLabel lblAdicionar;
    private javax.swing.JLabel lblCaminho;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblTextocaminhoBanco;
    private javax.swing.JRadioButton radioDireto;
    private javax.swing.JRadioButton radioVisualizar;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIdEmpresa;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUF;
    private javax.swing.JFormattedTextField txtUrlBackup;
    private javax.swing.JTextField txturlLogo;
    // End of variables declaration//GEN-END:variables
}
