/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.Log;
import br.com.bar.model.Funcionario;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerParametro;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author elias
 */
public class TelaCadastroFuncionario extends javax.swing.JFrame {

    ControlerParametro parametro = new ControlerParametro();
    ControlerFuncionario funcionario = new ControlerFuncionario();
    Util u = new Util();
    // Inicia Instância de log
    Log l = new Log();

    /**
     * Creates new form TelaCadastroFuncionario
     */
    public TelaCadastroFuncionario() {
        initComponents();
        txtCaminho.setVisible(false);
        txtId.setVisible(false);
        txtOperacao.setVisible(false);
        jtableGuias.setVisible(false);

    }

    public void recebeOperador(String operador, String cargo, String operacao) {

        lblCargo.setText(cargo);
        lblOperador.setText(operador);
        txtOperacao.setText(operacao);
        l.setUsuario(operador);
        Date data = new Date();

        if ("Adicionar".equals(operacao)) {

        } else {

            carregaFoto();
            bloqueiaCampos();
        }
    }

    public void recebeFuncionario(Funcionario f) {
        txtId.setText(f.getId());
        txtNome.setText(f.getNome());
        txtEndereço.setText(f.getEndereco());
        txtBairro.setText(f.getBairro());
        txtCep.setText(f.getBairro());
        txtCidade.setText(f.getCidade());
        txtCep.setText(f.getCep());
        txtTelefone.setText(f.getTelefone());
        txtEmail.setText(f.getEmail());
        txtLogin.setText(f.getLogin());
        txtSenha.setText(f.getSenha());
        txtComplemento.setText(f.getComplemento());
        txtNumero.setText(f.getNumero());
        txtRg.setText(f.getRg());
        txtCpf.setText(f.getCpf());
        txtCnh.setText(f.getCnh());
        txtTelRecado.setText(f.getTelefone_recado());
        comboCargo.setSelectedItem(f.getCargo());
        txtCaminho.setText(f.getFoto());

        if (f.getStatus().equals("0")) {
            comboSituacao.setSelectedItem("Ativo");
        } else {
            comboSituacao.setSelectedItem("Inativo");
        }

        if (f.getBloqueado().equals("0")) {
            comboBloqueio.setSelectedItem("Desbloqueado");
        } else {
            comboBloqueio.setSelectedItem("Bloqueado");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereço = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        comboCargo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboSituacao = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboBloqueio = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCnh = new javax.swing.JFormattedTextField();
        lbltemMesa = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtUf = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtTelRecado = new javax.swing.JFormattedTextField();
        lblTelefone1 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleHistorico = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCaminho = new javax.swing.JTextField();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        txtOperacao = new javax.swing.JTextField();
        jtableGuias = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        lblNome.setText("Nome *");
        jPanel1.add(lblNome);
        lblNome.setBounds(10, 8, 130, 20);
        jPanel1.add(txtNome);
        txtNome.setBounds(10, 27, 365, 30);
        jPanel1.add(txtEndereço);
        txtEndereço.setBounds(10, 80, 470, 30);

        jLabel2.setText("UF");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 160, 60, 20);

        jLabel3.setText("CEP");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 110, 70, 20);

        jLabel4.setText("Complemento");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 100, 20);
        jPanel1.add(txtBairro);
        txtBairro.setBounds(130, 130, 110, 30);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCep);
        txtCep.setBounds(250, 130, 90, 30);

        jLabel5.setText("Cidade");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 110, 90, 20);
        jPanel1.add(txtCidade);
        txtCidade.setBounds(350, 130, 200, 30);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(80, 180, 230, 30);

        jLabel6.setText("E-mail");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 160, 100, 20);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(570, 10, 140, 150);

        lblTelefone.setText("Celular");
        jPanel1.add(lblTelefone);
        lblTelefone.setBounds(590, 210, 90, 20);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(450, 230, 130, 30);

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garçom", "Caixa", "Gerente", "Cozinheiro", "Estoquista", "" }));
        jPanel1.add(comboCargo);
        comboCargo.setBounds(10, 290, 169, 30);

        jLabel9.setText("Cargo");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 270, 110, 14);

        jLabel10.setText("Login");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(320, 160, 90, 20);
        jPanel1.add(txtLogin);
        txtLogin.setBounds(320, 180, 120, 30);
        jPanel1.add(txtSenha);
        txtSenha.setBounds(450, 180, 100, 30);

        jLabel11.setText("Senha");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(450, 160, 90, 20);

        comboSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        comboSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSituacaoActionPerformed(evt);
            }
        });
        jPanel1.add(comboSituacao);
        comboSituacao.setBounds(190, 290, 70, 30);

        jLabel12.setText("Situação");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(190, 270, 70, 14);

        jLabel13.setText("Bloqueio");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(270, 270, 120, 14);

        comboBloqueio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desbloqueado", "Bloqueado" }));
        jPanel1.add(comboBloqueio);
        comboBloqueio.setBounds(270, 290, 100, 30);

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(52, 73, 94));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/camera.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(610, 160, 70, 50);

        jLabel1.setText("CPF");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 210, 70, 20);

        jLabel7.setText("RG");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 210, 50, 20);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCpf);
        txtCpf.setBounds(150, 230, 130, 30);

        txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jPanel1.add(txtRg);
        txtRg.setBounds(10, 230, 130, 30);

        jLabel8.setText("CNH");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(290, 210, 80, 20);

        txtCnh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jPanel1.add(txtCnh);
        txtCnh.setBounds(290, 230, 150, 30);

        lbltemMesa.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jPanel1.add(lbltemMesa);
        lbltemMesa.setBounds(10, 320, 340, 20);
        jPanel1.add(txtNumero);
        txtNumero.setBounds(490, 80, 60, 30);

        jLabel22.setText("Endereço");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 60, 90, 14);
        jPanel1.add(txtUf);
        txtUf.setBounds(10, 180, 60, 30);

        jLabel23.setText("Número");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(490, 60, 60, 14);

        try {
            txtTelRecado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtTelRecado);
        txtTelRecado.setBounds(590, 230, 120, 30);

        lblTelefone1.setText("Telefone");
        jPanel1.add(lblTelefone1);
        lblTelefone1.setBounds(450, 210, 90, 20);
        jPanel1.add(txtComplemento);
        txtComplemento.setBounds(10, 130, 110, 30);

        jLabel24.setText("Bairro");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(130, 110, 100, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/salvar24x24.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 290, 91, 30);

        jToggleHistorico.setText("Histórico");
        jToggleHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleHistorico);
        jToggleHistorico.setBounds(475, 290, 90, 30);

        jButton2.setText("Ranking de Vendas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 290, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 100, 720, 340);

        jPanel4.setBackground(new java.awt.Color(243, 156, 18));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        jLabel14.setText("Cadastro");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(30, 0, 185, 78);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel15.setText("de Funcionários");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(190, 50, 200, 40);
        jPanel4.add(txtId);
        txtId.setBounds(380, 10, 60, 30);
        jPanel4.add(txtCaminho);
        txtCaminho.setBounds(450, 10, 100, 30);

        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblOperador.setText("Operador");
        jPanel4.add(lblOperador);
        lblOperador.setBounds(420, 50, 114, 30);

        lblCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblCargo.setText("Operador");
        jPanel4.add(lblCargo);
        lblCargo.setBounds(510, 50, 100, 30);

        lblFechar.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        lblFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechar.setText("x");
        lblFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFechar))
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(680, 0, 40, 40);

        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/calendario24x24.png"))); // NOI18N
        lblData.setText("Data");
        jPanel4.add(lblData);
        lblData.setBounds(610, 50, 110, 30);
        jPanel4.add(txtOperacao);
        txtOperacao.setBounds(560, 10, 100, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 730, 100);

        jtableGuias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableGuiasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtableGuiasMouseEntered(evt);
            }
        });

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        jScrollPane3.setViewportView(txtHistorico);

        jtableGuias.addTab("Histórico", jScrollPane3);

        getContentPane().add(jtableGuias);
        jtableGuias.setBounds(0, 440, 720, 220);

        setSize(new java.awt.Dimension(720, 716));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        //Fecha janela de Cadastro
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("Fotos", "*.jpg,*.png");
        // Instancia selecionador de arquivos
        JFileChooser selecionaArquivo = new JFileChooser(parametro.getCAMINHO_FOTO_FUNCIONARIO());
        selecionaArquivo.addChoosableFileFilter(extensionFilter);
        selecionaArquivo.setDialogTitle("Selecionar Foto");
        selecionaArquivo.showOpenDialog(this);

        // Recebe arquivos captura seu caminho
        File file = selecionaArquivo.getSelectedFile();
        String caminho = file.getAbsolutePath();

        txtCaminho.setText(caminho);
        // adiciona imagem ao label foto
        ImageIcon imageIcon = new ImageIcon(caminho);
        Icon icon = new ImageIcon(imageIcon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH));
        lblFoto.setIcon(icon);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void comboSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSituacaoActionPerformed
        // Seleciona bloquio
        if ("Inativo".equals(comboSituacao.getSelectedItem().toString())) {
            comboBloqueio.setSelectedItem("Bloqueado");
        } else {
            comboBloqueio.setSelectedItem("Desbloqueado");
        }
    }//GEN-LAST:event_comboSituacaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Chama Tela Ranking
        TelaRanking tr = new TelaRanking();
        tr.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtableGuiasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableGuiasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableGuiasMouseEntered

    private void jtableGuiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableGuiasMouseClicked

    }//GEN-LAST:event_jtableGuiasMouseClicked

    private void jToggleHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleHistoricoActionPerformed
        // Ativa ou desativa o histórico
        if (jToggleHistorico.isSelected()) {
            jToggleHistorico.setText("Ocultar");
            jtableGuias.setVisible(true);

        } else {
            jToggleHistorico.setText("Histórico");
            jtableGuias.setVisible(false);
        }
    }//GEN-LAST:event_jToggleHistoricoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ("Adicionar".equals(txtOperacao.getText())) {
            // Adiciona um novo funcionário
            Funcionario f = new Funcionario();

            f.setFoto(txtCaminho.getText());
            f.setNome(txtNome.getText());
            f.setEndereco(txtEndereço.getText());
            f.setBairro(txtBairro.getText());
            f.setCep(txtCep.getText());
            f.setCidade(txtCidade.getText());
            f.setEmail(txtEmail.getText());
            f.setLogin(txtLogin.getText());
            f.setSenha(txtSenha.getText());
            f.setTelefone(txtTelefone.getText());
            f.setObservacao(txtHistorico.getText());
            f.setCargo(comboCargo.getSelectedItem().toString());
            f.setNumero(txtNumero.getText());
            f.setComplemento(txtComplemento.getText());
            f.setUf(txtUf.getText());
            f.setTelefone_recado(txtTelRecado.getText());

            String status = comboSituacao.getSelectedItem().toString();
            if (status.equals("Ativo")) {

                f.setStatus("0");
            } else {
                f.setStatus("1");
            }
            String bloqueio = comboBloqueio.getSelectedItem().toString();
            if (bloqueio.equals("Desbloqueado")) {

                f.setBloqueado("0");
            } else {
                f.setBloqueado("1");

            }

            f.setCpf(txtCpf.getText());
            f.setCnh(txtCnh.getText());
            f.setRg(txtRg.getText());

            if (txtNome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Funcionário inválido!");
            } else if (funcionario.temFuncionario(txtId.getText())) {
                JOptionPane.showMessageDialog(null, "Este funcionário já existe!\n Clique em 'Novo' para continuar!");
            } else {

                if (funcionario.adicionaFuncionario(f)) {
                    JOptionPane.showMessageDialog(null, "Funcionário adicionado com sucesso!");
                    limpaForm();
                    // Início do registro de log
                    l.setFuncionalidade("Salvar");
                    l.setDescricao(l.getUsuario() + " adicionou ->" + f.getNome() + " ao cadastro de funcionário");
                    l.gravaLog(l);

                    //Fim do registro de log
                }
            }
        } else {
            // Altera dados dos funcionários

            Funcionario f = new Funcionario();
            f.setId(txtId.getText());          
            f.setEndereco(txtEndereço.getText());
            f.setBairro(txtBairro.getText());
            f.setCep(txtCep.getText());
            f.setCidade(txtCidade.getText());
            f.setEmail(txtEmail.getText());
            f.setSenha(txtSenha.getText());
            f.setTelefone(txtTelefone.getText());
            f.setCargo(comboCargo.getSelectedItem().toString());
            f.setFoto(txtCaminho.getText());
            f.setObservacao(txtHistorico.getText());
            f.setCargo(comboCargo.getSelectedItem().toString());
            f.setNumero(txtNumero.getText());
            f.setComplemento(txtComplemento.getText());
            f.setUf(txtUf.getText());
            f.setTelefone_recado(txtTelRecado.getText());

            // Captura a situação
            String situacao = comboSituacao.getSelectedItem().toString();

            if (situacao.equals("Ativo")) {

                f.setStatus("0");
            } else {
                f.setStatus("1");
            }

            // Recebe o tipo de bloqueio
            String bloqueio = comboBloqueio.getSelectedItem().toString();

            if (bloqueio.equals("Bloqueado")) {

                f.setBloqueado("1");
            } else {
                f.setBloqueado("0");
            }
            //Instancia o controle do funcionário

            ControlerFuncionario cf = new ControlerFuncionario();

            // Verifica se o funcionário está bloqueado ou Inativo
            if (f.getStatus().equals("1") && f.getBloqueado().equals("1")) {
                // Verifica se o funcionário possui mesa cadastrada sob sua responsabilidade
                if (cf.temMesa(f)) {
                    // Se o funcionário possuir mesa, exibe mensagem e solicita transferida para outro 
                    JOptionPane.showMessageDialog(null, "Transfira as mesas do funcionário antes de continuar!");
                } else {
                    // Altera as mesas do funcionário
                    if (cf.alterar(f, txtId.getText())) {
                        JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                        limpaForm();
                        // Início do registro de log
                        l.setFuncionalidade("Alterar");
                        l.setDescricao(l.getUsuario() + " alterou o registro do funcioário ->" + f.getNome());
                        l.gravaLog(l);

                        //Fim do registro de log
                    }
                }
            } else {
                if (cf.alterar(f, txtId.getText())) {
                    JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");

                    // Início do registro de log
                    l.setFuncionalidade("Alterar");
                    l.setDescricao(l.getUsuario() + " alterou o registro do funcioário ->" + f.getNome());
                    l.gravaLog(l);
                    //Fim do registro de log
                }
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpaForm() {
        // Limpa formulário
        txtId.setText(null);
        txtNome.setText(null);
        txtEndereço.setText(null);
        txtBairro.setText(null);
        txtCep.setText(null);
        txtEmail.setText(null);
        txtLogin.setText(null);
        txtSenha.setText(null);
        txtTelefone.setText(null);
        txtCidade.setText(null);
        txtComplemento.setText(null);
        txtNumero.setText(null);
        txtUf.setText(null);
        comboBloqueio.setSelectedItem("Desbloqueado");
        comboCargo.setSelectedItem("Cargos");
        comboSituacao.setSelectedItem("Ativo");
        txtCaminho.setText(null);
        lblFoto.setIcon(null);
        txtRg.setText(null);
        txtCpf.setText(null);
        txtCnh.setText(null);
        txtTelRecado.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBloqueio;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JComboBox<String> comboSituacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleHistorico;
    private javax.swing.JTabbedPane jtableGuias;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lbltemMesa;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCaminho;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnh;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereço;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOperacao;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JFormattedTextField txtTelRecado;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables

   

    private void carregaFoto() {

        ImageIcon imageIcon = new ImageIcon(txtCaminho.getText());
        Icon icon = new ImageIcon(imageIcon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH));
        lblFoto.setIcon(icon);
    }

    private void bloqueiaCampos() {
        if ("Alterar".equals(txtOperacao.getText())) {
            txtNome.setEnabled(false);
            txtLogin.setEnabled(false);
            txtRg.setEnabled(false);
            txtCpf.setEnabled(false);
            txtCnh.setEnabled(false);
        }

    }
}
