/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.model.Pedido;
import br.com.bar.model.Produto;
import br.com.bar.model.ProdutoPedido;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerMesa;
import br.com.br.controler.ControlerPedido;
import br.com.br.controler.ControlerProduto;
import br.com.br.controler.ControlerEstoque;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author elias
 */
public class TelaPedido extends javax.swing.JFrame {

    ControlerMesa cm = new ControlerMesa();
    ControlerFuncionario cf = new ControlerFuncionario();
    ControlerPedido cp = new ControlerPedido();
    ControlerProduto cproduto = new ControlerProduto();
    ControlerEstoque est = new ControlerEstoque();
    Util u = new Util();

    /**
     * Creates new form TelaPedido
     */
    public TelaPedido() {
        initComponents();
        painelPedido.setVisible(false);

        txtIdMesa.setVisible(false);
        txtIdFuncionario.setVisible(false);
        txtNumeroPedido.setVisible(false);
        txtNumeroMesa.setVisible(false);

        txtTotal.setEnabled(false);
        txtCodigoProduto.setEnabled(false);
        txtQuantidade.setEnabled(false);
        
       
    }

    public void recebeOperador(String operador, String cargo) {

        lblCargo.setText(cargo);
        lblOperador.setText(operador);
        txtIdFuncionario.setText(cf.localizaIdLogin(operador));
        cm.listaMesaLivre(comboNumeroMEsa, txtIdFuncionario.getText());
        tblPedidos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos(txtIdFuncionario.getText())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        peinelsquerdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdMesa = new javax.swing.JTextField();
        txtIdFuncionario = new javax.swing.JTextField();
        painelPedido = new javax.swing.JPanel();
        btnConfirar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboNumeroMEsa = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnLogout = new javax.swing.JButton();
        txtNumeroPedido = new javax.swing.JTextField();
        txtNumeroMesa = new javax.swing.JTextField();
        painelDireito = new javax.swing.JPanel();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        tblMenu = new javax.swing.JPanel();
        txtCodigoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblNomeProduto = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        btnEstadoPedido = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalhe = new javax.swing.JTable();
        lblMensagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        peinelsquerdo.setBackground(new java.awt.Color(38, 53, 61));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/mesa128x128Claro.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pedidos");

        txtIdMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMesaActionPerformed(evt);
            }
        });

        txtIdFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFuncionarioActionPerformed(evt);
            }
        });

        painelPedido.setBackground(new java.awt.Color(38, 53, 61));

        btnConfirar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnConfirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Pedido.png"))); // NOI18N
        btnConfirar.setText("Abrir");
        btnConfirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mesa");

        comboNumeroMEsa.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        comboNumeroMEsa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNumeroMEsaItemStateChanged(evt);
            }
        });
        comboNumeroMEsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumeroMEsaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPedidoLayout = new javax.swing.GroupLayout(painelPedido);
        painelPedido.setLayout(painelPedidoLayout);
        painelPedidoLayout.setHorizontalGroup(
            painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(painelPedidoLayout.createSequentialGroup()
                        .addComponent(comboNumeroMEsa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        painelPedidoLayout.setVerticalGroup(
            painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPedidoLayout.createSequentialGroup()
                .addGroup(painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboNumeroMEsa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfirar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jCheckBox1.setBackground(new java.awt.Color(38, 53, 61));
        jCheckBox1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Abrir Pedido");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/power.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout peinelsquerdoLayout = new javax.swing.GroupLayout(peinelsquerdo);
        peinelsquerdo.setLayout(peinelsquerdoLayout);
        peinelsquerdoLayout.setHorizontalGroup(
            peinelsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peinelsquerdoLayout.createSequentialGroup()
                .addGroup(peinelsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peinelsquerdoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(peinelsquerdoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(peinelsquerdoLayout.createSequentialGroup()
                        .addGroup(peinelsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(peinelsquerdoLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel1))
                            .addGroup(peinelsquerdoLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(peinelsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1))))
                        .addGap(50, 50, 50)
                        .addGroup(peinelsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdMesa, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(txtIdFuncionario)
                            .addComponent(txtNumeroPedido)
                            .addComponent(txtNumeroMesa))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        peinelsquerdoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIdFuncionario, txtIdMesa, txtNumeroMesa, txtNumeroPedido});

        peinelsquerdoLayout.setVerticalGroup(
            peinelsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peinelsquerdoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(peinelsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(peinelsquerdoLayout.createSequentialGroup()
                        .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        peinelsquerdoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtIdFuncionario, txtIdMesa, txtNumeroMesa, txtNumeroPedido});

        getContentPane().add(peinelsquerdo);
        peinelsquerdo.setBounds(0, 0, 400, 530);

        painelDireito.setBackground(new java.awt.Color(204, 204, 204));
        painelDireito.setLayout(null);

        lblOperador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblOperador.setText("jLabel3");
        painelDireito.add(lblOperador);
        lblOperador.setBounds(20, 10, 91, 30);

        lblCargo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblCargo.setText("jLabel3");
        painelDireito.add(lblCargo);
        lblCargo.setBounds(20, 50, 91, 30);

        lblData.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/calendario24x24.png"))); // NOI18N
        lblData.setText("22/11/2017");
        painelDireito.add(lblData);
        lblData.setBounds(355, 40, 150, 32);

        txtCodigoProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        txtCodigoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Código Produto");

        txtQuantidade.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuantidadeMouseClicked(evt);
            }
        });
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel7.setText("QTD");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Total");

        txtTotal.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalMouseClicked(evt);
            }
        });
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
        });

        lblNomeProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblNomeProduto.setText("Produto");

        lblValor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        lblValor1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblValor1.setText("R$");

        btnEstadoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/listar.png"))); // NOI18N
        btnEstadoPedido.setText("Status Pedido");
        btnEstadoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstadoPedidoMouseClicked(evt);
            }
        });
        btnEstadoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tblMenuLayout = new javax.swing.GroupLayout(tblMenu);
        tblMenu.setLayout(tblMenuLayout);
        tblMenuLayout.setHorizontalGroup(
            tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tblMenuLayout.createSequentialGroup()
                        .addComponent(lblNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValor1)
                        .addGap(18, 18, 18)
                        .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(tblMenuLayout.createSequentialGroup()
                        .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tblMenuLayout.createSequentialGroup()
                                .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tblMenuLayout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tblMenuLayout.createSequentialGroup()
                                        .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGap(32, 32, 32)
                                .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tblMenuLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel9)
                                        .addGap(68, 68, 68))
                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnEstadoPedido))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tblMenuLayout.setVerticalGroup(
            tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tblMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tblMenuLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tblMenuLayout.createSequentialGroup()
                        .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(16, 16, 16)
                        .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tblMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btnEstadoPedido)
                .addGap(201, 201, 201))
        );

        painelDireito.add(tblMenu);
        tblMenu.setBounds(10, 90, 550, 210);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        tblPedidos.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N.Pedido", "Data", "Situação", "Número Mesa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPedidos.setRowHeight(22);
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);
        if (tblPedidos.getColumnModel().getColumnCount() > 0) {
            tblPedidos.getColumnModel().getColumn(0).setResizable(false);
            tblPedidos.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblPedidos.getColumnModel().getColumn(1).setResizable(false);
            tblPedidos.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblPedidos.getColumnModel().getColumn(2).setResizable(false);
            tblPedidos.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblPedidos.getColumnModel().getColumn(3).setResizable(false);
            tblPedidos.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        jTabbedPane1.addTab("Pedidos Abertos", jScrollPane1);

        tblDetalhe.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 12)); // NOI18N
        tblDetalhe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PRODUTO", "COD.", "QTD", "UNID", "TOTAL", "MESA"
            }
        ));
        tblDetalhe.setRowHeight(22);
        tblDetalhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalheMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetalhe);

        jTabbedPane1.addTab("Detalhe Pedido", jScrollPane2);

        painelDireito.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 310, 540, 200);

        lblMensagem.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 0, 0));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        painelDireito.add(lblMensagem);
        lblMensagem.setBounds(20, 300, 520, 28);

        jPanel1.setBackground(new java.awt.Color(38, 53, 61));

        btnFechar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFechar.setText("X");
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        painelDireito.add(jPanel1);
        jPanel1.setBounds(520, 0, 40, 40);

        getContentPane().add(painelDireito);
        painelDireito.setBounds(390, 0, 560, 530);

        setSize(new java.awt.Dimension(947, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboNumeroMEsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumeroMEsaActionPerformed
        //Limpa form
        limpaForm();

    }//GEN-LAST:event_comboNumeroMEsaActionPerformed

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
        // Fecha tela
        dispose();
    }//GEN-LAST:event_btnFecharMouseClicked

    private void txtIdMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMesaActionPerformed

    private void comboNumeroMEsaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNumeroMEsaItemStateChanged
        // 

    }//GEN-LAST:event_comboNumeroMEsaItemStateChanged

    private void btnConfirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirarActionPerformed
        // Inicia um pedido
        txtIdMesa.setText(cm.localizaIdMesa(comboNumeroMEsa.getSelectedItem().toString()));

        if (cp.temPedido(txtIdMesa.getText())) {
            JOptionPane.showMessageDialog(null, "Esta mesa já possui um pedido escolha outra!");

        } else {

            Pedido p = new Pedido();

            p.setCadMesaId(cm.localizaIdMesa(comboNumeroMEsa.getSelectedItem().toString()));
            String dataAtual = cp.myDataAtual();
            p.setData(dataAtual);
            p.setStatus("0"); // Pedido Aberto
            p.setIdFuncionario(cf.localizaIdLogin(lblOperador.getText()));
            p.setId_pedido(txtNumeroPedido.getText());
            
            
            
            int op = JOptionPane.showConfirmDialog(null, "Confirma a abertura do Pedido?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {

                if (cp.geraPedido(p)) {
                    JOptionPane.showMessageDialog(null, "Pedido Gerado!");
                    tblPedidos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos(txtIdFuncionario.getText())));
                    cm.trocaStatusMesa(comboNumeroMEsa.getSelectedItem().toString(), "1");
                    cm.listaMesaLivre(comboNumeroMEsa, txtIdFuncionario.getText());

                }

            } else {
                JOptionPane.showMessageDialog(null, "Abertura cancelada!");

            }
        }


    }//GEN-LAST:event_btnConfirarActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        int linha= tblPedidos.getSelectedRow();
        // Captura número da mesa
        String numeroMesa = tblPedidos.getModel().getValueAt(linha, 0).toString();
        txtNumeroMesa.setText(numeroMesa);
        // Exibe detalhe da mesa
        tblDetalhe.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(numeroMesa, txtNumeroPedido.getText())));

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoKeyPressed
        // Vai para a caixa quantidade 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //txtIdMesa.setText(cm.localizaIdMesa(comboNumeroMEsa.getSelectedItem().toString()));
            if (txtIdMesa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um pedido!");
            } else {

                Produto produto = new Produto();
                produto.setId(txtCodigoProduto.getText());

                try {

                    Produto pLocalizado = cproduto.localizaProduto(produto);
                    lblNomeProduto.setText(pLocalizado.getNome());
                    lblValor.setText(String.format("%7.2f", Double.parseDouble(pLocalizado.getValor())));

                    txtQuantidade.requestFocus();
                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "Produto não localizado");
                }
            }

        }
    }//GEN-LAST:event_txtCodigoProdutoKeyPressed

    private void txtQuantidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuantidadeMouseClicked
        // Seleciona a aba detalhe pedido


    }//GEN-LAST:event_txtQuantidadeMouseClicked

    private void txtIdFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFuncionarioActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        // Chama método que lista o detalhe do pedido pelo numero da mesa
        // Habilita caixas de texto
        txtCodigoProduto.setEnabled(true);
        txtQuantidade.setEnabled(true);
        // Captura linha selecionada
        int linha = tblPedidos.getSelectedRow();
        // Captura número da mesa
        String numeroMesa = tblPedidos.getModel().getValueAt(linha, 0).toString();
        txtNumeroMesa.setText(numeroMesa);

        //Localiza ID da mesa
        txtIdMesa.setText(cm.localizaIdMesa(tblPedidos.getModel().getValueAt(linha, 0).toString()));
        // Captura o número do pedido
        txtNumeroPedido.setText(tblPedidos.getModel().getValueAt(linha, 3).toString());
        // Exibe detalhe da mesa
        tblDetalhe.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(numeroMesa, txtNumeroPedido.getText())));
    }//GEN-LAST:event_tblPedidosMouseClicked

    private void txtTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMouseClicked

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Realiza logout
        dispose();
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        // Calcula o total do produto 
        ProdutoPedido pp = new ProdutoPedido();

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (txtQuantidade.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Informe a quantidade para continuar");
            } else {

                calculaTotal();
                int op = JOptionPane.showConfirmDialog(null, "Confirma a inclusão do produto?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
                // Instancia objeto ProdutoPedido
                if (op == JOptionPane.YES_OPTION) {
                    pp.setTbproduto_id(txtCodigoProduto.getText());
                    pp.setQtd(txtQuantidade.getText());
                    pp.setValorUnit(lblValor.getText().replaceAll(",", "."));
                    pp.setTotal(txtTotal.getText().replaceAll(",", "."));
                    pp.setData(cp.myDataAtual());
                    pp.setCadmesa_id(txtIdMesa.getText());
                    pp.setCadpedido_id_pedido(txtNumeroPedido.getText());
                    pp.setTbcadfuncionario_id(txtIdFuncionario.getText());

                    ControlerEstoque ec = new ControlerEstoque();
                    int qtdEstoque = ec.temNoEstoque(pp.getTbproduto_id());
                    
                    if (Integer.parseInt(pp.getQtd())<= qtdEstoque) {
                        // Adiciona o produto ao pedido     
                        cproduto.adicionaProdutoAoPedido(pp);
                        // Retira o produto do estoque
                        ec.retiraEstoque(pp, pp.getQtd());
                        // Registra movimentação 
                        if (est.registraMovimentacao(pp.getTbproduto_id(), pp.getQtd(), est.localizaIdOperacao("Venda"), null)){
                            System.out.println("Movimentação registrada!");
                        }
                       // Limpa label de mensagem de produto indisponível 
                        lblMensagem.setText(null);
                        
                    } else {
                        // Exibe mensagem de produto indisponpivel no momento
                        lblMensagem.setText(lblNomeProduto.getText() + " indisponível! Quantidade em estoque: " + qtdEstoque);
                    }

                    limpaForm();
                    tblDetalhe.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(comboNumeroMEsa.getSelectedItem().toString(), txtNumeroPedido.getText())));
                }
            }
        }
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed
        // Adiciona o produto ao pressionar enter

    }//GEN-LAST:event_txtTotalKeyPressed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // Exibe painel de abertura de pedido
        painelPedido.setVisible(true);
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void tblDetalheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalheMouseClicked
        // Envia porduto para a cozinha
        int linha = tblDetalhe.getSelectedRow();

        ArrayList<String> pCozinha = new ArrayList<>();

        //codProduto, produto, qtd, funcionario, mesa, data, status
        pCozinha.add(tblDetalhe.getModel().getValueAt(linha, 1).toString()); // Código Produto
        pCozinha.add(tblDetalhe.getModel().getValueAt(linha, 0).toString()); // Produto
        pCozinha.add(tblDetalhe.getModel().getValueAt(linha, 2).toString()); // Qtd         
        pCozinha.add(lblOperador.getText()); // Nome do Funcionario
        pCozinha.add(txtNumeroMesa.getText()); // Numero da mesa
        pCozinha.add(cp.myDataAtual()); // Data Atual 
        pCozinha.add("Pendente"); // Status Pendente - Liberado

        if (evt.getButton() == 3) {

            int op = JOptionPane.showConfirmDialog(null, "Enviar o prato \n" + pCozinha.get(1) + "Para a cozinha?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if (op == JOptionPane.YES_OPTION) {

                cp.enviaProdutoCozinha(pCozinha);

            }
        }

    }//GEN-LAST:event_tblDetalheMouseClicked

    private void btnEstadoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoPedidoActionPerformed
        // Chama a tela Status do pedido
        TelaStatusCozinha status = new TelaStatusCozinha();
        //status.recebeOperador(lblOperador.getText());
        status.setVisible(true);
    }//GEN-LAST:event_btnEstadoPedidoActionPerformed

    private void btnEstadoPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstadoPedidoMouseClicked
    public void calculaTotal() {
        int qtd = Integer.parseInt(txtQuantidade.getText());
        double valor = Double.parseDouble(lblValor.getText().replace(",", "."));
        double total = qtd * valor;
        txtTotal.setText(String.format("%7.2f", total));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirar;
    private javax.swing.JButton btnEstadoPedido;
    private javax.swing.JLabel btnFechar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JComboBox<String> comboNumeroMEsa;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JPanel painelDireito;
    private javax.swing.JPanel painelPedido;
    private javax.swing.JPanel peinelsquerdo;
    private javax.swing.JTable tblDetalhe;
    private javax.swing.JPanel tblMenu;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtIdFuncionario;
    private javax.swing.JTextField txtIdMesa;
    private javax.swing.JTextField txtNumeroMesa;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void limpaForm() {
        txtCodigoProduto.setText(null);
        txtQuantidade.setText(null);
        txtCodigoProduto.requestFocus();
        txtTotal.setText(null);
        lblNomeProduto.setText(null);
        lblValor.setText(null);
    }
}
