/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.model.Grupo;
import br.com.bar.model.Pedido;
import br.com.bar.model.Produto;
import br.com.bar.model.ProdutoPedido;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerEstoque;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerGrupo;
import br.com.br.controler.ControlerMesa;
import br.com.br.controler.ControlerPedido;
import br.com.br.controler.ControlerProduto;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author elias
 */
public class TelaPedido2 extends javax.swing.JFrame {

    ControlerFuncionario cFunc = new ControlerFuncionario();
    ControlerMesa cm = new ControlerMesa();
    ControlerPedido cp = new ControlerPedido();
    ControlerProduto cproduto = new ControlerProduto();
    ControlerEstoque est = new ControlerEstoque();
    ControlerGrupo cg = new ControlerGrupo();

    Util u = new Util();

    /**
     * Creates new form TelaPedido2
     */
    public TelaPedido2() {

        initComponents();
        lbllogo.setIcon(u.carregaLogo());
        cFunc.carregaComboFuncionario(comboGarcom, "Garçom");
        tblPedidosAbertos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos()));
        Calendar c = Calendar.getInstance();
        lblData.setText(u.formataDataBr(c.getTime()));
        bloqueiaCampos();
        // Oculta caixa de pesquisa
        lblPesquisa.setVisible(false);
        txtPesquisa.setVisible(false);
        txtIdGarcom.setVisible(false);
        txtIdMesa.setVisible(false);
        txtNumeroPedido.setVisible(false);
        txtNumeroMesa.setVisible(false);
        
       

    }

    public void recebeOperador(String operador, String perfil){
        lblOperador.setText(operador);
        lblCargo.setText(perfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtIdGarcom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNumeroMesa = new javax.swing.JTable();
        btnAbrirPedido = new javax.swing.JButton();
        txtIdMesa = new javax.swing.JTextField();
        jTabbedPanePedido = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidosAbertos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetalhePedido = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblListaProduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblQtd = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbltotal = new javax.swing.JLabel();
        txtNumeroPedido = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        lblData1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        comboGarcom = new javax.swing.JComboBox<>();
        btnListar = new javax.swing.JButton();
        txtNumeroMesa = new javax.swing.JTextField();
        panelFechar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        txtIdGarcom.setText("idGarcom");
        getContentPane().add(txtIdGarcom);
        txtIdGarcom.setBounds(1010, 60, 50, 30);

        tblNumeroMesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNumeroMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Mesas Disponíveis"
            }
        ));
        tblNumeroMesa.setRowHeight(25);
        tblNumeroMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNumeroMesaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNumeroMesa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 290, 230, 220);

        btnAbrirPedido.setBackground(new java.awt.Color(204, 204, 204));
        btnAbrirPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Pedido.png"))); // NOI18N
        btnAbrirPedido.setText("Abrir Pedido");
        btnAbrirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirPedido);
        btnAbrirPedido.setBounds(200, 530, 230, 50);

        txtIdMesa.setText("idMesa");
        getContentPane().add(txtIdMesa);
        txtIdMesa.setBounds(1010, 140, 50, 30);

        jTabbedPanePedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPanePedidoMouseClicked(evt);
            }
        });

        tblPedidosAbertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MESA", "SITUAÇÃO", "PEDIDO", "GARÇOM"
            }
        ));
        tblPedidosAbertos.setRowHeight(25);
        tblPedidosAbertos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosAbertosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPedidosAbertos);

        jTabbedPanePedido.addTab("Pedidos Abertos", jScrollPane2);

        tblDetalhePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDetalhePedido.setRowHeight(25);
        tblDetalhePedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalhePedidoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDetalhePedido);

        jTabbedPanePedido.addTab("Detalhe Pedido", jScrollPane3);

        tblListaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListaProduto.setRowHeight(25);
        tblListaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaProdutoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblListaProduto);

        jTabbedPanePedido.addTab("Lista de Produtos", jScrollPane6);

        getContentPane().add(jTabbedPanePedido);
        jTabbedPanePedido.setBounds(450, 290, 580, 190);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Produto")));

        lblCodigo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lblCodigo.setText("Código");

        lblQtd.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lblQtd.setText("Qtd");

        txtQtd.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtQtd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtQtdMouseEntered(evt);
            }
        });
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
        });

        txtCodigoProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtCodigoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoProdutoMouseClicked(evt);
            }
        });
        txtCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtd)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtd)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(440, 60, 290, 161);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Produto")));

        lblProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        lblValor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(740, 60, 250, 70);

        lblPesquisa.setText("Pesquisar Produto");
        getContentPane().add(lblPesquisa);
        lblPesquisa.setBounds(450, 230, 120, 14);

        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(txtPesquisa);
        txtPesquisa.setBounds(450, 250, 220, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Total")));

        lbltotal.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotal.setText("0,00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbltotal)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(740, 140, 250, 80);

        txtNumeroPedido.setText("nPedido");
        getContentPane().add(txtNumeroPedido);
        txtNumeroPedido.setBounds(1010, 100, 50, 30);

        jPanel4.setBackground(new java.awt.Color(38, 53, 61));
        jPanel4.setForeground(new java.awt.Color(52, 73, 94));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/logo.png"))); // NOI18N

        lblData1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblData1.setForeground(new java.awt.Color(255, 255, 255));
        lblData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData1.setText("SysBar");

        lblData.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/calendar24x24.png"))); // NOI18N
        lblData.setText("data");

        lblOperador.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lblOperador.setForeground(new java.awt.Color(255, 255, 255));
        lblOperador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario_branco.png"))); // NOI18N
        lblOperador.setText("usuário");

        lblCargo.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(255, 255, 255));
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil (2).png"))); // NOI18N
        lblCargo.setText("usuário");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblData1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData1)
                .addGap(18, 18, 18)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOperador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCargo)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 190, 600);

        lblData2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData2.setText("SysBar - Lançamento de Pedido");
        getContentPane().add(lblData2);
        lblData2.setBounds(200, 10, 740, 48);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Garçom")));

        comboGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGarcomActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(204, 204, 204));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/mesa32x32.png"))); // NOI18N
        btnListar.setText("Listar Mesas");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(200, 60, 230, 160);

        txtNumeroMesa.setText("nMesa");
        getContentPane().add(txtNumeroMesa);
        txtNumeroMesa.setBounds(1010, 180, 50, 30);

        panelFechar.setBackground(new java.awt.Color(52, 73, 94));
        panelFechar.setForeground(new java.awt.Color(52, 73, 94));
        panelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFecharMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");

        javax.swing.GroupLayout panelFecharLayout = new javax.swing.GroupLayout(panelFechar);
        panelFechar.setLayout(panelFecharLayout);
        panelFecharLayout.setHorizontalGroup(
            panelFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelFecharLayout.setVerticalGroup(
            panelFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(panelFechar);
        panelFechar.setBounds(1030, 0, 40, 40);

        lblMensagem.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(153, 153, 153));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("* sem mensagem");
        getContentPane().add(lblMensagem);
        lblMensagem.setBounds(450, 480, 580, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btnCozinha.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(790, 510, 70, 48);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btnEnviar.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 520, 90, 40);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gerenciar Pedido");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 560, 150, 23);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Status Cozinha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 560, 90, 20);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/relatorios48x48.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 510, 80, 50);

        jLabel8.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel8.setText("Enviar Prato (cozinha)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(620, 560, 150, 23);

        setSize(new java.awt.Dimension(1068, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGarcomActionPerformed


    }//GEN-LAST:event_comboGarcomActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // Lista todas as mesas livres do funcionário selecionado
        String nomeFunc = comboGarcom.getSelectedItem().toString();
        String idFunc = cFunc.localizaId(nomeFunc);
        tblNumeroMesa.setModel(DbUtils.resultSetToTableModel(cm.listaMesaLivre(idFunc)));
        tblPedidosAbertos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos()));
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAbrirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPedidoActionPerformed
        // Abre pedido
        if (cp.temPedido(txtIdMesa.getText())) {
            JOptionPane.showMessageDialog(null, "Esta mesa já possui um pedido escolha outra!");
        } else {
            Pedido p = new Pedido();
            p.setCadMesaId(txtIdMesa.getText());
            String dataAtual = cp.myDataAtual();
            p.setData(dataAtual);
            p.setStatus("0"); // Pedido Aberto
            p.setIdFuncionario(txtIdGarcom.getText());
            //p.setId_pedido(txtNumeroPedido.getText());

            int op = JOptionPane.showConfirmDialog(null, "Confirma a abertura do Pedido?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if (op == JOptionPane.YES_OPTION) {

                if (cp.geraPedido(p)) {
                    int linha = tblNumeroMesa.getSelectedRow();
                    String numero_mesa = tblNumeroMesa.getModel().getValueAt(linha, 0).toString();
                    JOptionPane.showMessageDialog(null, "Pedido Gerado!");

                    tblPedidosAbertos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos()));
                    cm.trocaStatusMesa(numero_mesa, "1");
                    tblNumeroMesa.setModel(DbUtils.resultSetToTableModel(cm.listaMesaLivre(txtIdGarcom.getText())));

                }

            } else {
                JOptionPane.showMessageDialog(null, "Abertura cancelada!");

            }
        }
    }//GEN-LAST:event_btnAbrirPedidoActionPerformed

    private void tblNumeroMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNumeroMesaMouseClicked
        // Seleciona uma mesa na tabela
        int linha = tblNumeroMesa.getSelectedRow();
        txtIdMesa.setText(cm.localizaIdMesa(tblNumeroMesa.getModel().getValueAt(linha, 0).toString()));
        txtIdGarcom.setText(cFunc.localizaId(comboGarcom.getSelectedItem().toString()));
    }//GEN-LAST:event_tblNumeroMesaMouseClicked

    private void tblPedidosAbertosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosAbertosMouseClicked
        // Selciona um pedido
        int linha = tblPedidosAbertos.getSelectedRow();
        String numeroMesa = tblPedidosAbertos.getModel().getValueAt(linha, 0).toString();
        txtNumeroMesa.setText(numeroMesa);
        String numPedido = tblPedidosAbertos.getModel().getValueAt(linha, 3).toString();
        tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(numeroMesa, numPedido)));
        txtNumeroPedido.setText(numPedido);
        txtIdGarcom.setText(cFunc.localizaId(tblPedidosAbertos.getModel().getValueAt(linha, 4).toString()));
        txtIdMesa.setText(cm.localizaIdMesa(numeroMesa));
        txtCodigoProduto.setEnabled(true);
        txtQtd.setEnabled(true);
        txtCodigoProduto.requestFocus();
        comboGarcom.setSelectedItem(tblPedidosAbertos.getModel().getValueAt(linha, 4).toString());
    }//GEN-LAST:event_tblPedidosAbertosMouseClicked

    private void jTabbedPanePedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPanePedidoMouseClicked
        // Exibe caixa de pesquisa e lista todos os produtos disponível no estoque

        tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.listaProdutoDisponivel()));
         int index =jTabbedPanePedido.getSelectedIndex();
         if ("Lista de Produtos".equals(jTabbedPanePedido.getTitleAt(index))){
             lblPesquisa.setVisible(true);
             txtPesquisa.setVisible(true);
         }else {
             lblPesquisa.setVisible(false);
             txtPesquisa.setVisible(false);
         }
    }//GEN-LAST:event_jTabbedPanePedidoMouseClicked

    private void txtCodigoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProdutoMouseClicked

    }//GEN-LAST:event_txtCodigoProdutoMouseClicked

    private void txtCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoKeyPressed
        // Vai para a caixa quantidade 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //txtIdMesa.setText(cm.localizaIdMesa(comboNumeroMEsa.getSelectedItem().toString()));
            if (txtIdMesa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um pedido!");
            } else {

                Produto produto = new Produto();
                produto.setId(txtCodigoProduto.getText());

                try {

                    Produto pLocalizado = cproduto.localizaProduto(produto);
                    lblProduto.setText(pLocalizado.getNome());
                    lblValor.setText(String.format("%7.2f", Double.parseDouble(pLocalizado.getValor())));

                    txtQtd.requestFocus();
                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "Produto não localizado");
                }
            }

        }
    }//GEN-LAST:event_txtCodigoProdutoKeyPressed

    private void txtQtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdMouseClicked
    // Calcula o total da venda 
    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed
        // Verifica se a tecla pressionada é a tecla enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                // Caso a quantidade não seja informada pede ao usuário que digite novamente!
                if (txtQtd.getText().isEmpty()) {
                    lblMensagem.setText("Quantidade inválida!");
                    lblMensagem.setForeground(Color.red);
                    txtQtd.requestFocus();

                } else {

                    lbltotal.setText(String.format("%7.2f", calculaPedido()));
                    lblMensagem.setText(null);

                    // Verifica se o pedido foi selecionado
                    if (txtNumeroPedido.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Por favor selecione um pedido!");
                    } else {
                        // Confirma pedido
                        int op = JOptionPane.showConfirmDialog(null, "Confirma a inclusão do produto? \n " + lblProduto.getText(), "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                        if (op == JOptionPane.YES_OPTION) {
                            // Instancia um objeto Produto Pedido
                            ProdutoPedido pp = new ProdutoPedido();
                            // Seta dados no objeto
                            pp.setTbproduto_id(txtCodigoProduto.getText());
                            pp.setQtd(txtQtd.getText());
                            pp.setValorUnit(lblValor.getText().replaceAll(",", "."));
                            pp.setTotal(lbltotal.getText().replaceAll(",", "."));
                            pp.setData(cp.myDataAtual());
                            pp.setCadmesa_id(txtIdMesa.getText());
                            pp.setCadpedido_id_pedido(txtNumeroPedido.getText());
                            pp.setTbcadfuncionario_id(txtIdGarcom.getText());

                            ControlerEstoque ec = new ControlerEstoque();
                            int qtdEstoque=ec.temNoEstoque(pp.getTbproduto_id());
                            
                            System.out.println("Qtd: " + qtdEstoque);
                            
                            if (Integer.parseInt(pp.getQtd())<= qtdEstoque) {
                                // Adiciona o produto ao pedido                 
                                cproduto.adicionaProdutoAoPedido(pp);    

                                // Retira o produto do estoque                 
                                ec.retiraEstoque(pp, pp.getQtd());

                                // Registra movimentação 
                                if (est.registraMovimentacao(pp.getTbproduto_id(), pp.getQtd(), est.localizaIdOperacao("Venda"), null)) {
                                    System.out.println("Movimentação registrada!");
                                }
                                // Limpa label de mensagem de produto indisponível 
                                lblMensagem.setText(null);
                                limpaform();
                                bloqueiaCampos();

                            } else {
                                // Exibe mensagem de produto indisponpivel no momento
                                lblMensagem.setForeground(Color.red);
                                lblMensagem.setText(lblProduto.getText() + " com quantidade insuficiente \n " + "existem em estoque apenas " + qtdEstoque + " unidades");
                                txtCodigoProduto.requestFocus();
                                txtCodigoProduto.setText(null);
                                txtQtd.setText(null);
                            }
                            //Atualiza a tabela de detalhe do pedido    
                            tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(txtIdMesa.getText(), txtNumeroPedido.getText())));
                            // Atualiza os produtos disponível no Estoque
                            tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.listaProdutoDisponivel()));
                        }

                    }
                }
            } catch (Exception e) {
                lblMensagem.setText("Quantidade inválida tente novamente!");
                lblMensagem.setOpaque(false);
                lblMensagem.setForeground(Color.red);
                txtQtd.requestFocus();
            }

        }
    }//GEN-LAST:event_txtQtdKeyPressed

    private void tblListaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaProdutoMouseClicked
        // Carega dados do produto
        int linha = tblListaProduto.getSelectedRow();
        txtCodigoProduto.setText(tblListaProduto.getModel().getValueAt(linha, 0).toString());
        lblProduto.setText(tblListaProduto.getModel().getValueAt(linha, 1).toString());
        lblValor.setText(tblListaProduto.getModel().getValueAt(linha, 3).toString());
        txtQtd.requestFocus();


    }//GEN-LAST:event_tblListaProdutoMouseClicked

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // Lista o produto localizado pelas inicias do nome
        tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.pesquisarProduto(txtPesquisa.getText())));
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        // Vai para a tabela de listagem de produto
        jTabbedPanePedido.setSelectedIndex(2);
        tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.listaProdutoDisponivel()));
    }//GEN-LAST:event_txtPesquisaFocusGained

    private void tblDetalhePedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalhePedidoMouseClicked
        // Envia porduto para a cozinha
        int linha = tblDetalhePedido.getSelectedRow();

        ArrayList<String> pCozinha = new ArrayList<>();

        //codProduto, produto, qtd, funcionario, mesa, data, status
        pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 1).toString()); // Código Produto
        pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 0).toString()); // Produto
        pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 2).toString()); // Qtd         
        pCozinha.add(comboGarcom.getSelectedItem().toString()); // Nome do Funcionario
        pCozinha.add(txtNumeroMesa.getText()); // Numero da mesa
        pCozinha.add(cp.myDataAtual()); // Data Atual 
        pCozinha.add("Pendente"); // Status Pendente - Liberado
        pCozinha.add(txtNumeroPedido.getText());

        if (evt.getButton() == 3) {

            int op = JOptionPane.showConfirmDialog(null, "Enviar o prato \n" + pCozinha.get(1) + "Para a cozinha?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if (op == JOptionPane.YES_OPTION) {

                cp.enviaProdutoCozinha(pCozinha);

            }
        }
    }//GEN-LAST:event_tblDetalhePedidoMouseClicked

    private void panelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFecharMouseClicked
        // Fecha a janela atual
        this.dispose();
    }//GEN-LAST:event_panelFecharMouseClicked

    private void txtQtdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdMouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // Chama Tela Cozinha
        TelaStatusCozinha status = new TelaStatusCozinha();
        status.recebeOperador(comboGarcom.getSelectedItem().toString());
        status.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // Envia prato para cozinha
        // Envia porduto para a cozinha
        int linha = tblDetalhePedido.getSelectedRow();

        ArrayList<String> pCozinha = new ArrayList<>();

        //codProduto, produto, qtd, funcionario, mesa, data, status
        pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 1).toString()); // Código Produto
        pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 0).toString()); // Produto
        pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 2).toString()); // Qtd         
        pCozinha.add(comboGarcom.getSelectedItem().toString()); // Nome do Funcionario
        pCozinha.add(txtNumeroMesa.getText()); // Numero da mesa
        pCozinha.add(cp.myDataAtual()); // Data Atual 
        pCozinha.add("Pendente"); // Status Pendente - Liberado
        pCozinha.add(txtNumeroPedido.getText());

            int op = JOptionPane.showConfirmDialog(null, "Enviar o prato \n " + pCozinha.get(1) + " para a cozinha? ", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if (op == JOptionPane.YES_OPTION) {

                cp.enviaProdutoCozinha(pCozinha);

            }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        TelaGerenciarPedido gp = new TelaGerenciarPedido();
        gp.recebeOperador(lblOperador.getText(), lblCargo.getText());
        gp.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private double calculaPedido() {
        double valor = Double.parseDouble(lblValor.getText().replaceAll(",", "."));
        int qtd = Integer.parseInt(txtQtd.getText());
        double total = valor * qtd;

        return total;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedido2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPedido;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> comboGarcom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPanePedido;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData2;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JPanel panelFechar;
    private javax.swing.JTable tblDetalhePedido;
    private javax.swing.JTable tblListaProduto;
    private javax.swing.JTable tblNumeroMesa;
    private javax.swing.JTable tblPedidosAbertos;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtIdGarcom;
    private javax.swing.JTextField txtIdMesa;
    private javax.swing.JTextField txtNumeroMesa;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables

    private void limpaform() {
        txtCodigoProduto.setText(null);
        lblProduto.setText(null);
        lblValor.setText(null);
        txtQtd.setText(null);
        lbltotal.setText(null);

    }

    private void bloqueiaCampos() {
        txtCodigoProduto.setEnabled(false);
        txtQtd.setEnabled(false);
    }
}
