/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.Log;
import br.com.bar.model.TableModelGrupoProduto;
import br.com.bar.model.TableModelReajuste;
import br.com.bar.util.FormataValor;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerGrupo;
import br.com.br.controler.ControlerProduto;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author elias
 */
public class TelaReajuste extends javax.swing.JFrame {

    /**
     * Creates new form TelaReajuste
     */
    ControlerProduto cp = new ControlerProduto();
    ControlerGrupo cg = new ControlerGrupo();
    Util u = new Util();
    TableModelReajuste model = new TableModelReajuste();
    TableModelGrupoProduto modelGrupo = new TableModelGrupoProduto();

    public TelaReajuste() {
        initComponents();
        txtId.setVisible(false);
        txtValor.setVisible(false);
        //desabilitaFator();
        desabilitaValorDireto();
        lblPesquisarProduto.setVisible(false);
        txtNomeProduto.setVisible(false);
        btnAplicar.setEnabled(false);
        radioPorValorUnit.setSelected(true);
        tblProdutos.setModel(DbUtils.resultSetToTableModel(cp.listaProdutoParaReajuste()));
        model.redimensionaColunas(tblProdutos);
        lblPesquisarProduto.setVisible(true);
        txtNomeProduto.setVisible(true);
        habilitaFator();
        radioFator.setSelected(true);

    }

    private void desabilitaFator() {

        txtPercentual.setEnabled(false);
        lblPercentual.setEnabled(false);
    }

    private void habilitaFator() {

        txtPercentual.setEnabled(true);
        lblPercentual.setEnabled(true);

    }

    private void desabilitaValorDireto() {
        lblCifra.setEnabled(false);
        txtValorDireto.setEnabled(false);

    }

    private void habilitaValorDireto() {
        lblCifra.setEnabled(true);
        txtValorDireto.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        bordas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelFormaReajuste = new javax.swing.JPanel();
        txtPercentual = new javax.swing.JTextField();
        lblCifra = new javax.swing.JLabel();
        radioFator = new javax.swing.JRadioButton();
        radioValorDireto = new javax.swing.JRadioButton();
        txtValorDireto = new javax.swing.JTextField();
        lblPercentual = new javax.swing.JLabel();
        btnAplicar = new javax.swing.JButton();
        panelProdutos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        lblPesquisarProduto = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        radioPorGrupo = new javax.swing.JRadioButton();
        radioPorValorUnit = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        bordas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        bordas.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(243, 156, 18));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 73, 94));
        jLabel1.setText("de Preços");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 60, 130, 40);
        jPanel1.add(txtId);
        txtId.setBounds(12, 100, 37, 20);
        jPanel1.add(txtValor);
        txtValor.setBounds(55, 100, 50, 20);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 73, 94));
        jLabel7.setText("Reajuste ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 10, 270, 50);

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));

        jLabel4.setBackground(new java.awt.Color(52, 73, 94));
        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fecharWhite24x24.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(741, 0, 40, 40);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/money-64.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 10, 80, 60);

        bordas.add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 120);

        panelFormaReajuste.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Forma de Reajuste"));

        txtPercentual.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtPercentual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPercentual.setText("0,0");
        txtPercentual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPercentualFocusGained(evt);
            }
        });
        txtPercentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPercentualActionPerformed(evt);
            }
        });
        txtPercentual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPercentualKeyReleased(evt);
            }
        });

        lblCifra.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblCifra.setText("R$");

        buttonGroup2.add(radioFator);
        radioFator.setText("Por Fator");
        radioFator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFatorActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioValorDireto);
        radioValorDireto.setText("Por Valor");
        radioValorDireto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioValorDiretoActionPerformed(evt);
            }
        });

        txtValorDireto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtValorDireto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorDireto.setText("0,00");
        txtValorDireto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorDiretoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorDiretoFocusLost(evt);
            }
        });
        txtValorDireto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorDiretoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorDiretoKeyReleased(evt);
            }
        });

        lblPercentual.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblPercentual.setText("%");

        btnAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/aplicar.png"))); // NOI18N
        btnAplicar.setText("Aplicar Reajuste");
        btnAplicar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnAplicarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormaReajusteLayout = new javax.swing.GroupLayout(panelFormaReajuste);
        panelFormaReajuste.setLayout(panelFormaReajusteLayout);
        panelFormaReajusteLayout.setHorizontalGroup(
            panelFormaReajusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormaReajusteLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelFormaReajusteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormaReajusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormaReajusteLayout.createSequentialGroup()
                        .addComponent(txtPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(lblCifra))
                    .addComponent(radioFator, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormaReajusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValorDireto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioValorDireto))
                .addGap(36, 36, 36))
        );
        panelFormaReajusteLayout.setVerticalGroup(
            panelFormaReajusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormaReajusteLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelFormaReajusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFator)
                    .addComponent(radioValorDireto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormaReajusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorDireto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCifra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        bordas.add(panelFormaReajuste);
        panelFormaReajuste.setBounds(10, 210, 330, 320);

        panelProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        tblProdutos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){

                return false;
            }

        };
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "VALOR R$"
            }
        ));
        tblProdutos.setRowHeight(20);
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        lblPesquisarProduto.setText("Pesquisar ");

        txtNomeProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtNomeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeProdutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeProdutoKeyReleased(evt);
            }
        });

        lblTitulo.setText("Produtos");

        javax.swing.GroupLayout panelProdutosLayout = new javax.swing.GroupLayout(panelProdutos);
        panelProdutos.setLayout(panelProdutosLayout);
        panelProdutosLayout.setHorizontalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelProdutosLayout.createSequentialGroup()
                        .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 146, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelProdutosLayout.setVerticalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProdutosLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblPesquisarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bordas.add(panelProdutos);
        panelProdutos.setBounds(360, 146, 410, 382);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo de Reajuste"));

        buttonGroup1.add(radioPorGrupo);
        radioPorGrupo.setText("Por Grupo");
        radioPorGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioPorGrupoMouseClicked(evt);
            }
        });
        radioPorGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPorGrupoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioPorValorUnit);
        radioPorValorUnit.setText("Por Valor Unitário");
        radioPorValorUnit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioPorValorUnitMouseClicked(evt);
            }
        });
        radioPorValorUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPorValorUnitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(radioPorGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(radioPorValorUnit)
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioPorGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(radioPorValorUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bordas.add(jPanel5);
        jPanel5.setBounds(10, 130, 330, 70);

        getContentPane().add(bordas);
        bordas.setBounds(0, 0, 781, 540);

        setSize(new java.awt.Dimension(781, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Confirma o reajuste?", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (resp == JOptionPane.YES_OPTION) {
            // Informa ao usuário para selecionar um forma de reajuste
            if (radioPorValorUnit.isSelected() || radioPorGrupo.isSelected()) {

                if (radioPorGrupo.isSelected() & radioFator.isSelected()) {
                    // Reajusta grupo pelo percentual
                    Double percentual = Double.parseDouble(txtPercentual.getText().replaceAll(",", "."));
                    // Reajusta caso o percentual seja maior que zero
                    if (percentual > 0) {
                        if (txtId.getText().isEmpty()) { // VErifica se o produto foi seleciondo
                            JOptionPane.showMessageDialog(this, "Selecione um grupo!");
                        } else {
                            // Reajusta o grupo de produto
                            cp.reajusteGrupoProduto(txtId.getText(), txtPercentual.getText());
                            tblProdutos.setModel(DbUtils.resultSetToTableModel(cp.listaProdutoParaReajuste()));
                            model.redimensionaColunas(tblProdutos);
                            txtPercentual.setText("0,0");
                            txtId.setText(null);
                            // Log
                            Log l = new Log();
                            l.setDescricao("Reajustou o Grupo de produtos->" + txtId.getText());
                            l.gravaLog(l);

                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Percentual inválido");
                    }
                    // Aplica reajuste unitário por fator de reajuste
                } else if (radioPorValorUnit.isSelected() && radioFator.isSelected()) {
                    Double percentual = Double.parseDouble(txtPercentual.getText().replaceAll(",", "."));
                    if (percentual > 0) { // Se o percentual for maior que zero continua
                        if (txtId.getText().isEmpty()) { // Solicita que o usuario selecione um produto
                            JOptionPane.showMessageDialog(this, "Selecione um produto para continuar!");
                        } else {
                            // Aplica reajuste e exibe mensagem caso o produto seja atualizado
                            if (cp.reajustaValorProduto(txtId.getText(), Double.parseDouble(txtValor.getText().replaceAll(",", ".")), Double.parseDouble(txtPercentual.getText().replaceAll(",", ".")))) {
                                JOptionPane.showMessageDialog(this, "Produto reajustado com sucesso!");
                                // Log
                                Log l = new Log();
                                l.setDescricao("Reajustou o valor do produto ->" + txtId.getText());
                                l.gravaLog(l);
                            }
                            tblProdutos.setModel(DbUtils.resultSetToTableModel(cp.listaProdutoParaReajuste()));
                            model.redimensionaColunas(tblProdutos);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Percentual inválido!");
                    }
                    // Reajusta valor diretamente a partir do valor informado pelo usuário
                } else if (radioPorValorUnit.isSelected() && radioValorDireto.isSelected()) {

                    double vDireto = Double.parseDouble(txtValorDireto.getText().replace(",", "."));
                    if (vDireto > 0) { // Informa que o produto não foi selecionado
                        if (txtId.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Selecione um produto para continuar!");
                        } else {
                            // Aplica reajuste a partir do valor informado
                            cp.reajustaValorProduto(txtId.getText(), vDireto);
                            // Log
                            Log l = new Log();
                            l.setDescricao("Reajustou o valor do produto->" + txtId.getText() + " " + txtValorDireto.getText());
                            l.gravaLog(l);
                            tblProdutos.setModel(DbUtils.resultSetToTableModel(cp.listaProdutoParaReajuste()));
                            model.redimensionaColunas(tblProdutos);
                            JOptionPane.showMessageDialog(this, "Produto reajustado com sucesso!");
                            txtId.setText(null);
                            txtValorDireto.setText("0,00");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Valor inválido!");
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Selecione um tipo de reajuste!");
            }
        } 


    }//GEN-LAST:event_btnAplicarActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // Fecha janela]
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        // TODO add your handling code here:
        int linha = tblProdutos.getSelectedRow();
        txtNomeProduto.setText(null);
        if (radioPorGrupo.isSelected()) {
            txtId.setText(tblProdutos.getModel().getValueAt(linha, 0).toString());

        } else {
            txtId.setText(tblProdutos.getModel().getValueAt(linha, 0).toString());
            txtValor.setText(tblProdutos.getModel().getValueAt(linha, 2).toString());
            txtValorDireto.setText(txtValor.getText());
        }
        btnAplicar.setEnabled(true);

    }//GEN-LAST:event_tblProdutosMouseClicked

    private void txtPercentualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPercentualKeyReleased

    }//GEN-LAST:event_txtPercentualKeyReleased

    private void btnAplicarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnAplicarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplicarAncestorAdded

    private void txtValorDiretoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDiretoKeyReleased
        // Susbstitui virgula por ponto

    }//GEN-LAST:event_txtValorDiretoKeyReleased

    private void radioFatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFatorActionPerformed
        // Habilita fator de reajuste
        habilitaFator();
        desabilitaValorDireto();
        txtPercentual.requestFocus();
        txtValorDireto.setText("0,00");

    }//GEN-LAST:event_radioFatorActionPerformed

    private void radioValorDiretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioValorDiretoActionPerformed
        // Habilita alteração informando diretamente o valor desejado para o produto
        desabilitaFator();
        habilitaValorDireto();
        txtValorDireto.requestFocus();
        txtPercentual.setText("0,0");
    }//GEN-LAST:event_radioValorDiretoActionPerformed

    private void txtPercentualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPercentualFocusGained
        //Seleciona radio button
        radioFator.setSelected(true);
    }//GEN-LAST:event_txtPercentualFocusGained

    private void txtValorDiretoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorDiretoFocusGained
        // Seleciona radio button
        radioValorDireto.setSelected(true);
    }//GEN-LAST:event_txtValorDiretoFocusGained

    private void txtPercentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPercentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPercentualActionPerformed

    private void txtNomeProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutoKeyReleased
        // Localiza Produto
        tblProdutos.setModel(DbUtils.resultSetToTableModel(cp.pesquisarProduto(txtNomeProduto.getText())));
        model.redimensionaColunas(tblProdutos);
    }//GEN-LAST:event_txtNomeProdutoKeyReleased

    private void txtNomeProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoKeyPressed

    private void radioPorGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPorGrupoActionPerformed
        if (radioPorGrupo.isSelected()) {
            desabilitaValorDireto();
            habilitaFator();
            radioValorDireto.setEnabled(false);
            radioFator.setSelected(true);
        }
    }//GEN-LAST:event_radioPorGrupoActionPerformed

    private void radioPorValorUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPorValorUnitActionPerformed

        if (radioPorValorUnit.isSelected()) {
            radioValorDireto.setEnabled(true);
            txtId.setText(null);
            radioFator.setSelected(true);
            habilitaFator();

        }
    }//GEN-LAST:event_radioPorValorUnitActionPerformed

    private void radioPorGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioPorGrupoMouseClicked
        // Lista grupo
        tblProdutos.setModel(DbUtils.resultSetToTableModel(cg.listaGrupoProduto()));
        modelGrupo.redimensionaColunas(tblProdutos);
        lblPesquisarProduto.setVisible(false);
        txtNomeProduto.setVisible(false);
        txtNomeProduto.setText(null);
        lblTitulo.setText("Grupos");
        txtValorDireto.setText("0,00");
        txtPercentual.setText("0,0");
        btnAplicar.setEnabled(false);
    }//GEN-LAST:event_radioPorGrupoMouseClicked

    private void radioPorValorUnitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioPorValorUnitMouseClicked
        // Lista produtos para reajuste

        tblProdutos.setModel(DbUtils.resultSetToTableModel(cp.listaProdutoParaReajuste()));
        model.redimensionaColunas(tblProdutos);
        lblPesquisarProduto.setVisible(true);
        txtNomeProduto.setVisible(true);
        txtNomeProduto.setText(null);
        lblTitulo.setText("Produtos");
        txtValorDireto.setText("0,00");
        txtPercentual.setText("0,0");
        btnAplicar.setEnabled(false);
    }//GEN-LAST:event_radioPorValorUnitMouseClicked

    private void txtValorDiretoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDiretoKeyPressed

        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            FormataValor fv = new FormataValor();
            txtValorDireto.setText(fv.Formata(txtValorDireto.getText()));                            
        }
    }//GEN-LAST:event_txtValorDiretoKeyPressed

    private void txtValorDiretoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorDiretoFocusLost
        
            FormataValor fv = new FormataValor();
            txtValorDireto.setText(fv.Formata(txtValorDireto.getText()));                            
        
    }//GEN-LAST:event_txtValorDiretoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReajuste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordas;
    private javax.swing.JButton btnAplicar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCifra;
    private javax.swing.JLabel lblPercentual;
    private javax.swing.JLabel lblPesquisarProduto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelFormaReajuste;
    private javax.swing.JPanel panelProdutos;
    private javax.swing.JRadioButton radioFator;
    private javax.swing.JRadioButton radioPorGrupo;
    private javax.swing.JRadioButton radioPorValorUnit;
    private javax.swing.JRadioButton radioValorDireto;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPercentual;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorDireto;
    // End of variables declaration//GEN-END:variables
}
