/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.ConexaoBd;
import br.com.bar.dao.Log;
import br.com.bar.model.MovimentacaoCaixa;
import br.com.bar.model.Pedido;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerCaixa;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerMesa;
import br.com.br.controler.ControlerParametro;
import br.com.br.controler.ControlerPedido;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.*;
import org.jfree.data.category.DefaultCategoryDataset;
import br.com.bar.util.Util;
import java.awt.Color;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;

/**
 *
 * @author elias
 */
public class TelaCaixa extends javax.swing.JFrame {

    /**
     * Creates new form TelaCaixa
     */
    ControlerMesa cm = new ControlerMesa();
    ControlerPedido cp = new ControlerPedido();
    ControlerCaixa caixa = new ControlerCaixa();
    ControlerFuncionario func = new ControlerFuncionario();
    ControlerParametro cparam = new ControlerParametro();
    Connection conexao = ConexaoBd.conector();
    Util utils = new Util();

    Log l = new Log();
    Date data = new Date();

    public TelaCaixa() {
        initComponents();

        caixa.listaMesaOcupada(comboMesa);
        checkTxServico.setSelected(true);
        txtIdMEsa.setVisible(false);
        txtIdPedido.setVisible(false);

        try {

            lblSaídas.setText("R$ " + String.format("%9.2f", caixa.totalizaSaida(lblOperador.getText())));
        } catch (NullPointerException e) {
            lblSaídas.setText("0.00");
        }

        try {

            lblEntradas.setText("R$ " + String.format("%9.2f", caixa.totalizaEntradas(lblOperador.getText())));
        } catch (NullPointerException e) {
            lblEntradas.setText("0.00");
        }

        if (lblTotal.getText().isEmpty()) {

        } else {
            calculaTaxa();
        }

        //double saldo = caixa.totalizaEntradas(lblOperador.getText()) - caixa.totalizaSaida();
        double saldo = caixa.totalizaEntradas(lblOperador.getText()) - caixa.totalizaSaida(lblOperador.getText());

        lblSaldo.setText("RS" + String.format("%9.2f", saldo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelEsquerdo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblEntradas = new javax.swing.JLabel();
        lblSaídas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        btnGrafico = new javax.swing.JLabel();
        painelDireito = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        checkDinheiro = new javax.swing.JCheckBox();
        checkCartao = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTaxaServico = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        checkTxServico = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        txtTotalGeral = new javax.swing.JTextField();
        lblReceber = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnFecharCaixa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboMesa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalhePedido = new javax.swing.JTable();
        txtIdMEsa = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdPedido = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        lblGarcom = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinFieldPessoas = new com.toedter.components.JSpinField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        painelEsquerdo.setBackground(new java.awt.Color(52, 73, 94));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pagamentos");

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Entradas");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Saídas");

        lblEntradas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblEntradas.setForeground(new java.awt.Color(255, 255, 255));
        lblEntradas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEntradas.setText("jLabel14");

        lblSaídas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblSaídas.setForeground(new java.awt.Color(255, 255, 255));
        lblSaídas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSaídas.setText("jLabel14");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Movimentação");

        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Saldo");

        lblSaldo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setText("Saldo");

        btnGrafico.setForeground(new java.awt.Color(255, 255, 255));
        btnGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btnGrafico.png"))); // NOI18N
        btnGrafico.setText("Gráfico do Período");
        btnGrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraficoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelEsquerdoLayout = new javax.swing.GroupLayout(painelEsquerdo);
        painelEsquerdo.setLayout(painelEsquerdoLayout);
        painelEsquerdoLayout.setHorizontalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel14))
                            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel25))
                                .addGap(77, 77, 77)
                                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSaídas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGrafico)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        painelEsquerdoLayout.setVerticalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel9)
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addGap(35, 35, 35)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblEntradas))
                .addGap(18, 18, 18)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSaídas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblSaldo))
                .addGap(34, 34, 34)
                .addComponent(btnAtualizar)
                .addGap(18, 18, 18)
                .addComponent(btnGrafico)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(painelEsquerdo);
        painelEsquerdo.setBounds(0, 0, 380, 650);

        painelDireito.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Operador:");
        painelDireito.add(jLabel2);
        jLabel2.setBounds(170, 20, 100, 20);

        lblOperador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblOperador.setText("jLabel2");
        painelDireito.add(lblOperador);
        lblOperador.setBounds(250, 20, 90, 20);

        lblCargo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblCargo.setText("jLabel2");
        painelDireito.add(lblCargo);
        lblCargo.setBounds(250, 50, 90, 20);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Forma de Pagamento");
        painelDireito.add(jLabel7);
        jLabel7.setBounds(10, 150, 410, 48);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel5.setText("Forma de Pagamento");
        painelDireito.add(jLabel5);
        jLabel5.setBounds(200, 210, 190, 30);

        txtValorPago.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtValorPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValorPagoMouseClicked(evt);
            }
        });
        txtValorPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorPagoActionPerformed(evt);
            }
        });
        txtValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorPagoKeyPressed(evt);
            }
        });
        painelDireito.add(txtValorPago);
        txtValorPago.setBounds(70, 390, 130, 40);

        buttonGroup1.add(checkDinheiro);
        checkDinheiro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        checkDinheiro.setText("Dinheiro");
        painelDireito.add(checkDinheiro);
        checkDinheiro.setBounds(250, 290, 90, 29);

        buttonGroup1.add(checkCartao);
        checkCartao.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        checkCartao.setText("Cartão");
        painelDireito.add(checkCartao);
        checkCartao.setBounds(250, 260, 110, 29);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel10.setText("R$");
        painelDireito.add(jLabel10);
        jLabel10.setBounds(30, 260, 40, 30);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel11.setText("10%");
        painelDireito.add(jLabel11);
        jLabel11.setBounds(30, 320, 40, 30);

        txtTaxaServico.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtTaxaServico.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTaxaServico.setText("0.00");
        painelDireito.add(txtTaxaServico);
        txtTaxaServico.setBounds(70, 310, 130, 40);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel12.setText("Pago");
        painelDireito.add(jLabel12);
        jLabel12.setBounds(70, 350, 100, 30);

        checkTxServico.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        checkTxServico.setText("Taxa de Serviço");
        checkTxServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTxServicoMouseClicked(evt);
            }
        });
        checkTxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTxServicoActionPerformed(evt);
            }
        });
        painelDireito.add(checkTxServico);
        checkTxServico.setBounds(30, 460, 190, 29);

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel13.setText("Total Geral");
        painelDireito.add(jLabel13);
        jLabel13.setBounds(30, 210, 170, 30);

        txtTotalGeral.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtTotalGeral.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalGeralActionPerformed(evt);
            }
        });
        painelDireito.add(txtTotalGeral);
        txtTotalGeral.setBounds(70, 250, 130, 40);

        lblReceber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/caixa.png"))); // NOI18N
        lblReceber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReceberMouseClicked(evt);
            }
        });
        painelDireito.add(lblReceber);
        lblReceber.setBounds(30, 510, 120, 64);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel15.setText("Troco");
        painelDireito.add(jLabel15);
        jLabel15.setBounds(240, 360, 170, 30);

        txtTroco.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtTroco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTroco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTrocoFocusGained(evt);
            }
        });
        txtTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrocoActionPerformed(evt);
            }
        });
        txtTroco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTrocoKeyPressed(evt);
            }
        });
        painelDireito.add(txtTroco);
        txtTroco.setBounds(240, 390, 130, 40);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel16.setText("R$");
        painelDireito.add(jLabel16);
        jLabel16.setBounds(30, 400, 40, 30);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/power.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        painelDireito.add(jLabel17);
        jLabel17.setBounds(300, 520, 120, 50);

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel23.setText("Cargo:");
        painelDireito.add(jLabel23);
        jLabel23.setBounds(180, 50, 80, 20);

        btnFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Maquineta.png"))); // NOI18N
        btnFecharCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharCaixaMouseClicked(evt);
            }
        });
        painelDireito.add(btnFecharCaixa);
        btnFecharCaixa.setBounds(190, 486, 96, 90);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Logout");
        painelDireito.add(jLabel3);
        jLabel3.setBounds(290, 580, 130, 14);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Receber Pagamento");
        painelDireito.add(jLabel18);
        jLabel18.setBounds(30, 580, 130, 14);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Fechar Caixa");
        painelDireito.add(jLabel24);
        jLabel24.setBounds(170, 580, 130, 14);

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));

        btnFechar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFechar.setText("X");
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDireito.add(jPanel2);
        jPanel2.setBounds(380, 0, 50, 40);

        lblStatus.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        painelDireito.add(lblStatus);
        lblStatus.setBounds(10, 10, 140, 60);

        getContentPane().add(painelDireito);
        painelDireito.setBounds(830, 0, 450, 650);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel6.setText("Mesas");

        comboMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesaActionPerformed(evt);
            }
        });

        tblDetalhePedido.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 12)); // NOI18N
        tblDetalhePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PRODUTO", "COD.", "QTD.", "VALOR", "TOTAL"
            }
        ));
        tblDetalhePedido.setRowHeight(22);
        jScrollPane1.setViewportView(tblDetalhePedido);

        lblTotal.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Total R$ ");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa");

        btnListar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMouseClicked(evt);
            }
        });
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel22.setText("Garçom");

        lblGarcom.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/impressora64x64.png"))); // NOI18N
        btnImprimir.setText("Imprimir Parcial");
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimirMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/calendario (2).png"))); // NOI18N
        jLabel4.setText("Contas a Pagar");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel21.setText("Pessoas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jSpinFieldPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(77, 77, 77)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtIdMEsa, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(txtIdPedido)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblGarcom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtIdMEsa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(lblGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinFieldPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtIdMEsa, txtIdPedido});

        getContentPane().add(jPanel1);
        jPanel1.setBounds(380, 0, 460, 650);

        setSize(new java.awt.Dimension(1254, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
        // Fecha Janela
        dispose();
    }//GEN-LAST:event_btnFecharMouseClicked

    private void comboMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesaActionPerformed


    }//GEN-LAST:event_comboMesaActionPerformed

    private void txtTotalGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalGeralActionPerformed

    private void checkTxServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTxServicoMouseClicked
        // Retira taxa de serviço
        txtTaxaServico.setText("00.00");
        txtValorPago.setText("00.00");
        txtTroco.setText("00.00");
        calculaTaxa();

    }//GEN-LAST:event_checkTxServicoMouseClicked

    private void txtTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrocoActionPerformed

    private void txtValorPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorPagoActionPerformed
        // Limpa campo ao digitar valor

    }//GEN-LAST:event_txtValorPagoActionPerformed

    private void txtValorPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorPagoMouseClicked
        // Limpa valor pago ao clicar
        txtValorPago.setText(null);
    }//GEN-LAST:event_txtValorPagoMouseClicked

    private void txtValorPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPagoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTroco.requestFocus();
            double totalGeral = Double.parseDouble(txtTotalGeral.getText().replace(",", "."));
            double totalPago = Double.parseDouble(txtValorPago.getText().replace(",", "."));

            if (totalPago >= totalGeral) {
                txtTroco.setText(String.format("%9.2f", totalPago - totalGeral));

            } else {
                JOptionPane.showMessageDialog(null, "O valor pago não pode ser menor que o total da conta!");
                txtTroco.setText("00.00");

            }
        }

    }//GEN-LAST:event_txtValorPagoKeyPressed

    private void txtTrocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrocoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculaTaxa();
        }
    }//GEN-LAST:event_txtTrocoKeyPressed

    private void checkTxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTxServicoActionPerformed

    private void txtTrocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTrocoFocusGained

    }//GEN-LAST:event_txtTrocoFocusGained

    private void lblReceberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReceberMouseClicked
        // Fecha pedido

        // Calcula valor
        int nPesoas = jSpinFieldPessoas.getValue();
        if (nPesoas <= 0) {
            nPesoas = 1;
        }
        Double totalGeral = Double.parseDouble(txtTotalGeral.getText().replaceAll(",", "."));
        Double totalPessoas = totalGeral / nPesoas;
        System.out.println(nPesoas);
        
        // Instancia um produto
        Pedido p = new Pedido();
        p.setTotal(txtTotalGeral.getText().replaceAll(",", "."));
        p.setComissao(txtTaxaServico.getText().replaceAll(",", "."));
        p.setTotalPago(txtValorPago.getText().replaceAll(",", "."));
        p.setStatus("1");
        p.setOperador(lblOperador.getText());
        p.setId(txtIdPedido.getText());

        // Pega forma de pagamento selecionada
        if (checkCartao.isSelected()) {

            p.setFormaPagto("Cartão");
        } else {
            p.setFormaPagto("Dinheiro");
        }
        // Pega id da mesa.

        p.setCadMesaId(txtIdMEsa.getText());
        // Solicita confirmação do usuário
        int op = JOptionPane.showConfirmDialog(null, "Fecha este pedido ?", "Atenção", JOptionPane.YES_OPTION, JOptionPane.ERROR_MESSAGE);

        if (op == JOptionPane.YES_OPTION) {  // Se confirmado feha o pedido

            if (checkCartao.isSelected() || checkDinheiro.isSelected()) {
                // PEga a data Atual
                String dtAtual = utils.formataDataBr(data).replaceAll("/", "");
                // Pega a hora atual
                String horaAtual = utils.formataDataHora(data, "h");
                //Gera Autenticacao
                String autentica = cp.autentica(func.localizaId(lblGarcom.getText()), comboMesa.getSelectedItem().toString(), txtIdPedido.getText(), dtAtual + "." + horaAtual);
                p.setAutenticacao(autentica);

                cp.fechaPedido(p);

                //Início do Registro de log
                l.setFuncionalidade("Recebimento");
                l.setDescricao(l.getUsuario() + " Recebeu R$ " + p.getTotalPago() + " Pedido: " + txtIdPedido.getText() + " Comissão:" + p.getComissao());
                l.gravaLog(l);

                //
                cm.trocaStatusMesa(comboMesa.getSelectedItem().toString(), "0");
                JOptionPane.showMessageDialog(null, "Pedido fechado com sucesso!");
                //tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePedido(comboMesa.getSelectedItem().toString())));
                // Imprime cupom de pagamento
                HashMap dados = new HashMap();
                Date dt = new Date();
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");

                dados.put("data", df.format(dt));
                dados.put("garcom", lblGarcom.getText());
                dados.put("titulo", "COMPROVANTE DE PAGAMENTO");
                dados.put("tx", Double.parseDouble(txtTaxaServico.getText().replaceAll(",", ".")));
                dados.put("id_pedido", p.getId());
                dados.put("npessoas", nPesoas);
                dados.put("total_pessoas", totalPessoas);

                try {
                    JasperPrint print = JasperFillManager.fillReport(cparam.getRELATORIOS() + "cupom.jasper", dados, conexao);
                    JasperViewer.viewReport(print, false);
                    lblTotal.setText("0.00");
                } catch (JRException e) {
                    System.out.println("br.com.bar.view.TelaCaixa.btnImprimirMouseClicked()");
                }
                // Fim da impressão de cupom
                cp.limpaTabela(tblDetalhePedido);
                limpaForm();
                lblEntradas.setText(String.format("%9.2f", caixa.totalizaEntradas()));

                try {

                } catch (Exception e) {
                }

                try {

                    caixa.listaMesaOcupada(comboMesa);

                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "Não há pedidos!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma forma de pagameto");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");

        }
    }//GEN-LAST:event_lblReceberMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        //Sai da tela Caixa
        dispose();
        TelaLogin login = new TelaLogin();
        login.setVisible(true);

    }//GEN-LAST:event_jLabel17MouseClicked

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        // Localiza o id da mesa selecionada
        txtIdMEsa.setText(cm.localizaIdMesa(comboMesa.getSelectedItem().toString()));
        //Localiza o id do  Pedido
        txtIdPedido.setText(cp.LocalizaIdPedido(comboMesa.getSelectedItem().toString()));
        // Exibe detalhe do pedido por mesa de acordo com o id do pedido
        tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(comboMesa.getSelectedItem().toString(), txtIdPedido.getText())));

        // Inicializa das variáveis TOTAL E totalGeral
        double total = 0;
        double totalGeral = 0;

        try {
            // Lista resultado da pesquisa e totaliza os produtos do pedido

            ResultSet rs = cp.detalhePorPedido(comboMesa.getSelectedItem().toString(), txtIdPedido.getText());

            while (rs.next()) {
                total = Double.parseDouble(rs.getString("total"));
                totalGeral = totalGeral + total;
            }
            // Formata e exibe o total geral do pedido
            lblTotal.setText(String.format("%9.2f", totalGeral));

        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao calcular o total da compra" + e);
        }
        // Calcula a taxa de serviço somando ao total do pedido
        calculaTaxa();

        lblGarcom.setText(func.retornaGarcom(comboMesa.getSelectedItem().toString()));

        //Iníciodo registro de Log
        l.setFuncionalidade("Listar");
        l.setDescricao(l.getUsuario() + " listou o detalhe do pedido ->" + txtIdPedido.getText() + "  Gaçom " + lblGarcom.getText() + " Mesa-> " + comboMesa.getSelectedItem().toString());
        l.gravaLog(l);
        //
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseClicked
        try {

            lblSaídas.setText("R$ " + String.format("%9.2f", caixa.totalizaSaida(lblOperador.getText())));
        } catch (NullPointerException e) {
            lblSaídas.setText("0.00");
        }

        try {

            lblEntradas.setText("R$ " + String.format("%9.2f", caixa.totalizaEntradas(lblOperador.getText())));
        } catch (NullPointerException e) {
            lblEntradas.setText("0.00");
        }

        double saldo = caixa.totalizaEntradas(lblOperador.getText()) - caixa.totalizaSaida(lblOperador.getText());

        lblSaldo.setText("RS" + String.format("%9.2f", saldo));


    }//GEN-LAST:event_btnAtualizarMouseClicked

    private void btnImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseClicked
        //Imprime cupom
        // Calcula valor
        int nPesoas = jSpinFieldPessoas.getValue();
        if (nPesoas <= 0) {
            nPesoas = 1;
        }
        Double totalGeral = Double.parseDouble(txtTotalGeral.getText().replaceAll(",", "."));
        Double totalPessoas = totalGeral / nPesoas;
        System.out.println(nPesoas);
        //Início do Registro de log
        l.setFuncionalidade("Imprimir");
        l.setDescricao(l.getUsuario() + "Imprimiu a parcial do pedido N." + txtIdPedido.getText() + " Comissão: " + txtTaxaServico.getText());
        l.gravaLog(l);

        //
        HashMap dados = new HashMap();
        Date dt = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");

        dados.put("data", df.format(dt));
        dados.put("id_pedido", txtIdPedido.getText());
        dados.put("garcom", lblGarcom.getText());
        dados.put("titulo", "PARCIAL DE CONSUMO");
        dados.put("tx", Double.parseDouble(txtTaxaServico.getText().replaceAll(",", ".")));
        dados.put("npessoas", nPesoas);
        dados.put("total_pessoas", totalPessoas);

        try {
            JasperPrint print = JasperFillManager.fillReport(cparam.getRELATORIOS() + "cupom.jasper", dados, conexao);
            JasperViewer.viewReport(print, false);
        } catch (JRException e) {
            System.out.println("br.com.bar.view.TelaCaixa.btnImprimirMouseClicked()" + e);
        }

    }//GEN-LAST:event_btnImprimirMouseClicked

    private void btnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarMouseClicked

    private void btnFecharCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharCaixaMouseClicked
        // Realiza o fechamento do caixa

        Date dataAtual = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");

        MovimentacaoCaixa cx = new MovimentacaoCaixa();

        cx.setData(df.format(dataAtual));
        cx.setEntrada(caixa.totalizaEntradas(lblOperador.getText()));
        cx.setSaida(caixa.totalizaSaida(lblOperador.getText()));
        cx.setSaldo(caixa.totalizaEntradas(lblOperador.getText()) - caixa.totalizaSaida(lblOperador.getText()));
        cx.setStatus(1);
        cx.setIdFuncionario(Integer.parseInt(func.localizaIdLogin(lblOperador.getText())));

        int op = JOptionPane.showConfirmDialog(null, lblOperador.getText() + " Tem certeza que deseja fechar seu caixa?", "Atenção", JOptionPane.YES_NO_OPTION);

        if (op == JOptionPane.YES_OPTION) {

            if (caixa.temMovimentacao(cx.getIdFuncionario())) { // Verifica se existe movimentação no dia para este operador.
                JOptionPane.showMessageDialog(null, "Caixa fechado, contate o administrador!");

            } else {
                if (caixa.gravaMovimentacao(cx)) {
                    JOptionPane.showMessageDialog(null, "Caixa fechado com sucesso!");
                    // Inicio do Registro de Log
                    l.setDescricao("Caixa");
                    l.setFuncionalidade("Fehamento de Caixa");
                    l.setUsuario(lblOperador.getText());
                    l.gravaLog(l);
                    // Fim do Registro de Log

                    // Imprime relatório de caixa 
                    HashMap param = new HashMap();
                    Date dt = new Date();
                    param.put("data", df.format(dt));
                    param.put("id_perador", cx.getIdFuncionario());

                    // Troca imagem de status
                    caixa.statusCaixa(lblStatus, caixa.temMovimentacao(cx.getIdFuncionario()));

                    try {

                        JasperPrint print = JasperFillManager.fillReport(cparam.getRELATORIOS() + "relMovimentacaoOperador.jasper", param, conexao);
                        JasperViewer.viewReport(print, false);

                    } catch (JRException e) {
                        System.out.println("br.com.bar.view.TelaCaixa.btnFecharCaixaMouseClicked()" + e);
                    }

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");

        }

    }//GEN-LAST:event_btnFecharCaixaMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // Chama a tela de Cadastro de Contas a pagar
        TelaContasApagar contaApagar = new TelaContasApagar();
        contaApagar.recebeOperador(lblOperador.getText(), lblCargo.getText());
        contaApagar.setVisible(true);


    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnGraficoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficoMouseClicked
        // Cria gráfico do Período

        Date dtAtual = new Date();

        String mesAtual = utils.formataData(dtAtual);
        ResultSet rs;
        rs = caixa.listaMovimentacao(mesAtual);

        // Cria data set para o gráfico
        DefaultCategoryDataset ds = new DefaultCategoryDataset();

        try {

            while (rs.next()) {
                ds.setValue(rs.getDouble("entradas"), "Entradas", rs.getString("data"));
                ds.setValue(rs.getDouble("saidas"), "Saídas", rs.getString("data"));
            }

        } catch (SQLException e) {
            System.out.println("Não há movimentação a ser listada ");
        }

        // Criando Gráfico de Barras'
        JFreeChart graficoBarras = ChartFactory.createBarChart("Movimentação Financeira", "Período", "Movimentação em R$", ds, PlotOrientation.VERTICAL, true, true, false);
        // Cria e recebe a categoria de plotagem do gráfico de barras
        CategoryPlot categoryPlot = graficoBarras.getCategoryPlot();
        // Atribui cores as barras do gráfico
        graficoBarras.getCategoryPlot().getRenderer().setSeriesPaint(0, Color.BLUE);
        graficoBarras.getCategoryPlot().getRenderer().setSeriesPaint(1, Color.RED);
        // Adiciona linhas de grade ao gráfico
        categoryPlot.setRangeGridlinePaint(Color.blue);
        // Cria janela do gráfico
        ChartFrame frame = new ChartFrame("Gráfico Movimentação do Período", graficoBarras);
        // Define a dimensão do gráfico
        frame.setSize(800, 600);
        //

        frame.setVisible(true);

    }//GEN-LAST:event_btnGraficoMouseClicked
    public void recebeOperador(String operador, String cargo) {
        lblOperador.setText(operador);
        lblCargo.setText(cargo);
        l.setUsuario(operador);
        String id = func.localizaIdLogin(operador);
        caixa.statusCaixa(lblStatus, caixa.temMovimentacao(Integer.parseInt(id)));
    }

    public void limpaForm() {
        txtIdMEsa.setText(null);
        txtIdPedido.setText(null);
        txtTaxaServico.setText(null);
        txtTotalGeral.setText(null);
        txtTroco.setText(null);
        txtValorPago.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtualizar;
    private javax.swing.JLabel btnFechar;
    private javax.swing.JLabel btnFecharCaixa;
    private javax.swing.JLabel btnGrafico;
    private javax.swing.JLabel btnImprimir;
    private javax.swing.JButton btnListar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkCartao;
    private javax.swing.JCheckBox checkDinheiro;
    private javax.swing.JCheckBox checkTxServico;
    private javax.swing.JComboBox<String> comboMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinFieldPessoas;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblEntradas;
    private javax.swing.JLabel lblGarcom;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblReceber;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaídas;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel painelDireito;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JTable tblDetalhePedido;
    private javax.swing.JTextField txtIdMEsa;
    private javax.swing.JTextField txtIdPedido;
    private javax.swing.JTextField txtTaxaServico;
    private javax.swing.JTextField txtTotalGeral;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables

    private void calculaTaxa() {

        double txServico = 0.10; // 10%
        double totalConta = Double.parseDouble(lblTotal.getText().replaceAll(",", "."));
        double totalTxServico = totalConta * txServico;
        double totalPago = 0;
        double troco = 0;

        if (checkTxServico.isSelected()) {

            txtTotalGeral.setText(String.format("%9.2f", totalConta + totalTxServico));
            txtTaxaServico.setText(String.format("%9.2f", totalTxServico));
        } else {
            txtTotalGeral.setText(String.format("%9.2f", totalConta));
            txtTaxaServico.setText("00.00");

        }

    }

}
