/*
 * Esta tela é responsável por exibir os relatórios na tela do sistema
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.ConexaoBd;
import br.com.bar.dao.ReportUtil;
import br.com.br.controler.ControlerContasApagar;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerParametro;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import br.com.bar.dao.Log;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias Santana
 */
public class TelaRelatorio extends javax.swing.JFrame {

    ControlerParametro p = new ControlerParametro();
    Connection conexao = ConexaoBd.conector();
    ControlerFuncionario f = new ControlerFuncionario();
    Log l = new Log();

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {

        initComponents();
        f.carregaComboCargo(comboCargos);
        Calendar c = Calendar.getInstance();
        dataInicio.setDate(c.getTime());
        dataFim.setDate(c.getTime());
    }

    public void recebeOperador(String operador, String cargo) {
        lblcargo.setText(cargo);
        lblUsuario.setText(operador);
        l.setUsuario(operador);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtablePanel = new javax.swing.JTabbedPane();
        panelGeral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        comboGrupos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        painelfinanceiro = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        comboFinanceiro = new javax.swing.JComboBox<>();
        btnOKFinanceiro = new javax.swing.JButton();
        dataInicio = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dataFim = new com.toedter.calendar.JDateChooser();
        panelProdutos = new javax.swing.JPanel();
        comboRelProduto = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JButton();
        panelFuncionarios = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboCargos = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        btnOK1 = new javax.swing.JButton();

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/relatorios48x48.png"))); // NOI18N
        jLabel16.setText("Relatórios");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(243, 156, 18));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Relatórios");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 40, 147, 48);

        lblcargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblcargo.setText("cargo");
        jPanel1.add(lblcargo);
        lblcargo.setBounds(300, 80, 90, 32);

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblUsuario.setText("usuario");
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(300, 40, 80, 30);

        jPanel6.setBackground(new java.awt.Color(91, 91, 95));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(400, 0, 42, 40);

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/cadastro-64.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 20, 112, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 130);

        jtablePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Relatórios Gerais"))));

        comboGrupos.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        comboGrupos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupos de Produto", "Grupos Financeiro", "Relatório de Mesas" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGeralLayout = new javax.swing.GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jtablePanel.addTab("Geral", panelGeral);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Relatórios Financeiros"))));

        comboFinanceiro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        comboFinanceiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relatório de Comissão Sitético", "Relatório de Comissão Análitico", "Contas Vencidas", "Contas a Vencer", "Relatório de Saídas", "Relatório de Entradas", "Relatório de Caixa Sintético", "Relatório de Movimentação - Estoque" }));

        btnOKFinanceiro.setText("OK");
        btnOKFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKFinanceiroActionPerformed(evt);
            }
        });

        dataInicio.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        dataInicio.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        jLabel4.setText("Início");

        jLabel5.setText("Fim");

        dataFim.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        dataFim.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboFinanceiro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5))))
                    .addComponent(btnOKFinanceiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(comboFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btnOKFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelfinanceiroLayout = new javax.swing.GroupLayout(painelfinanceiro);
        painelfinanceiro.setLayout(painelfinanceiroLayout);
        painelfinanceiroLayout.setHorizontalGroup(
            painelfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelfinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        painelfinanceiroLayout.setVerticalGroup(
            painelfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelfinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jtablePanel.addTab("Financeiro", painelfinanceiro);

        comboRelProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        comboRelProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos em Estoque", "Relatório de Compras (Posição Estoque)" }));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProdutosLayout = new javax.swing.GroupLayout(panelProdutos);
        panelProdutos.setLayout(panelProdutosLayout);
        panelProdutosLayout.setHorizontalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(comboRelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelProdutosLayout.setVerticalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboRelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jtablePanel.addTab("Produtos", panelProdutos);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Relatório de Funcionários  por cargos"))));

        jLabel3.setText("Cargos");

        comboCargos.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboCargos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnOK, comboCargos});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Relatório de Funcionários  por cargos"))));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Funcionarios Ativos / Inativos");

        comboTipo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Inativo", "Ativo" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOK1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnOK1, comboTipo});

        javax.swing.GroupLayout panelFuncionariosLayout = new javax.swing.GroupLayout(panelFuncionarios);
        panelFuncionarios.setLayout(panelFuncionariosLayout);
        panelFuncionariosLayout.setHorizontalGroup(
            panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionariosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelFuncionariosLayout.setVerticalGroup(
            panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionariosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jtablePanel.addTab("Funcionários", panelFuncionarios);

        getContentPane().add(jtablePanel);
        jtablePanel.setBounds(10, 130, 430, 390);

        setSize(new java.awt.Dimension(436, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // Ativa opções selecionadas

    }//GEN-LAST:event_comboTipoActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // Fehcajanela
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        ReportUtil rpu = new ReportUtil();
        HashMap filtro = new HashMap();
        filtro.put("filtro", comboCargos.getSelectedItem().toString());
        rpu.abreRelatorio(p.getRELATORIOS(), "relFuncPorCargo.jasper", filtro);

    }//GEN-LAST:event_btnOKActionPerformed

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
        int opcao = comboTipo.getSelectedIndex();

        HashMap map = new HashMap();

        if (0 == opcao) {
            try {

                JasperPrint print = JasperFillManager.fillReport(p.getRELATORIOS() + "relGeralDeFuncionarios.jasper", null, conexao);
                JasperViewer.viewReport(print, false);

                // Início do registro de Log
                l.setFuncionalidade("Relatório");
                l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " geral de Funcionários");
                l.gravaLog(l);
                // Fim do registro de Log

            } catch (JRException ex) {
                Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

            switch (opcao) {
                case 1:
                    map.put("b", 1); // Funcionários Inativo
                    break;
                case 2:
                    map.put("b", 0); // Funcionarios Ativos
                    break;

            }

            try {
                JasperPrint print = JasperFillManager.fillReport(p.getRELATORIOS() + "relFuncBlocDesb.jasper", map, conexao);
                JasperViewer.viewReport(print, false);
                // Início do registro de Log
                l.setFuncionalidade("Relatório");
                l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " relatório geral de funcionários");
                l.gravaLog(l);
                // Fim do registro de Log
            } catch (JRException ex) {
                Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnOK1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Exibe relatório 
        ReportUtil rpu = new ReportUtil();
        int opcao = comboGrupos.getSelectedIndex();
        switch (opcao) {
            case 0: // Grupo Produto
                rpu.abreRelatorio(p.getRELATORIOS(), "relGruposProduto.jasper", null);
                // Início do registro de Log
                l.setFuncionalidade("Relatório");
                l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " de Grupos de Produto");
                l.gravaLog(l);
                // Fim do registro de Log
                break;
            case 1: // Grupo Produto
                rpu.abreRelatorio(p.getRELATORIOS(), "relGruposFinanceiro.jasper", null);
                // Início do registro de Log
                l.setFuncionalidade("Relatório");
                l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " de Grupos Financeiros");
                l.gravaLog(l);
                // Fim do registro de Log
                break;
            case 2: // Relatório de mesas
                rpu.abreRelatorio(p.getRELATORIOS(), "relatorioDeMesas.jasper", null);
                // Início do registro de Log
                l.setFuncionalidade("Relatório");
                l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " de Mesas");
                l.gravaLog(l);
                // Fim do registro de Log
                break;

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnOKFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKFinanceiroActionPerformed
        ControlerContasApagar cap = new ControlerContasApagar();

        int opcao = comboFinanceiro.getSelectedIndex();

        HashMap datas = new HashMap();
        HashMap dtGeral = new HashMap();
        String dtInicio = cap.myData(dataInicio);

        String dtFim = cap.myData(dataFim);
        System.out.println(dtInicio);
        System.out.println(dtFim);
        //datas.put("dtInicio", dtInicio);
        //datas.put("dtFim", dtFim);
        ReportUtil rpu = new ReportUtil();

        //rpu.rio(p.getRELATORIOS(), "relGeralComissao.jasper", datas);
        switch (opcao) {

            case 0:
                try {
                    datas.put("dtInicio", dtInicio);
                    datas.put("dtFim", dtFim);
                    JasperPrint print = JasperFillManager.fillReport("c:/sysbar/rel/relSintComissao.jasper", datas, conexao);
                    JasperViewer.viewReport(print, false);
                    // Início do registro de Log
                    l.setFuncionalidade("Relatório");
                    l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " sitético de Comissão");
                    l.gravaLog(l);
                    // Fim do registro de Log
                } catch (JRException e) {
                    System.out.println("Erro ao abrir relatório sintético");
                }
                break;
            case 1:
                try {
                    dtGeral.put("dataInicio", dtInicio);
                    dtGeral.put("dataFim", dtFim);
                    JasperPrint print = JasperFillManager.fillReport("c:/sysbar/rel/comissaoGeral.jasper", dtGeral, conexao);
                    JasperViewer.viewReport(print, false);
                    // Início do registro de Log
                    l.setFuncionalidade("Relatório");
                    l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " geral de Comissões");
                    l.gravaLog(l);
                    // Fim do registro de Log
                } catch (JRException e) {
                    System.out.println("Erro ao abrir relatório analítico");
                }
                break;
            case 2:
                try {

                    JasperPrint print = JasperFillManager.fillReport("c:/sysbar/rel/contasApagarVencidas.jasper", null, conexao);
                    JasperViewer.viewReport(print, false);
                    // Início do registro de Log
                    l.setFuncionalidade("Relatório");
                    l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " contas a pagar");
                    l.gravaLog(l);
                    // Fim do registro de Log
                } catch (JRException e) {
                    System.out.println("Erro ao abrir relatório de contas a pagar vencidas");
                }
                break;
            case 3:
                try {

                    JasperPrint print = JasperFillManager.fillReport("c:/sysbar/rel/contasAvencer.jasper", null, conexao);
                    JasperViewer.viewReport(print, false);
                    // Início do registro de Log
                    l.setFuncionalidade("Relatório");
                    l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " de contas a vencer");
                    l.gravaLog(l);
                    // Fim do registro de Log
                } catch (JRException e) {
                    System.out.println("Erro ao abrir relatório de contas a vencer");
                }
                break;
            case 4: // Imprime relatóriode de Saída de caixa / Despesas
                try {
                    
                    HashMap periodo = new HashMap();
                    periodo.put("dt_inicio", dtInicio);
                    periodo.put("dt_fim", dtFim);
                                        
                    rpu.imprimiRelatorioTela("Saidas.jasper", periodo);
                    // Início do registro de Log

                    l.setFuncionalidade("Relatório");
                    l.setDescricao(l.getUsuario() + " acessou o " + l.getFuncionalidade() + " de contas pagas");
                    l.gravaLog(l);

                    // Fim do registro de Log
                } catch (JRException e) {
                    System.out.println("Erro ao abrir relatório de contas pagas");
                }
                break;
            case 5:
                /*
                 * Relatório de Fechamento Entradas
                 * 
                 */

                // Instancia classe responsável pela impressão do relatório
                ReportUtil reportUtil = new ReportUtil();
                // Instancia HashMap de parâmetros
                HashMap map = new HashMap();
                map.put("inicio", dtInicio);
                map.put("fim", dtFim);

                try {
                    /*
                    O metodo imprimiRelatorioTela abre o relatório informado
                    caso não haja movimentação de saída no dia ele abrirá o relatório de caixa 2
                    que relaciona apenas as entradas do dia.
                     */
                    reportUtil.imprimiRelatorioTela("relCaixa.jasper", map);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Você ainda não possui movimentação!");
                }

                break;
            case 6:
                /*
                 * Relatório de Fechamento Entradas
                 * 
                 */

                // Instancia classe responsável pela impressão do relatório
                ReportUtil report = new ReportUtil();
                // Instancia HashMap de parâmetros
                HashMap maps = new HashMap();
                maps.put("inicio", dtInicio);
                maps.put("fim", dtFim);

                try {
                    /*
                    O metodo imprimiRelatorioTela sitético das movimentações do período
                     */
                    report.imprimiRelatorioTela("caixaSintetico.jasper", maps);

                } catch (Exception e) {
                    System.out.println("br.com.bar.view.TelaRelatorio.btnOKFinanceiroActionPerformed()" + e);
                }

                break;
           
        }


    }//GEN-LAST:event_btnOKFinanceiroActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        //Abre relatório

        int opcao = comboRelProduto.getSelectedIndex();
        switch (opcao) {
            case 0:
                try {
                    JasperPrint print = JasperFillManager.fillReport("c:/SysBar/rel/relProdutos.jasper", null, conexao);
                    JasperViewer.viewReport(print, false);
                } catch (JRException e) {
                    System.out.println("Erro relatório de produtos em estoque");
                }
                break;

            case 1:

                try {
                    JasperPrint print = JasperFillManager.fillReport("c:/SysBar/rel/relPosicaoEstoque.jasper", null, conexao);
                    JasperViewer.viewReport(print, false);
                } catch (JRException e) {
                    System.out.println("Erro relatório de posição do Estoque");
                }
                break;
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOK1;
    private javax.swing.JButton btnOKFinanceiro;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboCargos;
    private javax.swing.JComboBox<String> comboFinanceiro;
    private javax.swing.JComboBox<String> comboGrupos;
    private javax.swing.JComboBox<String> comboRelProduto;
    private javax.swing.JComboBox<String> comboTipo;
    private com.toedter.calendar.JDateChooser dataFim;
    private com.toedter.calendar.JDateChooser dataInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jtablePanel;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JPanel painelfinanceiro;
    private javax.swing.JPanel panelFuncionarios;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JPanel panelProdutos;
    // End of variables declaration//GEN-END:variables
}
