/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.Log;
import br.com.bar.model.Fornecedor;
import br.com.bar.model.Produto;
import br.com.bar.model.TableModelCadastroProduto;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerEstoque;
import br.com.br.controler.ControlerFornecedor;
import br.com.br.controler.ControlerGrupo;
import br.com.br.controler.ControlerProduto;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class TelaCadastroProduto extends javax.swing.JFrame {

    ControlerProduto cp = new ControlerProduto();
    ControlerGrupo g = new ControlerGrupo();
    ControlerEstoque e = new ControlerEstoque();
    ControlerFornecedor cf = new ControlerFornecedor();
    Util u = new Util();
    TableModelCadastroProduto modelCadastroProduto = new TableModelCadastroProduto();
    Log l = new Log();
    TelaPesquisaProduto telaPesquisa;
    /**
     * Creates new form TelaCadastroProduto
     */
    public TelaCadastroProduto() {
        initComponents();

        g.carregaComboGrupoProduto(comboGrupoProduto);

        cf.carregaComboFornecedor(comboFornecedor);
        if ("Gerente".equals(lblCargo.getText())) {
            btnAdicionarFornecedor.setEnabled(true);
        } else {
            btnAdicionarFornecedor.setEnabled(false);
        }

        lblCargo.setVisible(false);
        lblOperador.setVisible(false);
       

    }

    public void recebeOperador(String operador, String cargo, String titulo) {

        lblCargo.setText(cargo);
        lblOperador.setText(operador);
        // Adiciona nome do operador ao log
        l.setUsuario(lblOperador.getText());
        lblTitulo.setText(titulo);
        if ("Gerente".equals(lblCargo.getText())) {
            btnAdicionarFornecedor.setVisible(true);
        } else {
            btnAdicionarFornecedor.setVisible(false);
        }
        
      if ("Alterar".equals(titulo)){
          bloqueiaCampos();
      }
   
    }
    
    public void recebeProduto(TelaPesquisaProduto tela, Produto p){
        txtDescricao.setText(p.getNome());
        txtQtdMin.setText(p.getQtdMin());
        txtQtdMax.setText(p.getQtdMax());
        txtQuantidade.setText(p.getQtd());
        txtValor.setText(p.getValor());
        comboFornecedor.setSelectedIndex(0);
        comboGrupoProduto.setSelectedIndex(0);
        this.telaPesquisa = tela;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bordas = new javax.swing.JPanel();
        painelEsquerdo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQtdMin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtdMax = new javax.swing.JTextField();
        comboGrupoProduto = new javax.swing.JComboBox<>();
        btnAdicionarFornecedor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblGrupoProduto = new javax.swing.JLabel();
        comboFornecedor = new javax.swing.JComboBox<>();
        btnAdicionarGrupo1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JLabel();
        panelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        bordas.setBackground(new java.awt.Color(204, 204, 204));
        bordas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        bordas.setLayout(null);

        painelEsquerdo.setBackground(new java.awt.Color(38, 53, 61));
        painelEsquerdo.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição");
        painelEsquerdo.add(jLabel3);
        jLabel3.setBounds(20, 0, 220, 30);

        txtDescricao.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescricaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDescricaoMouseEntered(evt);
            }
        });
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });
        painelEsquerdo.add(txtDescricao);
        txtDescricao.setBounds(20, 30, 330, 40);

        txtQuantidade.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });
        painelEsquerdo.add(txtQuantidade);
        txtQuantidade.setBounds(20, 110, 130, 40);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantidade");
        painelEsquerdo.add(jLabel4);
        jLabel4.setBounds(20, 80, 130, 30);

        txtValor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
        });
        txtValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValorMouseClicked(evt);
            }
        });
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
        });
        painelEsquerdo.add(txtValor);
        txtValor.setBounds(220, 110, 130, 40);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor R$");
        painelEsquerdo.add(jLabel5);
        jLabel5.setBounds(220, 80, 130, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fornecedor");
        painelEsquerdo.add(jLabel6);
        jLabel6.setBounds(20, 290, 170, 30);

        txtQtdMin.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtQtdMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtdMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdMinKeyPressed(evt);
            }
        });
        painelEsquerdo.add(txtQtdMin);
        txtQtdMin.setBounds(20, 180, 130, 40);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantidade Máxima");
        painelEsquerdo.add(jLabel7);
        jLabel7.setBounds(220, 150, 170, 30);

        txtQtdMax.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtQtdMax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelEsquerdo.add(txtQtdMax);
        txtQtdMax.setBounds(220, 180, 130, 40);

        comboGrupoProduto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        comboGrupoProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboGrupoProdutoItemStateChanged(evt);
            }
        });
        comboGrupoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGrupoProdutoActionPerformed(evt);
            }
        });
        painelEsquerdo.add(comboGrupoProduto);
        comboGrupoProduto.setBounds(20, 250, 200, 40);

        btnAdicionarFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdicionarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/adicionar.png"))); // NOI18N
        btnAdicionarFornecedor.setToolTipText("Adicionar Novo Grupo");
        btnAdicionarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarFornecedorMouseClicked(evt);
            }
        });
        painelEsquerdo.add(btnAdicionarFornecedor);
        btnAdicionarFornecedor.setBounds(230, 320, 50, 40);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantidade Mínima");
        painelEsquerdo.add(jLabel9);
        jLabel9.setBounds(20, 150, 170, 30);

        lblGrupoProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblGrupoProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblGrupoProduto.setText("Grupo ");
        painelEsquerdo.add(lblGrupoProduto);
        lblGrupoProduto.setBounds(20, 220, 170, 30);

        comboFornecedor.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        comboFornecedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFornecedorItemStateChanged(evt);
            }
        });
        comboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFornecedorActionPerformed(evt);
            }
        });
        painelEsquerdo.add(comboFornecedor);
        comboFornecedor.setBounds(20, 320, 200, 40);

        btnAdicionarGrupo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdicionarGrupo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/adicionar.png"))); // NOI18N
        btnAdicionarGrupo1.setToolTipText("Adicionar Novo Grupo");
        btnAdicionarGrupo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarGrupo1MouseClicked(evt);
            }
        });
        painelEsquerdo.add(btnAdicionarGrupo1);
        btnAdicionarGrupo1.setBounds(230, 250, 50, 40);

        btnSalvar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/salvar32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        painelEsquerdo.add(btnSalvar);
        btnSalvar.setBounds(140, 390, 110, 50);

        bordas.add(painelEsquerdo);
        painelEsquerdo.setBounds(0, 110, 400, 450);

        panelSuperior.setBackground(new java.awt.Color(243, 156, 18));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/estoque.png"))); // NOI18N
        panelSuperior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 70));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblTitulo.setText("titulo");
        panelSuperior.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, 40));

        jPanel3.setBackground(new java.awt.Color(38, 53, 61));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fecharWhite24x24.png"))); // NOI18N
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelSuperior.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel8.setText("de Produto");
        panelSuperior.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        lblOperador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblOperador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblOperador.setText("Operador:");
        panelSuperior.add(lblOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, 30));

        lblCargo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblCargo.setText("Cargo:");
        panelSuperior.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 100, 30));

        bordas.add(panelSuperior);
        panelSuperior.setBounds(0, 0, 400, 110);

        getContentPane().add(bordas);
        bordas.setBounds(0, 0, 398, 568);

        setSize(new java.awt.Dimension(397, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if ("Alterar".equals(lblTitulo.getText())){
            telaPesquisa.atualizaTabela();
        }
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void txtDescricaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescricaoMouseEntered
        // Vai para o próximo campo

    }//GEN-LAST:event_txtDescricaoMouseEntered

    private void txtDescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescricaoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDescricaoMouseClicked

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtQuantidade.requestFocus();
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        // Vai para o campo valor

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValor.requestFocus();
        }
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
        // Vai para quantidade mínima
        String valor = txtValor.getText();
        String novovalor = valor.replaceAll(",", ".");
        txtValor.setText(novovalor);

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtQtdMin.requestFocus();
        }
    }//GEN-LAST:event_txtValorKeyPressed

    private void txtQtdMinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdMinKeyPressed
        // Vai para Quantidade Máxima
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtQtdMax.requestFocus();
            txtQtdMax.setText(txtQuantidade.getText());
        }
    }//GEN-LAST:event_txtQtdMinKeyPressed

    private void comboGrupoProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboGrupoProdutoItemStateChanged


    }//GEN-LAST:event_comboGrupoProdutoItemStateChanged

    private void comboGrupoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGrupoProdutoActionPerformed


    }//GEN-LAST:event_comboGrupoProdutoActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        // Salva um produto

        Fornecedor f = new Fornecedor();
        f.setNome(comboFornecedor.getSelectedItem().toString());

        Produto p = new Produto();
        p.setNome(txtDescricao.getText());
        p.setQtd(txtQuantidade.getText());
        p.setQtdMax(txtQtdMax.getText());
        p.setQtdMin(txtQtdMin.getText());
        p.setValor(txtValor.getText());
        p.setIdFornecedor(Integer.parseInt(cf.localizaForecedor(f)));

        p.setTbGrupoId(g.localizaIdGrupoProduto(comboGrupoProduto));

        if (p.getValor() == null) {
            JOptionPane.showMessageDialog(null, "O produto não pode ser adicionado");
        } else {
            if (cp.temProduto(p)) {
                JOptionPane.showMessageDialog(null, "O produto " + p.getNome() + " já Existe!");
                limpaForm();
            } else {

                if (cp.adicionaProduto(p)) {
                    JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso!");
                    limpaForm();                    
                    // Início do Registro de Log
                    l.setDescricao("Adicionou o produto " + p.getNome() + " ao estoque");
                    l.setFuncionalidade("Salvar");
                    l.gravaLog(l);
                    // Fim do Log

                    // Localiza id do produto adicionado             
                    String id = e.localizaIdProduto(p.getNome());
                    // Registra movimentação
                    e.registraMovimentacao(id, p.getQtd(), e.localizaIdOperacao("Entrada"), "Produto Novo");

                }
            }

        }

    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnAdicionarFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarFornecedorMouseClicked
        // Chama Tela Fornecedores
        TelaCadastroFornecedor cadfor = new TelaCadastroFornecedor();
        cadfor.setAlwaysOnTop(true);
        cadfor.recebeOperador(lblOperador.getText(), lblCargo.getText(), "Incluir", null);
        //cadfor.recebeOperador(lblOperador.getText(), lblCargo.getText());
        cadfor.setVisible(true);
    }//GEN-LAST:event_btnAdicionarFornecedorMouseClicked

    private void btnAdicionarGrupo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarGrupo1MouseClicked
        // Chama o cadastro de Grupos
        TelaGruposProdutos gp = new TelaGruposProdutos();
        gp.setAlwaysOnTop(true);
        gp.recebeOperador(lblOperador.getText());
        gp.setVisible(true);
    }//GEN-LAST:event_btnAdicionarGrupo1MouseClicked

    private void comboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFornecedorActionPerformed


    }//GEN-LAST:event_comboFornecedorActionPerformed

    private void comboFornecedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFornecedorItemStateChanged

    }//GEN-LAST:event_comboFornecedorItemStateChanged

    private void txtValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorMouseClicked
        // Limpa campo valor
        txtValor.setText(null);
    }//GEN-LAST:event_txtValorMouseClicked

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        // Limpa campo valor ao receber o foco
        txtValor.setText(null);
    }//GEN-LAST:event_txtValorFocusGained
    private void limpaForm() {

        txtDescricao.setText(null);
        txtQuantidade.setText(null);
        txtQtdMax.setText(null);
        txtQtdMin.setText(null);
        txtValor.setText(null);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordas;
    private javax.swing.JLabel btnAdicionarFornecedor;
    private javax.swing.JLabel btnAdicionarGrupo1;
    private javax.swing.JLabel btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboFornecedor;
    private javax.swing.JComboBox<String> comboGrupoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblGrupoProduto;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQtdMax;
    private javax.swing.JTextField txtQtdMin;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void bloqueiaCampos() {
        txtDescricao.setEnabled(false);
        txtQuantidade.setEnabled(false);
        txtValor.setEnabled(false);
    }

}
