/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.Log;
import br.com.bar.model.Funcionario;
import br.com.bar.model.Mesa;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerMesa;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author elias
 */
public class TelaCadastroDeMesas extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroDeMesas
     */
    Mesa m = new Mesa();
    ControlerMesa cm = new ControlerMesa();
    ControlerFuncionario f = new ControlerFuncionario();
    
    Log log = new Log();
    
            
    boolean filtro = false; // Filtro de listagem de mesa false -> Apenas mesas do garçom selecionado  true -> Todas as mesas
    int estado = 0;

    public TelaCadastroDeMesas() {
        initComponents();
        txtIdGarcom.setVisible(false);
        txtIdMesa.setVisible(false);
        panelTroca.setVisible(false);
        txtIdNovoGarcom.setVisible(false);

        f.carregaComboFuncionario(comboGarcom, "Garçom");

        if (jCheckBoxTudo.isSelected()) {
            filtro = true;
        }

        tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), filtro)));

    }
    
    public void recebeOperador (String operador, String cargo){
        
        lblOperador.setText(cargo);
        lblCargo.setText(operador);
        log.setUsuario(operador);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdGarcom = new javax.swing.JTextField();
        txtIdMesa = new javax.swing.JTextField();
        comboGarcom = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNumeroMesa = new javax.swing.JTextField();
        panelTroca = new javax.swing.JPanel();
        comboNovoGarcom = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxTroca = new javax.swing.JCheckBox();
        menuBar = new javax.swing.JPanel();
        btnSalvarMesa = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JPanel();
        btnLixeira = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        jCheckBoxTudo = new javax.swing.JCheckBox();
        txtIdNovoGarcom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/logoMesa.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Mesas");

        txtIdGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdGarcomActionPerformed(evt);
            }
        });

        txtIdMesa.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        comboGarcom.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        comboGarcom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboGarcomItemStateChanged(evt);
            }
        });
        comboGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGarcomActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(52, 73, 94));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Garçon Responsável");

        jLabel13.setBackground(new java.awt.Color(52, 73, 94));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("N. Mesa");

        txtNumeroMesa.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        txtNumeroMesa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroMesaKeyPressed(evt);
            }
        });

        panelTroca.setBackground(new java.awt.Color(52, 73, 94));

        comboNovoGarcom.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/troca.png"))); // NOI18N
        jLabel3.setText("Troca Geral");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Novo Garçom");

        javax.swing.GroupLayout panelTrocaLayout = new javax.swing.GroupLayout(panelTroca);
        panelTroca.setLayout(panelTrocaLayout);
        panelTrocaLayout.setHorizontalGroup(
            panelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrocaLayout.createSequentialGroup()
                .addGroup(panelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNovoGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelTrocaLayout.setVerticalGroup(
            panelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrocaLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(comboNovoGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jCheckBoxTroca.setBackground(new java.awt.Color(52, 73, 94));
        jCheckBoxTroca.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jCheckBoxTroca.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTroca.setText("Troca Mesa Garçom");
        jCheckBoxTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTrocaMouseClicked(evt);
            }
        });
        jCheckBoxTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTrocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdGarcom, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(txtIdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(comboGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxTroca))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIdGarcom, txtIdMesa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtIdGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtIdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(5, 5, 5)
                        .addComponent(comboGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxTroca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 524);

        btnSalvarMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMesaMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/SalvarMesas.png"))); // NOI18N
        jLabel16.setText("Salvar");
        btnSalvarMesa.add(jLabel16);

        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        btnLixeira.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnLixeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Lixeira.png"))); // NOI18N
        btnLixeira.setText("Excluir");
        btnExcluir.add(btnLixeira);

        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/lapis.png"))); // NOI18N
        jLabel17.setText("Alterar");
        btnAlterar.add(jLabel17);

        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/limparCinza.png"))); // NOI18N
        jLabel18.setText("Limpar");

        javax.swing.GroupLayout btnLimparLayout = new javax.swing.GroupLayout(btnLimpar);
        btnLimpar.setLayout(btnLimparLayout);
        btnLimparLayout.setHorizontalGroup(
            btnLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimparLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        btnLimparLayout.setVerticalGroup(
            btnLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvarMesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
            .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(menuBar);
        menuBar.setBounds(470, 460, 450, 58);

        tblMesas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "N. da Mesa", "Garçom Responsável", "Status"
            }
        ));
        tblMesas.setRowHeight(22);
        tblMesas.setShowHorizontalLines(false);
        tblMesas.setShowVerticalLines(false);
        tblMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMesasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMesas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 100, 550, 350);

        jCheckBoxTudo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jCheckBoxTudo.setText("Tudo");
        jCheckBoxTudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTudoMouseClicked(evt);
            }
        });
        getContentPane().add(jCheckBoxTudo);
        jCheckBoxTudo.setBounds(390, 60, 130, 33);
        getContentPane().add(txtIdNovoGarcom);
        txtIdNovoGarcom.setBounds(460, 30, 70, 29);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Cargo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(670, 40, 60, 16);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Operador");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 20, 60, 16);

        lblOperador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblOperador.setText("Operador");
        getContentPane().add(lblOperador);
        lblOperador.setBounds(730, 20, 60, 16);

        lblCargo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblCargo.setText("Cargo");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(730, 40, 60, 16);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(910, 0, 40, 40);

        setSize(new java.awt.Dimension(947, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboGarcomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboGarcomItemStateChanged

    }//GEN-LAST:event_comboGarcomItemStateChanged

    private void comboGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGarcomActionPerformed
        tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), filtro)));
    }//GEN-LAST:event_comboGarcomActionPerformed

    private void btnSalvarMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMesaMouseClicked

        // Localiza id do funcionário
        String nome = comboGarcom.getSelectedItem().toString();
        txtIdGarcom.setText(f.localizaId(nome));

        // Salva funcionário no banco
        m.setId_funcionario(txtIdGarcom.getText());
        m.setNumeroMesa(txtNumeroMesa.getText());
        m.setStatus("0");

        int op = JOptionPane.showConfirmDialog(null, "Salvar Mesa", "Incluir mesa?", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        // Solicita confirmação do Usuário
        if (op == JOptionPane.YES_OPTION) {
                // Registro de Log
                log.setFuncionalidade("Salvar");
                log.setDescricao(log.getUsuario() + " salvou uma mesa -> " + m.getNumeroMesa());
                log.gravaLog(log);
                //Fim do registro de log

            if (cm.adicionaMesa(m)) { // Adiciona mesa
                JOptionPane.showMessageDialog(null, "Mesa salva com sucesso!");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada");
        }
        tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), filtro)));
        txtNumeroMesa.setText(null);
    }//GEN-LAST:event_btnSalvarMesaMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // Exclui Mesam
        m.setId(txtIdMesa.getText());

        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esta mesa?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

        if (op == JOptionPane.YES_OPTION) {
            
            // Inicio do registro de Log
            log.setFuncionalidade("Excluir");
            log.setDescricao(log.getUsuario() + " excluiu a mesa " + txtNumeroMesa.getText());
            log.gravaLog(log);
            // Fim do registro de LOG
            
            if (cm.excluiMesa(m)) {
                JOptionPane.showMessageDialog(null, "Mesa Excluída com sucesso");
                tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), filtro)));
                limpaForm();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada com sucesso!");

        }

    }//GEN-LAST:event_btnExcluirMouseClicked

    private void limpaForm() {
        txtIdGarcom.setText(null);
        txtNumeroMesa.setText(null);
        txtIdMesa.setText(null);
    }
    private void txtIdGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdGarcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdGarcomActionPerformed

    private void tblMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMesasMouseClicked
        if (jCheckBoxTroca.isSelected()) {

            txtIdNovoGarcom.setText(f.localizaId(comboNovoGarcom.getSelectedItem().toString()));
        } 

        selecionaIdMesa();
    }//GEN-LAST:event_tblMesasMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // Fehcajanela
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        limparMesa();
    }//GEN-LAST:event_btnLimparMouseClicked

    private void txtNumeroMesaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroMesaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Localiza id do funcionário
            String nome = comboGarcom.getSelectedItem().toString();
            txtIdGarcom.setText(f.localizaId(nome));

            // Salva funcionário no banco
            m.setId_funcionario(txtIdGarcom.getText());
            m.setNumeroMesa(txtNumeroMesa.getText());
            m.setStatus("0");

            int op = JOptionPane.showConfirmDialog(null, "Salvar Mesa", "Incluir mesa?", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            // Solicita confirmação do Usuário
            if (op == JOptionPane.YES_OPTION) {

                if (cm.adicionaMesa(m)) { // Adiciona mesa
                    JOptionPane.showMessageDialog(null, "Mesa salva com sucesso!");

                }
            } else {
                JOptionPane.showMessageDialog(null, "Operação cancelada");
            }
            tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), filtro)));
            txtNumeroMesa.setText(null);
        }


    }//GEN-LAST:event_txtNumeroMesaKeyPressed

    private void jCheckBoxTudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTudoMouseClicked

        // Exibe todas as mesas de todos os garçom
        if ("Tudo" == jCheckBoxTudo.getText()) {
            jCheckBoxTudo.setText("Retornar");
            filtro = true;
            tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), filtro)));
        } else {
            jCheckBoxTudo.setText("Tudo");
            tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), false)));
        }


    }//GEN-LAST:event_jCheckBoxTudoMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // Altera Mesa

        Mesa mesa = new Mesa();
        mesa.setId(txtIdMesa.getText());
        mesa.setNumeroMesa(txtNumeroMesa.getText());
        mesa.setStatus("0");
        mesa.setId_funcionario(txtIdNovoGarcom.getText());

        int op = JOptionPane.showConfirmDialog(null, "Confirma a alteração desta Mesa?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
           // Inicio do registro de log
              log.setFuncionalidade("Alterar");
              log.setDescricao(log.getUsuario() + " alterou dados da mesa -> " + txtNumeroMesa.getText()
                      + ": " + comboGarcom.getSelectedItem().toString() + " -> " + comboNovoGarcom.getSelectedItem().toString() );
              log.gravaLog(log);
           // Fim do registro de LOG
        if (op == JOptionPane.YES_OPTION) {
  
            if (cm.alteraMesa(mesa)) {
                JOptionPane.showMessageDialog(null, "Mesa Alterada!");
                tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), true)));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Alteração Cancelada!");
        }

    }//GEN-LAST:event_btnAlterarMouseClicked

    private void jCheckBoxTrocaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTrocaMouseClicked
        //Exibe painel de Troca
        if (jCheckBoxTroca.isSelected()) {
            panelTroca.setVisible(true);
            f.carregaComboFuncionario(comboNovoGarcom, "Garçom");
        }
    }//GEN-LAST:event_jCheckBoxTrocaMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // Troca garçom
        txtIdNovoGarcom.setText(f.localizaId(comboNovoGarcom.getSelectedItem().toString()));

        txtIdGarcom.setText(f.localizaId(comboGarcom.getSelectedItem().toString()));
        txtIdNovoGarcom.setText(f.localizaId(comboNovoGarcom.getSelectedItem().toString()));

        Funcionario novo = new Funcionario();
        Funcionario antigo = new Funcionario();

        novo.setId(txtIdNovoGarcom.getText());
        novo.setNome(comboNovoGarcom.getSelectedItem().toString());
        antigo.setId(txtIdGarcom.getText());
        antigo.setNome(comboGarcom.getSelectedItem().toString());

        int op = JOptionPane.showConfirmDialog(null, "Confirma a troca de Garçom? \n " + antigo.getNome() + " -> " + novo.getNome(), "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

        if (op == JOptionPane.YES_OPTION) {

            if (txtIdGarcom.getText().equals(txtIdNovoGarcom.getText())) {
                JOptionPane.showMessageDialog(null, "Escolha um garçom diferente para continuar");
            } else {

                if (cm.trocaGarcom(antigo, novo)) {
                    JOptionPane.showMessageDialog(null, "Troca realizada com sucesso!");
                    tblMesas.setModel(DbUtils.resultSetToTableModel(cm.listaMesa(comboGarcom.getSelectedItem().toString(), true)));
                } else {
                    JOptionPane.showMessageDialog(null, "Troca cancelada!");

                }
            }
        }


    }//GEN-LAST:event_jLabel3MouseClicked

    private void jCheckBoxTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTrocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTrocaActionPerformed

    private void selecionaIdMesa() {
        // Seleciona o id da mesa
        int linha = tblMesas.getSelectedRow();
        txtIdMesa.setText(tblMesas.getModel().getValueAt(linha, 0).toString());
        txtNumeroMesa.setText(tblMesas.getModel().getValueAt(linha, 2).toString());
        String nomeFuncionario = tblMesas.getModel().getValueAt(linha, 1).toString(); // Seleciona nome do funcionário

        txtIdGarcom.setText(f.localizaId(nomeFuncionario));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDeMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAlterar;
    private javax.swing.JPanel btnExcluir;
    private javax.swing.JPanel btnLimpar;
    private javax.swing.JLabel btnLixeira;
    private javax.swing.JPanel btnSalvarMesa;
    private javax.swing.JComboBox<String> comboGarcom;
    private javax.swing.JComboBox<String> comboNovoGarcom;
    private javax.swing.JCheckBox jCheckBoxTroca;
    private javax.swing.JCheckBox jCheckBoxTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel panelTroca;
    private javax.swing.JTable tblMesas;
    private javax.swing.JTextField txtIdGarcom;
    private javax.swing.JTextField txtIdMesa;
    private javax.swing.JTextField txtIdNovoGarcom;
    private javax.swing.JTextField txtNumeroMesa;
    // End of variables declaration//GEN-END:variables

    private void limparMesa() {
        txtIdMesa.setText(null);
        txtIdGarcom.setText(null);
        txtNumeroMesa.setText(null);

    }
}
