/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.ConexaoBd;
import br.com.bar.dao.Log;
import br.com.bar.model.Contas;
import br.com.br.controler.ControlerContasApagar;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerGrupo;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author elias
 */
public class TelaContasApagar extends javax.swing.JFrame {

    /**
     * Creates new form TelaContasApagar
     */
    ControlerContasApagar cc = new ControlerContasApagar();
    ControlerFuncionario cf = new ControlerFuncionario();
    ControlerGrupo grupo = new ControlerGrupo();

    SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
    Connection conexao = ConexaoBd.conector();

    // Instacia um registro de log
    Log l = new Log();

    public TelaContasApagar() {
        initComponents();

        txtIdConta.setVisible(false);
        txtIdFuncionario.setVisible(false);
        txtIdGrupo.setVisible(false);
        jdateChooserPagamento.setVisible(false);
        lblDataDePAgamento.setVisible(false);
        txtValorPago.setVisible(false);
        btnBaixar.setVisible(false);
        lblValorPago.setVisible(false);
        cc.listaGrupos(comboGrupoDespesas);
        txtIdGrupo.setText(grupo.localizaIdGrupo(comboGrupoDespesas));
        combofunc.setVisible(false);
        jSpinQtd.setVisible(false);
    }

    public void recebeOperador(String operador, String cargo) {

        lblCargo.setText(cargo);
        lblOperador.setText(operador);
        txtIdFuncionario.setText(cf.localizaIdLogin(operador));
        l.setUsuario(operador);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelEsquerdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblValorPago = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboGrupoDespesas = new javax.swing.JComboBox<>();
        lblDataDePAgamento = new javax.swing.JLabel();
        jdateChooserVencimento = new com.toedter.calendar.JDateChooser();
        jdateChooserPagamento = new com.toedter.calendar.JDateChooser();
        txtIdConta = new javax.swing.JTextField();
        combofunc = new javax.swing.JComboBox<>();
        jCheckMultiplo = new javax.swing.JCheckBox();
        jSpinQtd = new com.toedter.components.JSpinField();
        painelDireito = new javax.swing.JPanel();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdFuncionario = new javax.swing.JTextField();
        Menu = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnSalvar1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnBaixar = new javax.swing.JLabel();
        btnGraficoDeDespesas = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        checkEmAberto = new javax.swing.JCheckBox();
        checkPagas = new javax.swing.JCheckBox();
        checkTudo = new javax.swing.JCheckBox();
        txtIdGrupo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tbnFechar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        painelEsquerdo.setBackground(new java.awt.Color(52, 73, 94));
        painelEsquerdo.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/CalendarioCinzaClaro.png"))); // NOI18N
        painelEsquerdo.add(jLabel1);
        jLabel1.setBounds(100, 10, 128, 100);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contas a Pagar");
        painelEsquerdo.add(jLabel2);
        jLabel2.setBounds(30, 100, 307, 64);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descrição");
        painelEsquerdo.add(jLabel6);
        jLabel6.setBounds(20, 170, 110, 20);

        txtDescricao.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });
        painelEsquerdo.add(txtDescricao);
        txtDescricao.setBounds(20, 200, 320, 40);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor");
        painelEsquerdo.add(jLabel5);
        jLabel5.setBounds(190, 330, 70, 30);

        txtValor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });
        painelEsquerdo.add(txtValor);
        txtValor.setBounds(190, 360, 150, 40);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data de Vencimento");
        painelEsquerdo.add(jLabel8);
        jLabel8.setBounds(20, 250, 170, 30);

        lblValorPago.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblValorPago.setForeground(new java.awt.Color(255, 255, 255));
        lblValorPago.setText("Valor  Pago");
        painelEsquerdo.add(lblValorPago);
        lblValorPago.setBounds(20, 410, 170, 30);

        txtValorPago.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorPagoKeyReleased(evt);
            }
        });
        painelEsquerdo.add(txtValorPago);
        txtValorPago.setBounds(20, 450, 130, 40);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Grupo de Despesas");
        painelEsquerdo.add(jLabel7);
        jLabel7.setBounds(20, 330, 150, 30);

        comboGrupoDespesas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        comboGrupoDespesas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboGrupoDespesasItemStateChanged(evt);
            }
        });
        comboGrupoDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGrupoDespesasActionPerformed(evt);
            }
        });
        painelEsquerdo.add(comboGrupoDespesas);
        comboGrupoDespesas.setBounds(20, 360, 150, 40);

        lblDataDePAgamento.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblDataDePAgamento.setForeground(new java.awt.Color(255, 255, 255));
        lblDataDePAgamento.setText("Data de Pagamento");
        painelEsquerdo.add(lblDataDePAgamento);
        lblDataDePAgamento.setBounds(190, 250, 170, 30);
        painelEsquerdo.add(jdateChooserVencimento);
        jdateChooserVencimento.setBounds(20, 280, 150, 40);
        painelEsquerdo.add(jdateChooserPagamento);
        jdateChooserPagamento.setBounds(190, 280, 150, 40);
        painelEsquerdo.add(txtIdConta);
        txtIdConta.setBounds(280, 20, 50, 30);

        combofunc.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        painelEsquerdo.add(combofunc);
        combofunc.setBounds(160, 450, 180, 40);

        jCheckMultiplo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jCheckMultiplo.setForeground(new java.awt.Color(255, 255, 255));
        jCheckMultiplo.setText("Lançamento Multiplo");
        jCheckMultiplo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckMultiploMouseClicked(evt);
            }
        });
        painelEsquerdo.add(jCheckMultiplo);
        jCheckMultiplo.setBounds(120, 170, 160, 24);
        painelEsquerdo.add(jSpinQtd);
        jSpinQtd.setBounds(190, 280, 150, 40);

        getContentPane().add(painelEsquerdo);
        painelEsquerdo.setBounds(0, 0, 360, 520);

        painelDireito.setBackground(new java.awt.Color(204, 204, 204));
        painelDireito.setLayout(null);

        lblOperador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        painelDireito.add(lblOperador);
        lblOperador.setBounds(430, 10, 130, 20);

        lblCargo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblCargo.setText("Cargo");
        painelDireito.add(lblCargo);
        lblCargo.setBounds(430, 30, 100, 20);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Data");
        painelDireito.add(jLabel3);
        jLabel3.setBounds(430, 50, 80, 16);
        painelDireito.add(txtIdFuncionario);
        txtIdFuncionario.setBounds(10, 20, 40, 30);

        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/SalvarMesas.png"))); // NOI18N
        jLabel10.setText("Salvar");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalvarLayout = new javax.swing.GroupLayout(btnSalvar);
        btnSalvar.setLayout(btnSalvarLayout);
        btnSalvarLayout.setHorizontalGroup(
            btnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSalvarLayout.setVerticalGroup(
            btnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalvarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(25, 25, 25))
        );

        btnSalvar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvar1MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/limparCinza.png"))); // NOI18N
        jLabel15.setText("Limpar");

        javax.swing.GroupLayout btnSalvar1Layout = new javax.swing.GroupLayout(btnSalvar1);
        btnSalvar1.setLayout(btnSalvar1Layout);
        btnSalvar1Layout.setHorizontalGroup(
            btnSalvar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalvar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSalvar1Layout.setVerticalGroup(
            btnSalvar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalvar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Lixeira.png"))); // NOI18N
        jLabel12.setText("Excluir");

        javax.swing.GroupLayout btnExcluirLayout = new javax.swing.GroupLayout(btnExcluir);
        btnExcluir.setLayout(btnExcluirLayout);
        btnExcluirLayout.setHorizontalGroup(
            btnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnExcluirLayout.setVerticalGroup(
            btnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnBaixar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnBaixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btnbaixar-48.png"))); // NOI18N
        btnBaixar.setText("Baixar");
        btnBaixar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaixarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBaixarMouseEntered(evt);
            }
        });

        btnGraficoDeDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btngrafico2-48.png"))); // NOI18N
        btnGraficoDeDespesas.setText("Gráfico");
        btnGraficoDeDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraficoDeDespesasMouseClicked(evt);
            }
        });

        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/lapis.png"))); // NOI18N
        jLabel13.setText("Alterar");

        javax.swing.GroupLayout btnAlterarLayout = new javax.swing.GroupLayout(btnAlterar);
        btnAlterar.setLayout(btnAlterarLayout);
        btnAlterarLayout.setHorizontalGroup(
            btnAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlterarLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        btnAlterarLayout.setVerticalGroup(
            btnAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficoDeDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnGraficoDeDespesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(btnBaixar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnExcluir, btnSalvar, btnSalvar1});

        painelDireito.add(Menu);
        Menu.setBounds(0, 440, 620, 80);

        tblContas.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblContas.setRowHeight(22);
        tblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContas);

        painelDireito.add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 610, 360);

        checkEmAberto.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(checkEmAberto);
        checkEmAberto.setText("Aberto");
        checkEmAberto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkEmAbertoMouseClicked(evt);
            }
        });
        painelDireito.add(checkEmAberto);
        checkEmAberto.setBounds(280, 20, 81, 23);

        checkPagas.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(checkPagas);
        checkPagas.setText("Pagas");
        checkPagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkPagasMouseClicked(evt);
            }
        });
        painelDireito.add(checkPagas);
        checkPagas.setBounds(220, 20, 70, 23);

        checkTudo.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(checkTudo);
        checkTudo.setText("Tudo");
        checkTudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTudoMouseClicked(evt);
            }
        });
        checkTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTudoActionPerformed(evt);
            }
        });
        painelDireito.add(checkTudo);
        checkTudo.setBounds(150, 20, 70, 23);
        painelDireito.add(txtIdGrupo);
        txtIdGrupo.setBounds(60, 20, 40, 30);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        tbnFechar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tbnFechar.setForeground(new java.awt.Color(255, 255, 255));
        tbnFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbnFechar.setText("x");
        tbnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(tbnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDireito.add(jPanel1);
        jPanel1.setBounds(570, -10, 50, 50);

        getContentPane().add(painelDireito);
        painelDireito.setBounds(360, 0, 620, 520);

        setSize(new java.awt.Dimension(975, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        //Cadastra Conta

        Contas c = new Contas();

        c.setDescricao(txtDescricao.getText());
        c.setDataVencto(cc.myData(jdateChooserVencimento));
        c.setValor(txtValor.getText());
        c.setGrupoId(txtIdGrupo.getText());
        c.setFuncionarioId(txtIdFuncionario.getText());
        // Verifica se a conta Existe
        if (cc.existeConta(txtIdConta.getText())) {
            

        } else {
            
           if (jCheckMultiplo.isSelected()){
               if (cc.lancamentoMultiplo(jSpinQtd.getValue(), jdateChooserVencimento, c)){
                    JOptionPane.showMessageDialog(null, "Lançamento múltiplo realiado com sucesso!");
                    tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Aberto")));
               }
                          
           }else {
               // Caso o checkList não esteja selecionado executa a parcela de forma padrão
               
               if (cc.adicionaConta(c)) {
                   //Registra operação no log
                   l.setFuncionalidade("Salvar");
                   l.setDescricao(l.getUsuario() + " adicionou uma nova conta ->" + txtDescricao.getText());
                   l.gravaLog(l);
                   // fim do registro de log
                   limpaForm();
                   JOptionPane.showMessageDialog(null, "Cadasto Relizado com sucesso!");
                   String opcao = checkEmAberto.getText();
                   tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar(opcao)));
               }
           }

        }


    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnSalvar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar1MouseClicked
        limpaForm();
        txtIdConta.setText(null);
        lblDataDePAgamento.setVisible(false);
        jdateChooserPagamento.setVisible(false);
        lblValorPago.setVisible(false);
        txtValorPago.setVisible(false);
        combofunc.setVisible(false);


    }//GEN-LAST:event_btnSalvar1MouseClicked

    private void tbnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnFecharMouseClicked
        // Fecha tela principal
        this.dispose();
    }//GEN-LAST:event_tbnFecharMouseClicked

    private void checkPagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkPagasMouseClicked
        // Lista todas as contas pagas
        String opcao = checkPagas.getText();
        tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar(opcao)));
    }//GEN-LAST:event_checkPagasMouseClicked

    private void checkEmAbertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkEmAbertoMouseClicked
        // Lista todas as contas emaberto
        String opcao = checkEmAberto.getText();
        tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar(opcao)));
    }//GEN-LAST:event_checkEmAbertoMouseClicked

    private void checkTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTudoActionPerformed

    private void checkTudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTudoMouseClicked
        // Exibe todos os registros
        tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar(checkTudo.getText())));
    }//GEN-LAST:event_checkTudoMouseClicked

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        // Substitui virgula por ponto ao digitar
        String valorAntigo = txtValor.getText();
        String valorNovo = valorAntigo.replaceAll(",", ".");
        txtValor.setText(valorNovo);
    }//GEN-LAST:event_txtValorKeyReleased

    private void txtValorPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPagoKeyReleased
        // Substitui virgula por ponto ao digitar
        String valorAntigo = txtValorPago.getText();
        String valorNovo = valorAntigo.replaceAll(",", ".");
        txtValorPago.setText(valorNovo);
    }//GEN-LAST:event_txtValorPagoKeyReleased

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        // Foca combo Grupo de Despesas ao pressionar enter

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            comboGrupoDespesas.requestFocus();
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void comboGrupoDespesasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboGrupoDespesasItemStateChanged

    }//GEN-LAST:event_comboGrupoDespesasItemStateChanged

    private void comboGrupoDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGrupoDespesasActionPerformed

        txtIdGrupo.setText(grupo.localizaIdGrupo(comboGrupoDespesas));
        String operador = lblOperador.getText();


    }//GEN-LAST:event_comboGrupoDespesasActionPerformed

    private void tblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContasMouseClicked

        // Data Atual
        Date dataAtual = new Date();

        // Seleciona dados da tabela
        Contas c = new Contas();
        c.setId(txtIdConta.getText());
        c.setDataPagto(null);
        c.setValoPagto(null);
        c.setDescricao(txtDescricao.getText());

        int linha = tblContas.getSelectedRow();
        txtIdConta.setText(tblContas.getModel().getValueAt(linha, 0).toString());
        txtDescricao.setText(tblContas.getModel().getValueAt(linha, 1).toString());
        String dataPagamento;
        String dataVencimento = tblContas.getModel().getValueAt(linha, 3).toString();
        String tipo = tblContas.getModel().getValueAt(linha, 7).toString();

        if ("Comissão".equals(tipo)) {
            combofunc.setVisible(true);
            cf.carregaComboFuncionario(combofunc, "Garçom");
        } else {
            combofunc.setVisible(false);
        }
        // Seta data no jdateschooser
        try {

            jdateChooserVencimento.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(dataVencimento));

        } catch (ParseException ex) {

        }

        // Captura excessão quando se seleciona uma conta cadastrada na tabela.
        try {

            dataPagamento = tblContas.getModel().getValueAt(linha, 4).toString();

            jdateChooserPagamento.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(dataPagamento));

        } catch (ParseException e) {

        } catch (NullPointerException n) {
            // Caso o valor seja nulo exibe os campos para pagamento
            lblDataDePAgamento.setVisible(true);
            jdateChooserPagamento.setVisible(true);
            //jdateChooserPagamento.setDate(null);
            //jdateChooserPagamento.setDate(dataAtual);
            lblValorPago.setVisible(true);
            txtValorPago.setVisible(true);
            btnBaixar.setVisible(true);
            txtValorPago.setText(tblContas.getModel().getValueAt(linha, 2).toString());

        }

        txtValor.setText(tblContas.getModel().getValueAt(linha, 2).toString());
        txtValorPago.setText(tblContas.getModel().getValueAt(linha, 2).toString());

        try {

            if (evt.getButton() == MouseEvent.BUTTON3) {
                JPopupMenu menuPopup = cc.menu(c);
                menuPopup.show(tblContas, evt.getX(), evt.getY());
                limpaForm();

            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_tblContasMouseClicked

    private void btnBaixarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaixarMouseClicked
        // Baixa Conta
        Contas c = new Contas();

        c.setId(txtIdConta.getText());
        c.setDataPagto(cc.myData(jdateChooserPagamento));
        c.setValoPagto(txtValorPago.getText());
        c.setOperador(lblOperador.getText());

        if (c.getDataPagto().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a data de pagamento para continuar!");
        } else {

            if (c.getId() == null) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar...");
            } else if (c.getDataPagto() == null) {
                JOptionPane.showMessageDialog(null, "Informe a data de Pagamento");
            } else {
                int op = JOptionPane.showConfirmDialog(null, "Confirma a baixa desta conta?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

                if (op == JOptionPane.YES_OPTION) {
                    if (cc.baixarConta(c)) {
                        // Registra operação no log
                        l.setFuncionalidade("Pagamento");
                        l.setDescricao(l.getUsuario() + " pagou a conta " + txtDescricao.getText() + "-> R$ " + txtValor.getText() + "Vencimento: "
                                + df.format(jdateChooserVencimento.getCalendar().getTime()) + ": Pagamento" + df.format(jdateChooserVencimento.getCalendar().getTime()));
                        l.gravaLog(l);
                        // fim do registro de log

                        JOptionPane.showMessageDialog(null, "Baixa realizada com sucesso!");
                        limpaForm();
                        tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Aberto")));
                        // Fim do registro de log

                        int confirma = JOptionPane.showConfirmDialog(null, "Deseja Imprimir comprovante?", "Aenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                        if (confirma == JOptionPane.YES_OPTION) {
                            HashMap parametros = new HashMap();
                            parametros.put("titulo", "====== RECIBO DE PAGAMENTO ========= ");

                            /* Caso o valor a ser pago seja uma comissão o parâmetro a ser setado será o nome do funcionário que consta no combo
                        funcionario caso ele estejá visível
                             */
                            if (combofunc.isVisible()) {

                                parametros.put("funcionario", combofunc.getSelectedItem().toString());
                            } else {
                                parametros.put("funcionario", lblOperador.getText());
                            }

                            parametros.put("id", Integer.parseInt(txtIdConta.getText()));

                            try {
                                JasperPrint print = JasperFillManager.fillReport("C:/SysBar/rel/reciboDePagamento.jasper", parametros, conexao);
                                JasperViewer.viewReport(print, false);
                                combofunc.setVisible(false);

                            } catch (JRException ex) {
                                System.out.println("br.com.bar.view.TelaContasApagar.btnBaixarMouseClicked()");
                            }

                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Operação Cancelada!");
                        combofunc.setVisible(false);

                    }

                }
            }
        }


    }//GEN-LAST:event_btnBaixarMouseClicked

    private void btnBaixarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaixarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaixarMouseEntered

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        //Eclui conta
        Contas c = new Contas();
        c.setId(txtIdConta.getText());
        c.setDataPagto(cc.myData(jdateChooserPagamento));

        if (c.getDataPagto().isEmpty()) {

            if (c.getId().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione uma conta para continuar!");
            } else {
                // Registra operação no log
                l.setFuncionalidade("Excluir");
                l.setDescricao(l.getUsuario() + " excluiu a conta ->" + txtDescricao.getText() + " Vencimento: " + df.format(jdateChooserVencimento.getCalendar().getTime()) + " Valor R$ " + txtValor.getText());
                l.gravaLog(l);
                // Fim registro de log
                cc.excluiConta(c);
                tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Tudo")));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Contas Pagas não podem ser excluída!");
            limpaForm();

        }


    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // Altera apenas contas em aberto
        Contas c = new Contas();
        c.setDescricao(txtDescricao.getText());
        c.setDataVencto(cc.myData(jdateChooserVencimento));
        c.setGrupoId(txtIdGrupo.getText());
        c.setValor(txtValor.getText());
        c.setId(txtIdConta.getText());
        c.setDataPagto(cc.myData(jdateChooserPagamento));

        if ("".equals(c.getDataPagto())) {

            if (cc.alteraConta(c)) {

                JOptionPane.showMessageDialog(null, "Conta alterada!");
                tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Aberto")));
                limpaForm();
                //Regisra operação no log
                l.setFuncionalidade("Alterar");
                l.setDescricao(l.getUsuario() + " alterou a conta ->" + c.getDescricao() + " Data de Vencimento: " + c.getDataVencto());
                l.gravaLog(l);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Contas pagas não podem ser alteradas!");

        }


    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnGraficoDeDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficoDeDespesasMouseClicked
        // Gera gráfico de pizza das Despesas 
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        ResultSet rs = cc.listaContasPorCategoria();

        //Captura dados da consulta
        try {
            while (rs.next()) {
                pieDataset.setValue(rs.getString("grupo"), rs.getDouble("valor"));

            }
        } catch (SQLException e) {
            System.out.println("Erro ao preencher pierDataSet" + e);
        }
        // Cria Gráfico de Pizza

        JFreeChart graficoPizza = ChartFactory.createPieChart3D("Demonstrativo de Despesas", pieDataset, true, true, true);
        // Plotagem

        PiePlot piePlot = (PiePlot) graficoPizza.getPlot();

        // Janela do Grafico
        ChartFrame frame = new ChartFrame("Gráfico - Demonstrativo de Despesas", graficoPizza);
        frame.setSize(947, 524);
        frame.setVisible(true);

    }//GEN-LAST:event_btnGraficoDeDespesasMouseClicked

    private void jCheckMultiploMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckMultiploMouseClicked
        // Exibe caixa quantidade
        if (jCheckMultiplo.isSelected()) {
            jSpinQtd.setVisible(true);
        } else {
            jSpinQtd.setVisible(false);
        }
    }//GEN-LAST:event_jCheckMultiploMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContasApagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContasApagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContasApagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContasApagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContasApagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel btnAlterar;
    private javax.swing.JLabel btnBaixar;
    private javax.swing.JPanel btnExcluir;
    private javax.swing.JLabel btnGraficoDeDespesas;
    private javax.swing.JPanel btnSalvar;
    private javax.swing.JPanel btnSalvar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkEmAberto;
    private javax.swing.JCheckBox checkPagas;
    private javax.swing.JCheckBox checkTudo;
    private javax.swing.JComboBox<String> comboGrupoDespesas;
    private javax.swing.JComboBox<String> combofunc;
    private javax.swing.JCheckBox jCheckMultiplo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinQtd;
    private com.toedter.calendar.JDateChooser jdateChooserPagamento;
    private com.toedter.calendar.JDateChooser jdateChooserVencimento;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDataDePAgamento;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JPanel painelDireito;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JTable tblContas;
    private javax.swing.JLabel tbnFechar;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdConta;
    private javax.swing.JTextField txtIdFuncionario;
    private javax.swing.JTextField txtIdGrupo;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables

    private void limpaForm() {
        txtDescricao.setText(null);
        txtValor.setText(null);
        txtValorPago.setText(null);
        jdateChooserPagamento.setDate(null);
        jdateChooserVencimento.setDate(null);

    }
}
