/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.AutenticaUsuario;
import br.com.bar.dao.ConexaoBd;
import br.com.bar.dao.Log;
import br.com.bar.model.DadosEmpresa;
import br.com.br.controler.ControlerDadosEmpresa;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerParametro;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import org.codehaus.groovy.tools.shell.util.SimpleCompletor;

/**
 *
 * @author elias
 */
public class TelaLogin extends javax.swing.JFrame {
    Connection conexao=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ControlerDadosEmpresa d = new ControlerDadosEmpresa();
    
    
    Date dataAtual = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat hora = new SimpleDateFormat("h:mm");
    /**
     * Creates new form TelaLogin
     */
    ControlerParametro cp = new ControlerParametro();
    int acumula = 0;

    public TelaLogin() {
        initComponents();

        conexao = ConexaoBd.conector();
       
        if (conexao!=null){
               DadosEmpresa dadosEmpresa = d.selecionaDados();
               lblLicenca.setText("Software licenciado para " + dadosEmpresa.getNome_empresa());
        }else {
            
            TelaPametro param = new TelaPametro();
            param.setAlwaysOnTop(true); // Coloca a janela parêmetro na frente da tela de login
            param.setVisible(true);
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLicenca = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(52, 73, 94));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Identificação do Usuário");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 200, 230, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 20, 160, 190);

        lblVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersao.setText("1.2.4");
        jPanel1.add(lblVersao);
        lblVersao.setBounds(60, 320, 170, 20);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TechSys  ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 360, 240, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Versão");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 300, 170, 20);

        lblLicenca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLicenca.setText("xxxxx");
        jPanel1.add(lblLicenca);
        lblLicenca.setBounds(0, 340, 300, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 430);

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setLayout(null);

        txtLogin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLogin.setBorder(null);
        txtLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLogin.setMargin(null);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });
        jPanel2.add(txtLogin);
        txtLogin.setBounds(50, 180, 250, 40);

        txtSenha.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setBorder(null);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        jPanel2.add(txtSenha);
        txtSenha.setBounds(50, 260, 250, 40);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/login_1.png"))); // NOI18N
        jLabel4.setText("Senha");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 230, 110, 30);

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnLogin.setText("Entrar");
        btnLogin.setBorder(null);
        btnLogin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnLoginAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(50, 320, 250, 40);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SysBar");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 60, 150, 70);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel5.setText("X");
        jPanel3.add(jLabel5);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(290, 0, 30, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario_branco.png"))); // NOI18N
        jLabel6.setText("Login");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 150, 250, 30);

        lblMsg.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblMsg);
        lblMsg.setBounds(50, 370, 250, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(290, 0, 320, 430);

        setSize(new java.awt.Dimension(609, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       realizaLogin();
    }//GEN-LAST:event_btnLoginActionPerformed
    private void realizaLogin(){
        // Cria log
        Log l = new Log();
        
        l.setFuncionalidade("Login");
        l.setUsuario(txtLogin.getText());
        l.setDescricao(l.getUsuario() + " Logou no Sistema");
        

        // Autentica Usuário
        
        ControlerParametro p = new ControlerParametro();
        ControlerFuncionario cf = new ControlerFuncionario();
        AutenticaUsuario autentica = new AutenticaUsuario();

        if (autentica.autentica(txtLogin.getText().toLowerCase(), txtSenha.getText())) {

            String cargo = autentica.enviarCargo();
            String bloqueio = autentica.getBloqueio();
            String status = autentica.getStatus();

            if ("1".equals(bloqueio)) {
                JOptionPane.showMessageDialog(null, "Usuário Bloqueado! \n Procure um administrador!");
                //Início do Registro de Log
                
                l.setFuncionalidade("Acesso Negado");
                l.setDescricao("O usuário "+txtLogin.getText() + " Bloqueado tentou acessar o sistema!");
                l.gravaLog(l);
                // Fim do Registro de Log
                
            } else if ("1".equals(status)) {
                JOptionPane.showMessageDialog(null, "Usuário Inativo! \n Procure um administrador!");
                //Início do Registro de Log
                
                l.setFuncionalidade("Acesso Negado");
                l.setDescricao("O usuário "+txtLogin.getText() + " Inativo tentou acessar o sistema!");
                l.gravaLog(l);
                // Fim do Registro de Log
            } else {
                // Registra acesso do usuário no log
                l.gravaLog(l);
                //
                switch (cargo) {
                    case "Gerente": // Vai para tela principal
                        TelaPrincipal principal = new TelaPrincipal();
                        principal.recebeOperador(autentica.enviaOperador(), autentica.enviarCargo());
                        principal.setVisible(true);
                        this.dispose();
                        break;

                    case "Estoquista": // Vai para tela Estoque
                        TelaEstoque estoque = new TelaEstoque();
                        estoque.recebeOperador(autentica.enviaOperador(), autentica.enviarCargo());
                        estoque.setVisible(true);
                        this.dispose();
                        break;
                    case "Garçom": // Vai para tela Estoque
                        TelaPedido pedido = new TelaPedido();
                        pedido.recebeOperador(autentica.enviaOperador(), autentica.enviarCargo());
                        pedido.setVisible(true);
                        this.dispose();
                        break;
                    case "Caixa": // Vai para tela Estoque
                        TelaCaixa caixa = new TelaCaixa();
                        caixa.recebeOperador(autentica.enviaOperador(), autentica.enviarCargo());
                        caixa.setVisible(true);
                        this.dispose();
                        break;
                    case "Cozinheiro": // Vai para Cozinha
                        TelaConzinha cozinha = new TelaConzinha();
                        cozinha.recebeOperador(autentica.enviaOperador(),autentica.enviarCargo());
                        cozinha.setVisible(true);
                        this.dispose();
                        break;
                }
            }

        } else {
            int contagem = contador();
            int tentavias = 3 - contagem;
            if (contagem >= 3) {
                cp.bloqueiaLogin(cf.localizaIdLogin(txtLogin.getText()));
                //Início do Registro de Log
                l.setFuncionalidade("Acesso Negado");
                l.setDescricao("O usuário "+txtLogin.getText() + " por motivos de segurança foi bloqueado");
                l.gravaLog(l);
                // Fim do Registro de Log
            } else {
                //JOptionPane.showMessageDialog(null, "Restam " + tentavias + " tentativas \n Antes do bloqueio!");
                lblMsg.setForeground(Color.white);
                lblMsg.setText("Restam " + tentavias + " tentativas \n Antes do bloqueio!");
                //Início do Registro de Log
                
                l.setFuncionalidade("Acesso Negado");
                l.setDescricao(txtLogin.getText() + " tentou acessar o sistema -> " + tentavias + " vezes");
                l.gravaLog(l);
                // Fim do Registro de Log

            }
        }
    }
    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        // Vai para caixa senha
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSenha.requestFocus();
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed

    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        // Realiza login
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            realizaLogin();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // Fecha Janela
        dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnLoginAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLicenca;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private int contador() {
        int contador = 1;
        acumula = acumula + contador;
        System.out.println(acumula);
        return acumula;
    }

}
