/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.Log;
import br.com.bar.model.Cliente;
import br.com.bar.model.Funcionario;
import br.com.bar.model.Localidade;
import br.com.bar.util.ClienteViaCepWS;
import br.com.bar.util.FormataValor;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerCliente;
import br.com.br.controler.ControlerLodalidade;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
/*
    - public class TelaCadastroFuncionario extends javax.swing.JFrame
    - Teste de Alteração de herança da janela de jFrame para JDialog
 */
public class TelaCadastroCliente extends JDialog {

    ControlerCliente controlCliente = new ControlerCliente();
    ControlerLodalidade cl = new ControlerLodalidade();

    Util u = new Util();
    // Inicia Instância de log
    Log l = new Log();
    String nome = null;

    public TelaCadastroCliente() {
        initComponents();
        txtCaminho.setVisible(false);
        txtId.setVisible(false);
        txtOperacao.setVisible(false);
        //Torna a janela Modal
        this.setModal(true);
        lblPerfil.setVisible(false);
        lblData.setVisible(false);
        lblOperador.setVisible(false);
        cl.carregaComboLocalidade(comboLocalidade);

    }

    public void recebeOperador(String operador, String cargo, String operacao) {
        Date data = new Date();
        lblData.setText(u.formataDataBr(data));

        lblPerfil.setText(cargo);
        lblOperador.setText(operador);
        txtOperacao.setText(operacao);

        if ("Adicionar".equals(txtOperacao.getText())) {
            lblTiulo.setText("Incluir");
            lblSubTitulo.setText("Cliente");

        } else if ("Alterar".equals(txtOperacao.getText())) {
            lblTiulo.setText("Alterar");
            lblSubTitulo.setText("Cliente");

        } else {
            lblTiulo.setText("Consultar");
            lblSubTitulo.setText("Cliente");
            bloqueiaTudo();
        }
        l.setUsuario(operador);

        if ("Adicionar".equals(operacao)) {

        } else {

            bloqueiaCampos();
        }

    }

    public void recebeFuncionario(Funcionario f) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        bordas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCep = new javax.swing.JFormattedTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        comboLocalidade = new javax.swing.JComboBox<>();
        lblLocalidade = new javax.swing.JLabel();
        lbltemMesa = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        comboUf = new javax.swing.JComboBox<>();
        lblCelular = new javax.swing.JLabel();
        txtPontoReferencia = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        lblTaxa = new javax.swing.JLabel();
        lblMoeda = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTiulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCaminho = new javax.swing.JTextField();
        lblOperador = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        txtOperacao = new javax.swing.JTextField();
        jtableGuias = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        btnSalvar3 = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        bordas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        bordas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(null);

        lblNome.setText("Nome *");
        jPanel1.add(lblNome);
        lblNome.setBounds(150, 10, 130, 20);

        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(150, 30, 280, 30);

        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyReleased(evt);
            }
        });
        jPanel1.add(txtEndereco);
        txtEndereco.setBounds(150, 90, 360, 30);

        lblUf.setText("UF");
        jPanel1.add(lblUf);
        lblUf.setBounds(150, 120, 60, 20);

        lblCep.setText("CEP");
        jPanel1.add(lblCep);
        lblCep.setBounds(10, 70, 70, 20);

        lblComplemento.setText("Complemento");
        jPanel1.add(lblComplemento);
        lblComplemento.setBounds(10, 120, 100, 20);

        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroKeyReleased(evt);
            }
        });
        jPanel1.add(txtBairro);
        txtBairro.setBounds(250, 140, 110, 30);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCepKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCepKeyReleased(evt);
            }
        });
        jPanel1.add(txtCep);
        txtCep.setBounds(10, 90, 130, 30);

        lblCidade.setText("Cidade");
        jPanel1.add(lblCidade);
        lblCidade.setBounds(370, 120, 170, 20);

        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCidadeKeyReleased(evt);
            }
        });
        jPanel1.add(txtCidade);
        txtCidade.setBounds(370, 140, 210, 30);

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(10, 190, 260, 30);

        lblEmail.setText("Ponto de Referênica");
        jPanel1.add(lblEmail);
        lblEmail.setBounds(280, 170, 210, 20);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyReleased(evt);
            }
        });
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(440, 30, 140, 30);

        comboLocalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocalidadeActionPerformed(evt);
            }
        });
        jPanel1.add(comboLocalidade);
        comboLocalidade.setBounds(10, 240, 210, 30);

        lblLocalidade.setText("Localidade");
        jPanel1.add(lblLocalidade);
        lblLocalidade.setBounds(10, 220, 110, 20);

        lbltemMesa.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jPanel1.add(lbltemMesa);
        lbltemMesa.setBounds(10, 370, 340, 20);

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });
        jPanel1.add(txtNumero);
        txtNumero.setBounds(520, 90, 60, 30);

        lblEndereco.setText("Endereço*");
        jPanel1.add(lblEndereco);
        lblEndereco.setBounds(150, 70, 90, 20);

        lblNumero.setText("Número*");
        jPanel1.add(lblNumero);
        lblNumero.setBounds(520, 70, 60, 20);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularKeyPressed(evt);
            }
        });
        jPanel1.add(txtCelular);
        txtCelular.setBounds(10, 30, 130, 30);

        lblTelefone.setText("Telefone Fixo");
        jPanel1.add(lblTelefone);
        lblTelefone.setBounds(440, 10, 90, 20);

        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplementoKeyReleased(evt);
            }
        });
        jPanel1.add(txtComplemento);
        txtComplemento.setBounds(10, 140, 130, 30);

        lblBairro.setText("Bairro");
        jPanel1.add(lblBairro);
        lblBairro.setBounds(250, 120, 100, 20);

        comboUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE" }));
        comboUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUfActionPerformed(evt);
            }
        });
        jPanel1.add(comboUf);
        comboUf.setBounds(150, 140, 90, 30);

        lblCelular.setText("Celular*");
        jPanel1.add(lblCelular);
        lblCelular.setBounds(10, 10, 90, 20);

        txtPontoReferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPontoReferenciaMouseClicked(evt);
            }
        });
        txtPontoReferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPontoReferenciaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPontoReferenciaKeyReleased(evt);
            }
        });
        jPanel1.add(txtPontoReferencia);
        txtPontoReferencia.setBounds(280, 190, 300, 30);

        lblEmail1.setText("E-mail");
        jPanel1.add(lblEmail1);
        lblEmail1.setBounds(10, 170, 100, 20);

        lblTaxa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTaxa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTaxa.setText("0,00");
        jPanel1.add(lblTaxa);
        lblTaxa.setBounds(450, 240, 100, 30);

        lblMoeda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMoeda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMoeda.setText("R$");
        jPanel1.add(lblMoeda);
        lblMoeda.setBounds(410, 240, 40, 30);

        bordas.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 101, 585, 280));

        jPanel4.setBackground(new java.awt.Color(243, 156, 18));
        jPanel4.setLayout(null);

        lblTiulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        lblTiulo.setText("Cadastro");
        jPanel4.add(lblTiulo);
        lblTiulo.setBounds(30, 0, 270, 78);

        lblSubTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lblSubTitulo.setText("de Clientes");
        jPanel4.add(lblSubTitulo);
        lblSubTitulo.setBounds(130, 50, 200, 40);
        jPanel4.add(txtId);
        txtId.setBounds(280, 10, 60, 30);
        jPanel4.add(txtCaminho);
        txtCaminho.setBounds(350, 10, 100, 30);

        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblOperador.setText("Operador");
        jPanel4.add(lblOperador);
        lblOperador.setBounds(320, 50, 114, 30);

        lblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblPerfil.setText("Operador");
        jPanel4.add(lblPerfil);
        lblPerfil.setBounds(410, 50, 100, 30);

        jPanel5.setBackground(new java.awt.Color(52, 73, 94));

        lblFechar.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(255, 255, 255));
        lblFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fecharWhite24x24.png"))); // NOI18N
        lblFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(550, 0, 40, 40);

        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/calendario24x24.png"))); // NOI18N
        lblData.setText("Data");
        jPanel4.add(lblData);
        lblData.setBounds(510, 50, 110, 30);
        jPanel4.add(txtOperacao);
        txtOperacao.setBounds(460, 10, 80, 30);

        bordas.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 586, 100));

        jtableGuias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableGuiasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtableGuiasMouseEntered(evt);
            }
        });

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        jScrollPane3.setViewportView(txtHistorico);

        jtableGuias.addTab("Histórico", jScrollPane3);

        bordas.add(jtableGuias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 570, 120));

        btnSalvar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/salvar24x24.png"))); // NOI18N
        btnSalvar3.setText("Salvar");
        btnSalvar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvar3MouseClicked(evt);
            }
        });
        btnSalvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar3ActionPerformed(evt);
            }
        });
        btnSalvar3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnSalvar3KeyReleased(evt);
            }
        });
        bordas.add(btnSalvar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 140, 32));

        lblMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblMsg.setText("jLabel1");
        bordas.add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 570, -1));

        getContentPane().add(bordas);
        bordas.setBounds(0, 0, 587, 567);

        setSize(new java.awt.Dimension(587, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked

        dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void jtableGuiasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableGuiasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableGuiasMouseEntered

    private void jtableGuiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableGuiasMouseClicked

    }//GEN-LAST:event_jtableGuiasMouseClicked

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        // Aceita apenas número
        txtNumero.setText(txtNumero.getText().replaceAll("[^0-9]", ""));
        txtNumero.setText(u.tamanhoMaximo(txtNumero.getText(), 4));
        lblNumero.setForeground(Color.BLACK);
        lblMsg.setText(null);
    }//GEN-LAST:event_txtNumeroKeyReleased

    private void comboUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUfActionPerformed
        // TODO add your handling code here:
        lblUf.setForeground(Color.BLACK);
        lblMsg.setText(null);
    }//GEN-LAST:event_comboUfActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased

    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyReleased
        // Limita tanho do campo ENDEREÇO
        txtEndereco.setText(u.tamanhoMaximo(txtEndereco.getText(), 45));
        lblEndereco.setForeground(Color.BLACK);
        lblMsg.setText(null);
    }//GEN-LAST:event_txtEnderecoKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // Limita tamnho do campo EMAIL
        txtEmail.setText(u.tamanhoMaximo(txtEmail.getText(), 45));
        lblEmail.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTelefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyReleased
        // limita tamanho do campo TELEFONE

    }//GEN-LAST:event_txtTelefoneKeyReleased

    private void txtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyReleased
        // Limita tamanho do campo BAIRRO
        txtBairro.setText(u.tamanhoMaximo(txtBairro.getText(), 35));
        lblBairro.setForeground(Color.black);
        lblMsg.setText(null);
    }//GEN-LAST:event_txtBairroKeyReleased

    private void txtComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyReleased
        // Limita tamanho do cmapo COMPLEMENTO
        txtComplemento.setText(u.tamanhoMaximo(txtComplemento.getText(), 35));
        lblComplemento.setForeground(Color.black);
    }//GEN-LAST:event_txtComplementoKeyReleased

    private void txtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyReleased
        // Limita tamanho do compo CIDADE
        txtCidade.setText(u.tamanhoMaximo(txtCidade.getText(), 40));
        lblCidade.setForeground(Color.black);
    }//GEN-LAST:event_txtCidadeKeyReleased

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMouseClicked

    private void txtCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepKeyReleased
        lblCep.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtCepKeyReleased

    private void txtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyPressed
        lblMsg.setText(null);
        lblCelular.setForeground(Color.BLACK);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_txtCelularKeyPressed

    private void comboLocalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocalidadeActionPerformed
        lblLocalidade.setForeground(Color.BLACK);
        lblMsg.setText(null);

//        if (comboLocalidade.getSelectedIndex()!=0) {
//            FormataValor fv = new FormataValor();
//            
//            Localidade localidade= new Localidade();
//            localidade.setNome(comboLocalidade.getSelectedItem().toString());                    
//            lblTaxa.setText(fv.Formata(String.valueOf(cl.retornaTaxa(localidade))));
//        } else {
//            lblTaxa.setText("0,00");
//        }
  valorEnrega();
       

    }//GEN-LAST:event_comboLocalidadeActionPerformed

    private void txtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepKeyPressed
        // Busca o CEP informado
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER) {
                String cep = txtCep.getText().replace("-", "");
                String json = ClienteViaCepWS.buscarCep(cep);
                Map mapa = ClienteViaCepWS.formataCepWs(json);
                try {
                    txtEndereco.setText(mapa.get("logradouro").toString());
                    txtBairro.setText(mapa.get("bairro").toString());
                    txtCidade.setText(mapa.get("localidade").toString());
                    txtComplemento.setText(mapa.get("complemento").toString());
                    comboUf.setSelectedItem(mapa.get("uf"));
                    txtEmail.requestFocus();
                } catch (NullPointerException e) {

                }
            }
        }
    }//GEN-LAST:event_txtCepKeyPressed

    private void btnSalvar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar3MouseClicked

    private void btnSalvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar3ActionPerformed
        if (valida()) {
            Cliente c = new Cliente();
            // Instancia o objeto localidad e localida o ID da localidade
            Localidade localidade = new Localidade();
            localidade.setNome(comboLocalidade.getSelectedItem().toString());
            localidade.setId(Integer.parseInt(cl.retornaIdLocalidade(localidade)));
            // Seta dados do cliente
            c.setTelefone(txtCelular.getText());
            c.setNome(txtNome.getText());
            c.setTelefone_recado(txtTelefone.getText());
            c.setCep(txtCep.getText());
            c.setEndereco(txtEndereco.getText());
            c.setNumero(txtNumero.getText());
            c.setComplemento(txtComplemento.getText());
            c.setUf(comboUf.getSelectedItem().toString());
            c.setBairro(txtBairro.getText());
            c.setCidade(txtCidade.getText());
            c.setEmail(txtEmail.getText());
            c.setReferencia(txtPontoReferencia.getText());

            // Informa  dados da lodalidade
            c.setLocalidade(localidade);
            c.setHistorico(txtHistorico.getText());
            // Altera dados do cliente
            if ("Alterar".equals(lblTiulo.getText())) {
                int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo alterar os dados do cliente?", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
                if (op == JOptionPane.YES_OPTION) {

                    if (cl.alteraCliente(c)) {
                        JOptionPane.showMessageDialog(this, "Alteração realizada com sucesso!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }
                }
            } else {
                // Adiciona Cliente
                if (controlCliente.adicionaCliente(c)) {
                    JOptionPane.showMessageDialog(this, "Cliente adicionado com sucesso!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                    limpaForm();
                    this.dispose();
                }
            }

        }
    }//GEN-LAST:event_btnSalvar3ActionPerformed

    private void btnSalvar3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvar3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar3KeyReleased

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // Limita tanho do campo NOME
        txtNome.setText(u.tamanhoMaximo(txtNome.getText(), 45));
        lblNome.setForeground(Color.BLACK);
        lblMsg.setText(null);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTelefone.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCep.requestFocus();
        }
    }//GEN-LAST:event_txtTelefoneKeyPressed

    private void txtPontoReferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPontoReferenciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontoReferenciaMouseClicked

    private void txtPontoReferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPontoReferenciaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontoReferenciaKeyPressed

    private void txtPontoReferenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPontoReferenciaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontoReferenciaKeyReleased

    public void limpaForm() {
        // Limpa formulário
        txtId.setText(null);
        txtNome.setText(null);
        txtEndereco.setText(null);
        txtBairro.setText(null);
        txtCep.setText(null);
        txtEmail.setText(null);
        txtTelefone.setText(null);
        txtCidade.setText(null);
        txtComplemento.setText(null);
        txtNumero.setText(null);
        comboUf.setSelectedItem("Selecione...");
        comboLocalidade.setSelectedItem("Selecione...");
        comboLocalidade.setSelectedItem("Cargos");
        txtCaminho.setText(null);
        txtCelular.setText(null);
        txtHistorico.setText(null);
        txtPontoReferencia.setText(null);
    }

    private void bloqueiaTudo() {
        // Limpa formulário
        txtId.setEnabled(false);
        txtNome.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtEmail.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setText(null);
        txtNumero.setEnabled(false);
        txtCaminho.setEnabled(false);
        txtCelular.setEnabled(false);
        comboUf.setEnabled(false);
        comboLocalidade.setEnabled(false);
        comboLocalidade.setEnabled(false);
        txtComplemento.setEnabled(false);

        jtableGuias.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordas;
    private javax.swing.JButton btnSalvar3;
    private javax.swing.JComboBox<String> comboLocalidade;
    private javax.swing.JComboBox<String> comboUf;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jtableGuias;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblLocalidade;
    private javax.swing.JLabel lblMoeda;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTaxa;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTiulo;
    private javax.swing.JLabel lblUf;
    private javax.swing.JLabel lbltemMesa;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCaminho;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOperacao;
    private javax.swing.JTextField txtPontoReferencia;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void bloqueiaCampos() {
        if ("Alterar".equals(txtOperacao.getText())) {
            txtNome.setEnabled(false);

        }

    }

    /* 
       Este método valida os campos do cadastro de Funcioinário retornando um Boolean
       como resposta final.
     */
    public boolean valida() {
        // Seta  resposta padrão com TRUE.
        boolean resp = true;
        if ("(  )     -    ".equals(txtCelular.getText())
                || txtCelular.getText().equals("(00)00000-0000") || txtCelular.getText().equals("(11)11111-1111")
                || txtCelular.getText().equals("(22)22222-2222") || txtCelular.getText().equals("(33)33333-3333")
                || txtCelular.getText().equals("(44)44444-4444") || txtCelular.getText().equals("(55)55555-5555")
                || txtCelular.getText().equals("(66)66666-6666") || txtCelular.getText().equals("(77)77777-7777")
                || txtCelular.getText().equals("(88)88888-8888") || txtCelular.getText().equals("(99)99999-9999")
                || txtCelular.getText().length() != 14) {
            lblMsg.setText("*Informe um número de CELULAR para continuar!");
            txtCelular.requestFocus();
            lblCelular.setForeground(Color.RED);
            resp = false;

            /*
                     else if ("Selecione...".equals(comboLocalidade.getSelectedItem().toString())) {
                    lblMsg.setText("*Informe um Cargo para continuar!");
                    comboLocalidade.requestFocus();
                    lblCargo.setForeground(Color.RED);
                    resp = false;
             */
        } else if ("".equals(txtNome.getText())) {
            lblMsg.setText("*Informe um NOME para continuar!");
            txtNome.requestFocus();
            lblNome.setForeground(Color.red);
            resp = false;
        } else if ("".equals(txtEndereco.getText())) {
            lblMsg.setText("*Informe um ENDEREÇO para continuar!");
            txtEndereco.requestFocus();
            lblEndereco.setForeground(Color.red);
            resp = false;
        } else if ("".equals(txtNumero.getText())) {
            lblMsg.setText("*Informe o NÚMERO para continuar!");
            txtNumero.requestFocus();
            lblNumero.setForeground(Color.red);
            resp = false;
        } else if ("Selecione...".equals(comboLocalidade.getSelectedItem().toString())) {
            lblMsg.setText("*Informe uma LOCALIDADE para continuar!");
            lblLocalidade.setForeground(Color.red);
            comboLocalidade.requestFocus();
            resp = false;
        }
        return resp;
    }

    public void recebeCliente(Cliente c) {
        txtCelular.setText(c.getTelefone());
        txtNome.setText(c.getNome());
        txtTelefone.setText(c.getTelefone_recado());
        txtCep.setText(c.getCep());
        txtEndereco.setText(c.getEndereco());
        txtNumero.setText(c.getNumero());
        txtComplemento.setText(c.getComplemento());
        comboUf.setSelectedItem(c.getUf());
        txtBairro.setText(c.getBairro());
        txtCidade.setText(c.getCidade());
        txtEmail.setText(c.getEmail());
        txtPontoReferencia.setText(c.getReferencia());
        txtHistorico.setText(c.getHistorico());

        //String nomeLocalidade = cl.retornaNomeLocalidade(c.getLocalidade().getNome());
       // comboLocalidade.setSelectedItem(nomeLocalidade);

    }

    private void valorEnrega() {
        
        String localidade = comboLocalidade.getSelectedItem().toString();
        Localidade loca = new Localidade();
        loca.setNome(localidade);
        
        if (comboLocalidade.getSelectedIndex() != 0) {
            FormataValor fv = new FormataValor();
            lblTaxa.setText(fv.Formata(String.valueOf(cl.retornaTaxa(loca))));
        } else {
            lblTaxa.setText("0,00");
        }
    }
    
}
