/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.Log;
import br.com.br.controler.ControlerCozinha;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author elias
 */
public class TelaConzinha extends javax.swing.JFrame {

    /**
     * Creates new form TelaConzinha
     */
    ControlerCozinha cc = new ControlerCozinha();

    public TelaConzinha() {
        initComponents();
        txtidProdutoCozinha.setVisible(false);

        // Atualiza a lista de pedidos da cozinha após período de tempo informado
        long minutos = 60000; //milisegundos = 1 minuto
        java.util.Timer timer = new java.util.Timer();
        TimerTask atualizaCozinha = new TimerTask() {
            @Override
            public void run() {

                tblCozinha.setModel(DbUtils.resultSetToTableModel(cc.listaProdutosCozinha()));
            }
        };

        timer.scheduleAtFixedRate(atualizaCozinha, 0, minutos);

    }

    public void recebeOperador(String operador, String cargo) {

        lblOperador.setText(operador);
        lblCargo.setText(cargo);
        if ("Gerente".equals(lblCargo.getText())) {
            lblREmovePrato.setVisible(true);
        } else {
            lblREmovePrato.setVisible(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelEsquerdo = new javax.swing.JPanel();
        txtidProdutoCozinha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paineldireito = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCozinha = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAlteraRefeicao = new javax.swing.JPanel();
        btnLiberaRefeicao = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblREmovePrato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        painelEsquerdo.setBackground(new java.awt.Color(38, 53, 61));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cozinha");
        jLabel5.setToolTipText("");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/refeicao128x128.png"))); // NOI18N
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout painelEsquerdoLayout = new javax.swing.GroupLayout(painelEsquerdo);
        painelEsquerdo.setLayout(painelEsquerdoLayout);
        painelEsquerdoLayout.setHorizontalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(txtidProdutoCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelEsquerdoLayout.setVerticalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(txtidProdutoCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        getContentPane().add(painelEsquerdo);
        painelEsquerdo.setBounds(0, 0, 270, 546);

        paineldireito.setLayout(null);

        tblCozinha.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        tblCozinha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCozinha.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblCozinha.setRowHeight(30);
        tblCozinha.setSelectionBackground(new java.awt.Color(255, 255, 102));
        tblCozinha.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblCozinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCozinhaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCozinha);
        if (tblCozinha.getColumnModel().getColumnCount() > 0) {
            tblCozinha.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblCozinha.getColumnModel().getColumn(1).setPreferredWidth(180);
            tblCozinha.getColumnModel().getColumn(2).setPreferredWidth(30);
            tblCozinha.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        paineldireito.add(jScrollPane1);
        jScrollPane1.setBounds(12, 116, 861, 319);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel2.setText("SOLICITAÇÕES");
        paineldireito.add(jLabel2);
        jLabel2.setBounds(167, 22, 305, 64);

        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/power.png"))); // NOI18N
        jLabel4.setText("Logout");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnlogoutLayout = new javax.swing.GroupLayout(btnlogout);
        btnlogout.setLayout(btnlogoutLayout);
        btnlogoutLayout.setHorizontalGroup(
            btnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnlogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnlogoutLayout.setVerticalGroup(
            btnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnlogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        paineldireito.add(btnlogout);
        btnlogout.setBounds(210, 450, 161, 85);

        btnAlteraRefeicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlteraRefeicaoMouseClicked(evt);
            }
        });

        btnLiberaRefeicao.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnLiberaRefeicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/refeicao.png"))); // NOI18N
        btnLiberaRefeicao.setText("Libera Refeição");
        btnLiberaRefeicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLiberaRefeicaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnAlteraRefeicaoLayout = new javax.swing.GroupLayout(btnAlteraRefeicao);
        btnAlteraRefeicao.setLayout(btnAlteraRefeicaoLayout);
        btnAlteraRefeicaoLayout.setHorizontalGroup(
            btnAlteraRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlteraRefeicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLiberaRefeicao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAlteraRefeicaoLayout.setVerticalGroup(
            btnAlteraRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlteraRefeicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLiberaRefeicao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paineldireito.add(btnAlteraRefeicao);
        btnAlteraRefeicao.setBounds(370, 450, 178, 85);

        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblOperador.setText("jLabel9");
        paineldireito.add(lblOperador);
        lblOperador.setBounds(688, 16, 130, 30);

        lblCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblCargo.setText("jLabel10");
        paineldireito.add(lblCargo);
        lblCargo.setBounds(688, 53, 130, 40);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        paineldireito.add(jPanel1);
        jPanel1.setBounds(860, 0, 40, 40);

        lblREmovePrato.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblREmovePrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fechar.png"))); // NOI18N
        lblREmovePrato.setText("Remove Prato");
        lblREmovePrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblREmovePratoMouseClicked(evt);
            }
        });
        paineldireito.add(lblREmovePrato);
        lblREmovePrato.setBounds(580, 450, 160, 80);

        getContentPane().add(paineldireito);
        paineldireito.setBounds(270, 0, 900, 550);

        setSize(new java.awt.Dimension(1168, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // Fecha Janela
        Log l = new Log();
        l.setUsuario(lblOperador.getText());
        l.setFuncionalidade("Fechar");

        String cargo = lblCargo.getText();
        if ("Gerente".equals(cargo)) {
            l.setDescricao(l.getUsuario() + " Fechou a tela cozinha");
            l.gravaLog(l);
            dispose();
        } else {

            if (cc.pratoPendente() > 0) { // Verifica se existem pratos pendentes na cozinha.
                JOptionPane.showMessageDialog(null, "Existem pratos pendentes!");
            }
            l.setDescricao(l.getUsuario() + " Saiu da tela cozinha");
            l.gravaLog(l);
            System.exit(0);
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void tblCozinhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCozinhaMouseClicked
        int linha = tblCozinha.getSelectedRow();
        txtidProdutoCozinha.setText(tblCozinha.getModel().getValueAt(linha, 0).toString());


    }//GEN-LAST:event_tblCozinhaMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked


    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnAlteraRefeicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlteraRefeicaoMouseClicked
    }//GEN-LAST:event_btnAlteraRefeicaoMouseClicked

    private void btnLiberaRefeicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLiberaRefeicaoMouseClicked
        // Libera produto refeição  da cozinha

        if (cc.liberaProduto(txtidProdutoCozinha.getText())) {
            JOptionPane.showMessageDialog(null, "Pedido Librado!");
            Log l = new Log();
            l.setDescricao(lblOperador.getText() + " liberou um(a)" + tblCozinha.getModel().getValueAt(0, 1).toString() + " da cozinha");
            l.setFuncionalidade("Liberar Pedido");
            l.setUsuario(lblOperador.getText());
            l.gravaLog(l);

            tblCozinha.setModel(DbUtils.resultSetToTableModel(cc.listaProdutosCozinha()));
        }

    }//GEN-LAST:event_btnLiberaRefeicaoMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (cc.pratoPendente() > 0) {
            JOptionPane.showMessageDialog(null, "Realize a liberação dos pratos \n pendentes para continuar");
        } else {

            // Faz logout
            Log l = new Log();

            l.setDescricao(lblOperador.getText() + "Fez logout no sistema");
            l.setFuncionalidade("Logout");
            l.setUsuario(lblOperador.getText());
            l.gravaLog(l);

            dispose();
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lblREmovePratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblREmovePratoMouseClicked
        // Remove prato Cozinha
        if ("Gerente".equals(lblCargo.getText())) {

            if (txtidProdutoCozinha.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um item antes de excluir!");
            } else {
                int resp = JOptionPane.showConfirmDialog(null, "Deseja remover este item?", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (resp == JOptionPane.YES_OPTION) {
                    if (cc.removePrato(txtidProdutoCozinha.getText())) {
                        JOptionPane.showMessageDialog(null, "Produto removido!");
                        tblCozinha.setModel(DbUtils.resultSetToTableModel(cc.listaProdutosCozinha()));
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Operação cancelada!");
                }
            }
        } else {
            // Desabilita o botão remove prato para o usuários com cargo diferente de gerente.
            lblREmovePrato.setVisible(false);
        }

    }//GEN-LAST:event_lblREmovePratoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConzinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConzinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConzinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConzinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConzinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAlteraRefeicao;
    private javax.swing.JLabel btnLiberaRefeicao;
    private javax.swing.JPanel btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblREmovePrato;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JPanel paineldireito;
    private javax.swing.JTable tblCozinha;
    private javax.swing.JTextField txtidProdutoCozinha;
    // End of variables declaration//GEN-END:variables
}
