/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.ConexaoBd;
import br.com.bar.dao.Log;
import br.com.bar.dao.ReportUtil;
import br.com.bar.model.Contas;
import br.com.bar.model.DadosEmpresa;
import br.com.br.controler.ControlerContasApagar;
import br.com.br.controler.ControlerDadosEmpresa;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerGrupo;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author elias
 */
public class TelaContasApagar extends javax.swing.JFrame {

    /**
     * Creates new form TelaContasApagar
     */
    ControlerContasApagar cc = new ControlerContasApagar();
    ControlerFuncionario cf = new ControlerFuncionario();
    ControlerGrupo grupo = new ControlerGrupo();
    ReportUtil rpu=new ReportUtil();
    SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
    Connection conexao = ConexaoBd.conector();
    ControlerDadosEmpresa de = new ControlerDadosEmpresa();

    // Instacia um registro de log
    Log l = new Log();

    public TelaContasApagar() {
        initComponents();
        Date d = new Date();
        desaBilitaBotoes();
        txtIdConta.setVisible(false);
        txtIdFuncionario.setVisible(false);
        txtIdGrupo.setVisible(false);
        jdateChooserPagamento.setVisible(false);
        lblAdicionar.setEnabled(true);
        lblDataDePAgamento.setVisible(false);
        lblDataDePAgamento.setText("Data de Pagamento");
        txtValorPago.setVisible(false);
        btnBaixar.setVisible(false);
        lblValorPago.setVisible(false);
        lblLimpar.setEnabled(false);
        cc.listaGrupos(comboGrupoDespesas);
        txtIdGrupo.setText(grupo.localizaIdGrupo(comboGrupoDespesas));
        combofunc.setVisible(false);
        jSpinQtd.setVisible(false);
        btnGraficoDeDespesas.setVisible(false);
        try {
            //Adiciona data ao objeto jdateChooser 
            jdateChooserVencimento.setDate(d);
        } catch (Exception e) {
            System.out.println("br.com.bar.view.TelaContasApagar.<init>()" +e );
        }
    }

    public void recebeOperador(String operador, String cargo) {

        lblCargo.setText(cargo);
        lblOperador.setText(operador);
        txtIdFuncionario.setText(cf.localizaIdLogin(operador));
        l.setUsuario(operador);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelEsquerdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblValorPago = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboGrupoDespesas = new javax.swing.JComboBox<>();
        lblDataDePAgamento = new javax.swing.JLabel();
        jdateChooserVencimento = new com.toedter.calendar.JDateChooser();
        jdateChooserPagamento = new com.toedter.calendar.JDateChooser();
        txtIdConta = new javax.swing.JTextField();
        combofunc = new javax.swing.JComboBox<>();
        jCheckMultiplo = new javax.swing.JCheckBox();
        jSpinQtd = new com.toedter.components.JSpinField();
        jLabel9 = new javax.swing.JLabel();
        painelDireito = new javax.swing.JPanel();
        lblOperador = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        txtIdFuncionario = new javax.swing.JTextField();
        Menu = new javax.swing.JPanel();
        btnBaixar = new javax.swing.JLabel();
        btnGraficoDeDespesas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        txtIdGrupo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tbnFechar = new javax.swing.JLabel();
        btnSalvar1 = new javax.swing.JPanel();
        lblLimpar = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JPanel();
        lblAdicionar = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JPanel();
        lblExcluir = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JPanel();
        lblalterar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        painelEsquerdo.setBackground(new java.awt.Color(38, 53, 61));
        painelEsquerdo.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/CalendarioCinzaClaro.png"))); // NOI18N
        painelEsquerdo.add(jLabel1);
        jLabel1.setBounds(100, 10, 128, 100);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contas a Pagar");
        painelEsquerdo.add(jLabel2);
        jLabel2.setBounds(30, 100, 307, 64);

        txtDescricao.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescricaoFocusGained(evt);
            }
        });
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });
        painelEsquerdo.add(txtDescricao);
        txtDescricao.setBounds(20, 200, 320, 40);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor R$");
        painelEsquerdo.add(jLabel5);
        jLabel5.setBounds(190, 330, 70, 30);

        txtValor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });
        painelEsquerdo.add(txtValor);
        txtValor.setBounds(190, 360, 150, 40);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data de Vencimento");
        painelEsquerdo.add(jLabel8);
        jLabel8.setBounds(20, 250, 170, 30);

        lblValorPago.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblValorPago.setForeground(new java.awt.Color(255, 255, 255));
        lblValorPago.setText("Valor Pago R$");
        painelEsquerdo.add(lblValorPago);
        lblValorPago.setBounds(20, 410, 150, 30);

        txtValorPago.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorPagoKeyReleased(evt);
            }
        });
        painelEsquerdo.add(txtValorPago);
        txtValorPago.setBounds(20, 440, 130, 40);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Grupo de Despesas");
        painelEsquerdo.add(jLabel7);
        jLabel7.setBounds(20, 330, 150, 30);

        comboGrupoDespesas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        comboGrupoDespesas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboGrupoDespesasItemStateChanged(evt);
            }
        });
        comboGrupoDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGrupoDespesasActionPerformed(evt);
            }
        });
        painelEsquerdo.add(comboGrupoDespesas);
        comboGrupoDespesas.setBounds(20, 360, 150, 40);

        lblDataDePAgamento.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblDataDePAgamento.setForeground(new java.awt.Color(255, 255, 255));
        lblDataDePAgamento.setText("Data de Pagamento");
        painelEsquerdo.add(lblDataDePAgamento);
        lblDataDePAgamento.setBounds(190, 250, 170, 30);
        painelEsquerdo.add(jdateChooserVencimento);
        jdateChooserVencimento.setBounds(20, 280, 150, 40);
        painelEsquerdo.add(jdateChooserPagamento);
        jdateChooserPagamento.setBounds(190, 280, 150, 40);
        painelEsquerdo.add(txtIdConta);
        txtIdConta.setBounds(280, 20, 50, 30);

        combofunc.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        painelEsquerdo.add(combofunc);
        combofunc.setBounds(160, 440, 180, 40);

        jCheckMultiplo.setBackground(new java.awt.Color(38, 53, 61));
        jCheckMultiplo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jCheckMultiplo.setForeground(new java.awt.Color(255, 255, 255));
        jCheckMultiplo.setText("Lançamento Múltiplo");
        jCheckMultiplo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckMultiploMouseClicked(evt);
            }
        });
        jCheckMultiplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMultiploActionPerformed(evt);
            }
        });
        painelEsquerdo.add(jCheckMultiplo);
        jCheckMultiplo.setBounds(120, 170, 160, 25);
        painelEsquerdo.add(jSpinQtd);
        jSpinQtd.setBounds(190, 280, 150, 40);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descrição");
        painelEsquerdo.add(jLabel9);
        jLabel9.setBounds(20, 170, 110, 20);

        getContentPane().add(painelEsquerdo);
        painelEsquerdo.setBounds(0, 0, 360, 520);

        painelDireito.setBackground(new java.awt.Color(204, 204, 204));
        painelDireito.setLayout(null);

        lblOperador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        painelDireito.add(lblOperador);
        lblOperador.setBounds(230, 20, 130, 30);

        lblCargo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblCargo.setText("Cargo");
        painelDireito.add(lblCargo);
        lblCargo.setBounds(330, 20, 100, 30);
        painelDireito.add(txtIdFuncionario);
        txtIdFuncionario.setBounds(10, 20, 40, 30);

        btnBaixar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnBaixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btnbaixar-48.png"))); // NOI18N
        btnBaixar.setText("Pagar");
        btnBaixar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaixarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBaixarMouseEntered(evt);
            }
        });

        btnGraficoDeDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btngrafico2-48.png"))); // NOI18N
        btnGraficoDeDespesas.setText("Gráfico");
        btnGraficoDeDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraficoDeDespesasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficoDeDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGraficoDeDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaixar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelDireito.add(Menu);
        Menu.setBounds(0, 440, 620, 80);

        tblContas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblContas.setRowHeight(25);
        tblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContas);

        painelDireito.add(jScrollPane1);
        jScrollPane1.setBounds(0, 140, 610, 280);
        painelDireito.add(txtIdGrupo);
        txtIdGrupo.setBounds(60, 20, 40, 30);

        jPanel1.setBackground(new java.awt.Color(38, 53, 61));

        tbnFechar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tbnFechar.setForeground(new java.awt.Color(255, 255, 255));
        tbnFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbnFechar.setText("x");
        tbnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tbnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDireito.add(jPanel1);
        jPanel1.setBounds(570, 0, 50, 40);

        btnSalvar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvar1MouseClicked(evt);
            }
        });

        lblLimpar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fechar.png"))); // NOI18N
        lblLimpar.setText("Limpar");
        lblLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalvar1Layout = new javax.swing.GroupLayout(btnSalvar1);
        btnSalvar1.setLayout(btnSalvar1Layout);
        btnSalvar1Layout.setHorizontalGroup(
            btnSalvar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        btnSalvar1Layout.setVerticalGroup(
            btnSalvar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painelDireito.add(btnSalvar1);
        btnSalvar1.setBounds(170, 70, 97, 54);

        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });

        lblAdicionar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/adicionas32x32.png"))); // NOI18N
        lblAdicionar.setText("Adicionar");
        lblAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdicionarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalvarLayout = new javax.swing.GroupLayout(btnSalvar);
        btnSalvar.setLayout(btnSalvarLayout);
        btnSalvarLayout.setHorizontalGroup(
            btnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        btnSalvarLayout.setVerticalGroup(
            btnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painelDireito.add(btnSalvar);
        btnSalvar.setBounds(280, 70, 110, 54);

        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        lblExcluir.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Lixeira.png"))); // NOI18N
        lblExcluir.setText("Excluir");
        lblExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnExcluirLayout = new javax.swing.GroupLayout(btnExcluir);
        btnExcluir.setLayout(btnExcluirLayout);
        btnExcluirLayout.setHorizontalGroup(
            btnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExcluirLayout.createSequentialGroup()
                .addComponent(lblExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnExcluirLayout.setVerticalGroup(
            btnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExcluirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDireito.add(btnExcluir);
        btnExcluir.setBounds(400, 70, 90, 54);

        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });

        lblalterar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/lapis.png"))); // NOI18N
        lblalterar.setText("Alterar");
        lblalterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblalterarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnAlterarLayout = new javax.swing.GroupLayout(btnAlterar);
        btnAlterar.setLayout(btnAlterarLayout);
        btnAlterarLayout.setHorizontalGroup(
            btnAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblalterar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnAlterarLayout.setVerticalGroup(
            btnAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblalterar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painelDireito.add(btnAlterar);
        btnAlterar.setBounds(500, 70, 100, 54);

        jPanel2.setPreferredSize(new java.awt.Dimension(78, 32));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/filtro32x32.png"))); // NOI18N

        comboFiltro.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Tudo", "Pagas", "Abertas" }));
        comboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelDireito.add(jPanel2);
        jPanel2.setBounds(10, 70, 150, 55);

        getContentPane().add(painelDireito);
        painelDireito.setBounds(360, 0, 620, 520);

        setSize(new java.awt.Dimension(976, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked


    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnSalvar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar1MouseClicked


    }//GEN-LAST:event_btnSalvar1MouseClicked

    private void tbnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnFecharMouseClicked
        // Fecha tela principal
        this.dispose();
    }//GEN-LAST:event_tbnFecharMouseClicked

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        // Substitui virgula por ponto ao digitar
        String valorAntigo = txtValor.getText();
        String valorNovo = valorAntigo.replaceAll(",", ".");
        txtValor.setText(valorNovo);
    }//GEN-LAST:event_txtValorKeyReleased

    private void txtValorPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPagoKeyReleased
        // Substitui virgula por ponto ao digitar
        String valorAntigo = txtValorPago.getText();
        String valorNovo = valorAntigo.replaceAll(",", ".");
        txtValorPago.setText(valorNovo);
    }//GEN-LAST:event_txtValorPagoKeyReleased

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        // Foca combo Grupo de Despesas ao pressionar enter

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            comboGrupoDespesas.requestFocus();
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void comboGrupoDespesasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboGrupoDespesasItemStateChanged

    }//GEN-LAST:event_comboGrupoDespesasItemStateChanged

    private void comboGrupoDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGrupoDespesasActionPerformed

        txtIdGrupo.setText(grupo.localizaIdGrupo(comboGrupoDespesas));
        String operador = lblOperador.getText();


    }//GEN-LAST:event_comboGrupoDespesasActionPerformed

    private void tblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContasMouseClicked
        // Habilita Botões
        habilitaBotoes();
        
        // Data Atual
        Date dataAtual = new Date();

        // Seleciona dados da tabela
        Contas c = new Contas();
        c.setId(txtIdConta.getText());
        c.setDataPagto(null);
        c.setValoPagto(null);
        c.setDescricao(txtDescricao.getText());
        

        int linha = tblContas.getSelectedRow();
        txtIdConta.setText(tblContas.getModel().getValueAt(linha, 0).toString());
        txtDescricao.setText(tblContas.getModel().getValueAt(linha, 1).toString());
        String dataPagamento;
        String dataVencimento = tblContas.getModel().getValueAt(linha, 3).toString();
        String tipo = tblContas.getModel().getValueAt(linha, 7).toString();
        comboGrupoDespesas.setSelectedItem(tipo);
        if ("Comissão".equals(tipo)) {
            combofunc.setVisible(true);
            cf.carregaComboFuncionario(combofunc, "Garçom");
        } else {
            combofunc.setVisible(false);
        }
        // Seta data no jdateschooser
        try {

            jdateChooserVencimento.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(dataVencimento));

        } catch (ParseException ex) {

        }

        // Captura excessão quando se seleciona uma conta cadastrada na tabela.
        try {

            dataPagamento = tblContas.getModel().getValueAt(linha, 4).toString();

            jdateChooserPagamento.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(dataPagamento));

        } catch (ParseException e) {

        } catch (NullPointerException n) {
            // Caso o valor seja nulo exibe os campos para pagamento
            lblDataDePAgamento.setVisible(true);
            jdateChooserPagamento.setVisible(true);
            lblValorPago.setVisible(true);
            txtValorPago.setVisible(true);
            btnBaixar.setVisible(true);
            txtValorPago.setText(tblContas.getModel().getValueAt(linha, 2).toString());

        }

        txtValor.setText(tblContas.getModel().getValueAt(linha, 2).toString());
        txtValorPago.setText(tblContas.getModel().getValueAt(linha, 2).toString());

        try {

            if (evt.getButton() == MouseEvent.BUTTON3) {
                JPopupMenu menuPopup = cc.menu(c, lblOperador);
                menuPopup.show(tblContas, evt.getX(), evt.getY());
                limpaForm();

            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_tblContasMouseClicked

    private void btnBaixarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaixarMouseClicked
        // Baixa Conta
        Contas c = new Contas();

        c.setId(txtIdConta.getText());
        c.setDataPagto(cc.myData(jdateChooserPagamento));
        c.setValoPagto(txtValorPago.getText().replaceAll(",", "."));
        c.setOperador(lblOperador.getText());
        Date dtPagamento = jdateChooserPagamento.getDate();
        Date dtVencimento = jdateChooserVencimento.getDate();
        
if (dtPagamento.getTime()<dtVencimento.getTime()){
    JOptionPane.showMessageDialog(null, "A data de pagamento não pode ser\ninferior a data de vencimento!");
}else {
    
    
     if (c.getDataPagto().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Informe a data de pagamento para continuar!");
    } else {

        if (c.getId() == null) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar...");
        } else if (c.getDataPagto() == null) {
            JOptionPane.showMessageDialog(null, "Informe a data de Pagamento");
        } else {
            int op = JOptionPane.showConfirmDialog(null, "Confirma a baixa desta conta?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if (op == JOptionPane.YES_OPTION) {
                if (cc.baixarConta(c)) {
                    // Registra operação no log
                    l.setFuncionalidade("Pagamento");
                    l.setDescricao(l.getUsuario() + " pagou a conta " + txtDescricao.getText() + "-> R$ " + txtValor.getText() + "Vencimento: "
                            + df.format(jdateChooserVencimento.getCalendar().getTime()) + ": Pagamento" + df.format(jdateChooserVencimento.getCalendar().getTime()));
                    l.gravaLog(l);
                    // fim do registro de log

                    JOptionPane.showMessageDialog(null, "Baixa realizada com sucesso!");
                    limpaForm();
                    tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Aberto")));
                    // Fim do registro de log

                    int confirma = JOptionPane.showConfirmDialog(null, "Deseja Imprimir comprovante?", "Aenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                    if (confirma == JOptionPane.YES_OPTION) {
                        HashMap parametros = new HashMap();
                        parametros.put("titulo", "====== RECIBO DE PAGAMENTO ========= ");

                        // Caso o valor a ser pago seja uma comissão o parâmetro a ser setado será o nome do funcionário que consta no combo
                        //funcionario caso ele estejá visível
                         
                        if (combofunc.isVisible()) {

                            parametros.put("funcionario", combofunc.getSelectedItem().toString());
                        } else {
                            parametros.put("funcionario", lblOperador.getText());
                        }

                        parametros.put("id", Integer.parseInt(txtIdConta.getText()));
                        
                        try {

                            DadosEmpresa dados = de.selecionaDados();
                            parametros.put("empresa", dados.getNome_empresa());
                            rpu.imprimiRelatorioTela("reciboDePagamento.jasper", rpu.rodape(dados, parametros));
                            combofunc.setVisible(false);

                        } catch (JRException ex) {
                            System.out.println("br.com.bar.view.TelaContasApagar.btnBaixarMouseClicked()");
                        }

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Operação Cancelada!");
                    combofunc.setVisible(false);

                }

            }
        }
    }
    
}


    }//GEN-LAST:event_btnBaixarMouseClicked

    private void btnBaixarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaixarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaixarMouseEntered

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked


    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked


    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnGraficoDeDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficoDeDespesasMouseClicked
        // Gera gráfico de pizza das Despesas 
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        ResultSet rs = cc.listaContasPorCategoria();

        //Captura dados da consulta
        try {
            while (rs.next()) {
                pieDataset.setValue(rs.getString("grupo"), rs.getDouble("valor"));

            }
        } catch (SQLException e) {
            System.out.println("Erro ao preencher pierDataSet" + e);
        }
        // Cria Gráfico de Pizza

        JFreeChart graficoPizza = ChartFactory.createPieChart3D("Demonstrativo de Despesas", pieDataset, true, true, true);
        // Plotagem

        PiePlot piePlot = (PiePlot) graficoPizza.getPlot();

        // Janela do Grafico
        ChartFrame frame = new ChartFrame("Gráfico - Demonstrativo de Despesas", graficoPizza);
        frame.setSize(947, 524);
        frame.setVisible(true);

    }//GEN-LAST:event_btnGraficoDeDespesasMouseClicked

    private void jCheckMultiploMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckMultiploMouseClicked
        // Exibe caixa quantidade
        if (jCheckMultiplo.isSelected()) {
            jSpinQtd.setVisible(true);
            lblDataDePAgamento.setVisible(true);
            lblDataDePAgamento.setText("Parcelas");

        } else {
            jSpinQtd.setVisible(false);
            lblDataDePAgamento.setVisible(false);
            lblDataDePAgamento.setText("Data de Pagamento");
        }
    }//GEN-LAST:event_jCheckMultiploMouseClicked

    private void lblAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdicionarMouseClicked
        //Cadastra Conta
        if (lblAdicionar.isEnabled()){
            
            Contas c = new Contas();

            c.setDescricao(txtDescricao.getText());
            c.setDataVencto(cc.myData(jdateChooserVencimento));
            c.setValor(txtValor.getText().replaceAll(",", "."));
            c.setGrupoId(txtIdGrupo.getText());
            c.setFuncionarioId(txtIdFuncionario.getText());
            if ("".equals(c.getDescricao())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os dados para continuar!");
            } else {

                // Verifica se a conta Existe
                if (cc.existeConta(txtIdConta.getText())) {

                    JOptionPane.showMessageDialog(null, "Conta já cadastrada!");

                } else {

                    if (jCheckMultiplo.isSelected()) {

                        if (cc.lancamentoMultiplo(jSpinQtd.getValue(), jdateChooserVencimento, c)) {
                            JOptionPane.showMessageDialog(null, "Lançamento múltiplo realiado com sucesso!");
                            tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Aberto")));
                            limpaForm();
                        }
                    } else {
                        // Caso o checkList não esteja selecionado executa a parcela de forma padrão

                        if (cc.adicionaConta(c)) {
                            //Registra operação no log
                            l.setFuncionalidade("Salvar");
                            l.setDescricao(l.getUsuario() + " adicionou uma nova conta ->" + txtDescricao.getText());
                            l.gravaLog(l);
                            // fim do registro de log
                            limpaForm();
                            JOptionPane.showMessageDialog(null, "Cadastro Relizado com sucesso!");
                            desaBilitaBotoes();

                            tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Aberto")));
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_lblAdicionarMouseClicked


    private void lblalterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblalterarMouseClicked
        // Altera apenas contas em aberto
        if (lblalterar.isEnabled()){
            
            Contas c = new Contas();
            c.setDescricao(txtDescricao.getText());
            c.setDataVencto(cc.myData(jdateChooserVencimento));
            c.setGrupoId(txtIdGrupo.getText());
            c.setValor(txtValor.getText());
            c.setId(txtIdConta.getText());
            c.setDataPagto(cc.myData(jdateChooserPagamento));

            if ("".equals(c.getDataPagto())) {
                if ("".equals(txtIdConta.getText())) {
                    JOptionPane.showMessageDialog(null, "Selecione uma conta para continuar!");
                } else {

                    if (cc.alteraConta(c)) {

                        JOptionPane.showMessageDialog(null, "Conta alterada!");
                        tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Aberto")));
                        limpaForm();
                        //Regisra operação no log
                        l.setFuncionalidade("Alterar");
                        l.setDescricao(l.getUsuario() + " alterou a conta ->" + c.getDescricao() + " Data de Vencimento: " + c.getDataVencto());
                        l.gravaLog(l);
                        desaBilitaBotoes();
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Contas pagas não podem ser alteradas!");

            }
        }
    }//GEN-LAST:event_lblalterarMouseClicked

    private void lblLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimparMouseClicked
        // Desabilita o botão limpar.
        if (lblLimpar.isEnabled()){
            
            limpaForm();
            txtIdConta.setText(null);
            lblDataDePAgamento.setVisible(false);
            jdateChooserPagamento.setVisible(false);
            lblValorPago.setVisible(false);
            txtValorPago.setVisible(false);
            combofunc.setVisible(false);
        }
    }//GEN-LAST:event_lblLimparMouseClicked

    private void lblExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseClicked
        if (lblExcluir.isEnabled()){
            
            //Exclui conta
            Contas c = new Contas();
            c.setId(txtIdConta.getText());
            c.setDataPagto(cc.myData(jdateChooserPagamento));
            c.setDescricao(txtDescricao.getText());

            if (c.getDataPagto().isEmpty()) {

                if (c.getId().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Selecione uma conta para continuar!");
                } else {
                    // Registra operação no log
                    l.setFuncionalidade("Excluir");
                    try {

                        l.setDescricao(l.getUsuario() + " excluiu a conta ->" + txtDescricao.getText() + " Vencimento: " + df.format(jdateChooserVencimento.getCalendar().getTime()) + " Valor R$ " + txtValor.getText());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Selecione uma conta para continuar!");

                    }
                    l.gravaLog(l);
                    // Fim registro de log
                    if (c.getDescricao() == null || "".equals(c.getDescricao())) {

                    } else {

                        cc.excluiConta(c);
                    }
                    tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar("Aberto")));  // Filtro Aberto | Tudo
                    limpaForm();
                    desaBilitaBotoes();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Contas Pagas não podem ser excluída!");
                limpaForm();

            }
        }


    }//GEN-LAST:event_lblExcluirMouseClicked

    private void comboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroActionPerformed
        
        String op = comboFiltro.getSelectedItem().toString();
             
                        
        switch (op){
            case "Abertas":                
                tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar(op)));
                break;
            case "Pagas":
                tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar(op)));
                break;
            case "Tudo":
                tblContas.setModel(DbUtils.resultSetToTableModel(cc.listaContasApagar(op)));
                break;
            case "Selecione...":
                DefaultTableModel tbm = new DefaultTableModel();
                tblContas.setModel(tbm);
                break;
        }
        
    }//GEN-LAST:event_comboFiltroActionPerformed

    private void jCheckMultiploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMultiploActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckMultiploActionPerformed

    private void txtDescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoFocusGained
        // Desabilita TextFild Valor
        txtValor.setEditable(true);
    }//GEN-LAST:event_txtDescricaoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContasApagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContasApagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContasApagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContasApagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContasApagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel btnAlterar;
    private javax.swing.JLabel btnBaixar;
    private javax.swing.JPanel btnExcluir;
    private javax.swing.JLabel btnGraficoDeDespesas;
    private javax.swing.JPanel btnSalvar;
    private javax.swing.JPanel btnSalvar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JComboBox<String> comboGrupoDespesas;
    private javax.swing.JComboBox<String> combofunc;
    private javax.swing.JCheckBox jCheckMultiplo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinQtd;
    private com.toedter.calendar.JDateChooser jdateChooserPagamento;
    private com.toedter.calendar.JDateChooser jdateChooserVencimento;
    private javax.swing.JLabel lblAdicionar;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDataDePAgamento;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblLimpar;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JLabel lblalterar;
    private javax.swing.JPanel painelDireito;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JTable tblContas;
    private javax.swing.JLabel tbnFechar;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdConta;
    private javax.swing.JTextField txtIdFuncionario;
    private javax.swing.JTextField txtIdGrupo;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables

    private void limpaForm() {
        txtDescricao.setText(null);
        txtValor.setText(null);
        txtValorPago.setText(null);
        jdateChooserPagamento.setDate(null);
        jdateChooserVencimento.setDate(null);

    }

    private void habilitaBotoes() {
         lblLimpar.setEnabled(true);
         lblAdicionar.setEnabled(true);
         lblalterar.setEnabled(true);
         lblExcluir.setEnabled(true);
    }
    private void desaBilitaBotoes() {
         lblLimpar.setEnabled(false);
         lblAdicionar.setEnabled(false);
         lblalterar.setEnabled(false);
         lblExcluir.setEnabled(false);
    }
}
