/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.model.Pedido;
import br.com.bar.model.Produto;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerMesa;
import br.com.br.controler.ControlerPedido;
import br.com.br.controler.ControlerProduto;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author elias
 */
public class TelaPedido2 extends javax.swing.JFrame {
    ControlerFuncionario cFunc = new ControlerFuncionario();
    ControlerMesa cm = new ControlerMesa();
    ControlerPedido cp = new ControlerPedido();
    ControlerProduto cproduto = new ControlerProduto();
    Util u = new Util();
    /**
     * Creates new form TelaPedido2
     */
    public TelaPedido2() {
        
        initComponents();
        cFunc.carregaComboFuncionario(comboGarcom, "Garçom");
        tblPedidosAbertos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos()));
        // Oculta caixa de pesquisa
        lblPesquisa.setVisible(false);
        txtPesquisa.setVisible(false);
        Calendar c = Calendar.getInstance();
        lblData.setText(u.formataDataBr(c.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        comboGarcom = new javax.swing.JComboBox<>();
        txtIdGarcom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNumeroMesa = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnAbrirPedido = new javax.swing.JButton();
        txtIdMesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidosAbertos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetalhePedido = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblListaProduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblQtd = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbltotal = new javax.swing.JLabel();
        txtNumeroPedido = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        comboGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGarcomActionPerformed(evt);
            }
        });
        getContentPane().add(comboGarcom);
        comboGarcom.setBounds(10, 37, 192, 35);

        txtIdGarcom.setText("idGarcom");
        getContentPane().add(txtIdGarcom);
        txtIdGarcom.setBounds(230, 20, 50, 30);

        tblNumeroMesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNumeroMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Numero da Mesa"
            }
        ));
        tblNumeroMesa.setRowHeight(25);
        tblNumeroMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNumeroMesaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNumeroMesa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 124, 192, 373);

        btnListar.setText("Listar Mesas");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(10, 83, 93, 35);

        btnAbrirPedido.setText("Abrir Pedido");
        btnAbrirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirPedido);
        btnAbrirPedido.setBounds(109, 83, 93, 35);

        txtIdMesa.setText("idMesa");
        getContentPane().add(txtIdMesa);
        txtIdMesa.setBounds(350, 20, 50, 30);

        jLabel2.setText("Garçom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 14, 70, 14);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        tblPedidosAbertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPedidosAbertos.setRowHeight(25);
        tblPedidosAbertos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosAbertosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPedidosAbertos);

        jTabbedPane1.addTab("Pedidos Abertos", jScrollPane2);

        tblDetalhePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDetalhePedido.setRowHeight(25);
        jScrollPane3.setViewportView(tblDetalhePedido);

        jTabbedPane1.addTab("Detalhe Pedido", jScrollPane3);

        tblListaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListaProduto.setRowHeight(25);
        tblListaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaProdutoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblListaProduto);

        jTabbedPane1.addTab("Lista de Produtos", jScrollPane6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(210, 270, 583, 230);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Produto")));

        lblCodigo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblCodigo.setText("Código");

        lblQtd.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblQtd.setText("Qtd");

        txtQtd.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtQtd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtdMouseClicked(evt);
            }
        });
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
        });

        txtCodigoProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtCodigoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoProdutoMouseClicked(evt);
            }
        });
        txtCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtd)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQtd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtd)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(220, 60, 301, 161);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Produto")));

        lblProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblProduto.setText("jLabel3");

        lblValor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblValor.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(lblValor))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(550, 60, 250, 70);

        lblData.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblData.setText("jLabel3");
        getContentPane().add(lblData);
        lblData.setBounds(640, 10, 158, 48);

        lblPesquisa.setText("Pesquisar Produto");
        getContentPane().add(lblPesquisa);
        lblPesquisa.setBounds(220, 240, 120, 14);
        getContentPane().add(txtPesquisa);
        txtPesquisa.setBounds(340, 230, 180, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Total")));

        lbltotal.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotal.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbltotal)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(550, 140, 250, 80);

        txtNumeroPedido.setText("idMesa");
        getContentPane().add(txtNumeroPedido);
        txtNumeroPedido.setBounds(290, 20, 50, 30);

        setSize(new java.awt.Dimension(920, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGarcomActionPerformed
        
        
    }//GEN-LAST:event_comboGarcomActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // Lista todas as mesas livres do funcionário selecionado
        String nomeFunc = comboGarcom.getSelectedItem().toString();
        String idFunc = cFunc.localizaId(nomeFunc);
        tblNumeroMesa.setModel(DbUtils.resultSetToTableModel(cm.listaMesaLivre(idFunc)));
        tblPedidosAbertos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos()));
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAbrirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPedidoActionPerformed
        // Abre pedido
        if (cp.temPedido(txtIdMesa.getText())){
                        JOptionPane.showMessageDialog(null, "Esta mesa já possui um pedido escolha outra!");
        }else {
            Pedido p = new Pedido();
            p.setCadMesaId(txtIdMesa.getText());
            String dataAtual = cp.myDataAtual();
            p.setData(dataAtual);
            p.setStatus("0"); // Pedido Aberto
            p.setIdFuncionario(txtIdGarcom.getText());
            //p.setId_pedido(txtNumeroPedido.getText());
            
            int op = JOptionPane.showConfirmDialog(null, "Confirma a abertura do Pedido?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if (op == JOptionPane.YES_OPTION) {

                if (cp.geraPedido(p)) {
                    int linha = tblNumeroMesa.getSelectedRow();
                    String numero_mesa = tblNumeroMesa.getModel().getValueAt(linha, 0).toString();
                    JOptionPane.showMessageDialog(null, "Pedido Gerado!");
                    
                    tblPedidosAbertos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos()));
                    cm.trocaStatusMesa(numero_mesa, "1");
                    tblNumeroMesa.setModel(DbUtils.resultSetToTableModel(cm.listaMesaLivre(txtIdGarcom.getText())));

                }

            } else {
                JOptionPane.showMessageDialog(null, "Abertura cancelada!");

            }
        }
    }//GEN-LAST:event_btnAbrirPedidoActionPerformed

    private void tblNumeroMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNumeroMesaMouseClicked
        // Seleciona uma mesa na tabela
        int linha = tblNumeroMesa.getSelectedRow();
        txtIdMesa.setText(cm.localizaIdMesa(tblNumeroMesa.getModel().getValueAt(linha, 0).toString()));
        txtIdGarcom.setText(cFunc.localizaId(comboGarcom.getSelectedItem().toString()));
    }//GEN-LAST:event_tblNumeroMesaMouseClicked

    private void tblPedidosAbertosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosAbertosMouseClicked
        // Selciona um pedido
        int linha = tblPedidosAbertos.getSelectedRow();
        String numeroMesa = tblPedidosAbertos.getModel().getValueAt(linha, 0).toString();
        String numPedido = tblPedidosAbertos.getModel().getValueAt(linha, 3).toString();
        tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(numeroMesa, numPedido)));
        txtNumeroPedido.setText(numPedido);
    }//GEN-LAST:event_tblPedidosAbertosMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // Exibe caixa de pesquisa e lista todos os produtos disponível no estoque
        lblPesquisa.setVisible(true);
        txtPesquisa.setVisible(true);
        tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.listaProdutoDisponivel()));
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void txtCodigoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProdutoMouseClicked

    }//GEN-LAST:event_txtCodigoProdutoMouseClicked

    private void txtCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoKeyPressed
        // Vai para a caixa quantidade 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //txtIdMesa.setText(cm.localizaIdMesa(comboNumeroMEsa.getSelectedItem().toString()));
            if (txtIdMesa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um pedido!");
            } else {

                Produto produto = new Produto();
                produto.setId(txtCodigoProduto.getText());

                try {

                    Produto pLocalizado = cproduto.localizaProduto(produto);
                    lblProduto.setText(pLocalizado.getNome());
                    lblValor.setText(String.format("%7.2f", Double.parseDouble(pLocalizado.getValor())));

                    txtQtd.requestFocus();
                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "Produto não localizado");
                }
            }

        }
    }//GEN-LAST:event_txtCodigoProdutoKeyPressed

    private void txtQtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdMouseClicked

    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            lbltotal.setText(String.format("%7.2f",calculaPedido()));
        }
    }//GEN-LAST:event_txtQtdKeyPressed

    private void tblListaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaProdutoMouseClicked
        // Carega dados do produto
        int linha = tblListaProduto.getSelectedRow();
        txtCodigoProduto.setText(tblListaProduto.getModel().getValueAt(linha, 0).toString());        
        lblProduto.setText(tblListaProduto.getModel().getValueAt(linha, 1).toString());
        lblValor.setText(tblListaProduto.getModel().getValueAt(linha, 3).toString());
        txtQtd.requestFocus();
        
                
        
    }//GEN-LAST:event_tblListaProdutoMouseClicked

    private  double calculaPedido(){
        double valor = Double.parseDouble(lblValor.getText().replaceAll(",", "."));
        int qtd = Integer.parseInt(txtQtd.getText());
        double total = valor * qtd;
        
        return total;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedido2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPedido;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> comboGarcom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tblDetalhePedido;
    private javax.swing.JTable tblListaProduto;
    private javax.swing.JTable tblNumeroMesa;
    private javax.swing.JTable tblPedidosAbertos;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtIdGarcom;
    private javax.swing.JTextField txtIdMesa;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
