/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.dao.Log;
import br.com.bar.model.Fornecedor;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerFornecedor;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author elias
 */
public class TelaCadastroFornecedor extends JDialog {

    ControlerFornecedor cf = new ControlerFornecedor();
    Log log = new Log();
    Util u = new Util();
    String operacao;
    Fornecedor fRebido = new Fornecedor();
    TelaFornecedores tlFor;

    /**
     * Creates new form TelaCadastroFornecedor
     */
    public TelaCadastroFornecedor() {
        initComponents();
        txtIdFor.setVisible(false);
        lblCargo.setVisible(false);
        lblOperador.setVisible(false);
        btnSalvar.setEnabled(false);
        bloqueiaCampos();
    }

    public void recebeOperador(String operador, String cargo, String operacao, TelaFornecedores tl) {

        lblCargo.setText(cargo);
        lblOperador.setText(operador);
        Calendar c = Calendar.getInstance();
        this.operacao = operacao;
        this.tlFor = tl;
        lblTitulo.setText(operacao);
        if("Incluir".equals(lblTitulo.getText())){
            lblTitulo.setText(operacao);
            desbloqueiaCampos();
            txtFornecedor.setEnabled(true);
            txtCnpj.setEnabled(true);
        }
    }

    public void recebeFornecedor(Fornecedor f) {
        // Carrega da dos do Fornecedor informado no parâmetro do método.
        txtFornecedor.setText(f.getNome());
        txtCnpj.setText(f.getCnpj());
        txtEndereco.setText(f.getEndereco());
        txtNumero.setText(f.getNumero());
        txtComplemento.setText(f.getComplemento());
        txtBairro.setText(f.getBairro());
        txtCep.setText(f.getCep());
        txtCidade.setText(f.getCidade());
        comboUf.setSelectedItem(f.getUf());
        txtRepresentante.setText(f.getRepresentante());
        txtTelefone.setText(f.getTelefone());
        txtEmail.setText(f.getEmail());
        txtSite.setText(f.getSite());
        comboStatus.setSelectedItem(f.getStatus());
        System.out.println("Status:" + f.getStatus());
        txtAreaObs.setText(f.getObs());
        this.fRebido = f;
        switch (operacao) {
            
            case "Incluir":
                lblTitulo.setText(operacao);
                desbloqueiaCampos();
                break;
            case "Alterar":
                lblTitulo.setText(operacao);
                desbloqueiaCampos();
                txtFornecedor.setEnabled(false);
                txtCnpj.setEnabled(false);
                break;
            case "Consultar":
                lblTitulo.setText(operacao);
                bloqueiaCampos();
                btnSalvar.setVisible(false);
                break;

            default:
                bloqueiaCampos();
        }

    }

    private void limparform() {

        txtFornecedor.setText(null);
        txtCnpj.setText(null);
        txtEndereco.setText(null);
        txtNumero.setText(null);
        txtComplemento.setText(null);
        txtBairro.setText(null);
        txtCep.setText(null);
        txtCidade.setText(null);
        comboUf.setSelectedIndex(0);
        txtRepresentante.setText(null);
        txtTelefone.setText(null);
        txtEmail.setText(null);
        txtSite.setText(null);
        comboStatus.setSelectedIndex(0);
        txtAreaObs.setText(null);

    }

    private void bloqueiaCampos() {

        txtFornecedor.setEnabled(false);
        txtCnpj.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        comboUf.setEnabled(false);
        txtRepresentante.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtEmail.setEnabled(false);
        txtSite.setEnabled(false);
        comboStatus.setEnabled(false);
        txtAreaObs.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        txtIdFor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRepresentante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        comboUf = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObs = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(243, 156, 18));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Fornecedor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 50, 270, 48);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btnFornecedor.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 116, 100);

        lblOperador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario (2).png"))); // NOI18N
        lblOperador.setText("Operador");
        jPanel1.add(lblOperador);
        lblOperador.setBounds(350, 80, 120, 32);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(122, 156, 42, 0);

        lblCargo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblCargo.setText("Cargo");
        jPanel1.add(lblCargo);
        lblCargo.setBounds(350, 40, 110, 30);
        jPanel1.add(txtIdFor);
        txtIdFor.setBounds(388, 156, 34, 20);

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/fecharWhite24x24.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(455, 0, 40, 40);

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblTitulo.setText("titulo");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(120, 10, 180, 48);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 0, 500, 120);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Endereço");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 20));

        txtFornecedor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFornecedorKeyReleased(evt);
            }
        });
        jPanel2.add(txtFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 320, 30));

        lblTelefone.setText("Telefone");
        jPanel2.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, 20));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, 30));

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 30));

        jLabel5.setText("CNPJ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 14, -1, 20));

        txtRepresentante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRepresentanteKeyReleased(evt);
            }
        });
        jPanel2.add(txtRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 300, 30));

        jLabel8.setText("Razão Social");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 80, -1));

        jLabel6.setText("Site");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 20));

        txtEmail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, 30));

        jLabel9.setText("Observação");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 80, 20));

        txtSite.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSiteMouseClicked(evt);
            }
        });
        jPanel2.add(txtSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 230, 30));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ativo", "Inativo" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });
        jPanel2.add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 28));

        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyReleased(evt);
            }
        });
        jPanel2.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 470, 30));

        jLabel11.setText("Representante");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, 20));

        jLabel13.setText("CEP");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 20));

        jLabel14.setText("Complemento");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 110, 20));

        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplementoKeyReleased(evt);
            }
        });
        jPanel2.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, 30));

        txtBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtBairroMouseReleased(evt);
            }
        });
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroKeyReleased(evt);
            }
        });
        jPanel2.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 200, 30));

        jLabel15.setText("Bairro");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 110, 20));

        btnSalvar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/salvar32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 110, 48));

        jLabel16.setText("Número");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 20));

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        jLabel17.setText("UF");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 50, 20));

        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCidadeKeyReleased(evt);
            }
        });
        jPanel2.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 290, 30));

        comboUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE" }));
        comboUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUfActionPerformed(evt);
            }
        });
        jPanel2.add(comboUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 80, 30));

        jLabel18.setText("Cidade");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, 20));

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCnpjMouseClicked(evt);
            }
        });
        jPanel2.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 35, 140, 30));

        jLabel10.setText("E-mail");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        txtAreaObs.setColumns(20);
        txtAreaObs.setLineWrap(true);
        txtAreaObs.setRows(5);
        txtAreaObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAreaObsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAreaObs);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 350, 100));

        jLabel19.setText("Status");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 40, 20));
        jPanel2.add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 260, 20));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 120, 500, 550);

        setSize(new java.awt.Dimension(492, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        // Cadastra fornecedor
     if (btnSalvar.isEnabled()){
         
         fRebido.setNome(txtFornecedor.getText());
         fRebido.setCnpj(txtCnpj.getText());
         fRebido.setEndereco(txtEndereco.getText());
         fRebido.setNumero(txtNumero.getText());
         fRebido.setComplemento(txtComplemento.getText());
         fRebido.setBairro(txtBairro.getText());
         fRebido.setCep(txtCep.getText());
         fRebido.setCidade(txtCidade.getText());
         fRebido.setUf(comboUf.getSelectedItem().toString());
         fRebido.setTelefone(txtTelefone.getText());
         fRebido.setEmail(txtEmail.getText());
         fRebido.setRepresentante(txtRepresentante.getText());
         fRebido.setSite(txtSite.getText());
         fRebido.setStatus(comboStatus.getSelectedItem().toString());
         fRebido.setObs(txtAreaObs.getText());

         if ("Incluir".equals(operacao)) {

             if (cf.temFornecedor(fRebido)) {
                 JOptionPane.showMessageDialog(null, "O fornecedor " + fRebido.getNome() + " já está cadastrado!");
             } else if ("Selecione...".equals(comboStatus.getSelectedItem().toString())) {
                 JOptionPane.showMessageDialog(null, "Selecione o status do Fornecedor!");
             } else if ("".equals(txtFornecedor.getText())) {
                 lblMsg.setText("Informe a razão social do fornecedor para continuar!");

             } else {
                 cf.cadastraFornecedor(fRebido);
                 lblMsg.setText("*Fornecedor cadastrado com sucesso!");
                 lblMsg.setForeground(Color.blue);
                 tlFor.atualizaTabela();
                 dispose();
                 // Inicio do Registro de Log     

                 Log l = new Log();
                 l.setUsuario(lblOperador.getText());
                 l.setDescricao(l.getUsuario() + " Cadastrou um novo fornecedor " + fRebido.getNome());
                 l.setFuncionalidade("Tela Fornecedores");
                 l.gravaLog(l);
             }
         } else {
             cf.alteraFornecedor(fRebido);
             System.out.println("Id:" + fRebido.getId());
             lblMsg.setText("*Alteração realizada com sucesso!");
             tlFor.atualizaTabela();
             dispose();
         }

         limparform();
     }

    }//GEN-LAST:event_btnSalvarMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // Fecha a janela
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void comboUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUfActionPerformed
        if (!"Selecione...".equals(comboUf.getSelectedItem().toString()) && !"Selecione...".equals(comboStatus.getSelectedItem().toString())) {
            btnSalvar.setEnabled(true);
        }
    }//GEN-LAST:event_comboUfActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // Habilita botão Adicionar se os combos estiverem com a opção
        // Diferente de selecionado. 

        if (!"Selecione...".equals(comboUf.getSelectedItem().toString()) && !"Selecione...".equals(comboStatus.getSelectedItem().toString())) {
            btnSalvar.setEnabled(true);
        }
    }//GEN-LAST:event_comboStatusActionPerformed

    private void txtFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFornecedorKeyReleased
        // Limita tamanho do campo
        txtFornecedor.setText(u.tamanhoMaximo(txtFornecedor.getText(), 45));
    }//GEN-LAST:event_txtFornecedorKeyReleased

    private void txtCnpjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCnpjMouseClicked
        // Limita tamanho do campo
        txtCnpj.setText(u.tamanhoMaximo(txtCnpj.getText(), 18));

    }//GEN-LAST:event_txtCnpjMouseClicked

    private void txtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyReleased
        // Limita tamanho do campo ENDEREÇO
        txtEndereco.setText(u.tamanhoMaximo(txtEndereco.getText(), 45));
    }//GEN-LAST:event_txtEnderecoKeyReleased

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        txtNumero.setText(u.tamanhoMaximo(txtNumero.getText(), 4));
    }//GEN-LAST:event_txtNumeroKeyReleased

    private void txtComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyReleased
        txtComplemento.setText(u.tamanhoMaximo(txtComplemento.getText(), 30));
    }//GEN-LAST:event_txtComplementoKeyReleased

    private void txtBairroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBairroMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroMouseReleased

    private void txtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyReleased
        txtBairro.setText(u.tamanhoMaximo(txtBairro.getText(), 45));
    }//GEN-LAST:event_txtBairroKeyReleased

    private void txtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyReleased
        txtCidade.setText(u.tamanhoMaximo(txtCidade.getText(), 45));
    }//GEN-LAST:event_txtCidadeKeyReleased

    private void txtRepresentanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepresentanteKeyReleased
        txtRepresentante.setText(u.tamanhoMaximo(txtRepresentante.getText(), 45));
    }//GEN-LAST:event_txtRepresentanteKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        txtEmail.setText(u.tamanhoMaximo(txtEmail.getText(), 35));
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSiteMouseClicked
        txtSite.setText(u.tamanhoMaximo(txtSite.getText(), 35));
    }//GEN-LAST:event_txtSiteMouseClicked

    private void txtAreaObsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaObsKeyReleased
        txtAreaObs.setText(u.tamanhoMaximo(txtAreaObs.getText(), 255));
    }//GEN-LAST:event_txtAreaObsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSalvar;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JComboBox<String> comboUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaObs;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtIdFor;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextField txtSite;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void desbloqueiaCampos() {

        txtEndereco.setEnabled(true);
        txtNumero.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCep.setEnabled(true);
        txtCidade.setEnabled(true);
        comboUf.setEnabled(true);
        txtRepresentante.setEnabled(true);
        txtTelefone.setEnabled(true);
        txtEmail.setEnabled(true);
        txtSite.setEnabled(true);
        comboStatus.setEnabled(true);
        txtAreaObs.setEnabled(true);
    }
}
