/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import br.com.bar.model.Grupo;
import br.com.bar.model.Pedido;
import br.com.bar.model.Produto;
import br.com.bar.model.ProdutoPedido;
import br.com.bar.model.TableModelCozinha;
import br.com.bar.model.TableModelDetalhePedido;
import br.com.bar.model.TableModelPedidosAbertos;
import br.com.bar.model.TableModelProdutoEstoque;
import br.com.bar.util.Util;
import br.com.br.controler.ControlerCozinha;
import br.com.br.controler.ControlerEstoque;
import br.com.br.controler.ControlerFuncionario;
import br.com.br.controler.ControlerGrupo;
import br.com.br.controler.ControlerMesa;
import br.com.br.controler.ControlerPedido;
import br.com.br.controler.ControlerProduto;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author elias
 */
public class TelaPedido2 extends javax.swing.JFrame {

    ControlerFuncionario cFunc = new ControlerFuncionario();
    ControlerMesa cm = new ControlerMesa();
    ControlerPedido cp = new ControlerPedido();
    ControlerProduto cproduto = new ControlerProduto();
    ControlerEstoque est = new ControlerEstoque();
    ControlerGrupo cg = new ControlerGrupo();
    TableModelPedidosAbertos modelPedidos = new TableModelPedidosAbertos();
    TableModelDetalhePedido modelDetPedido = new TableModelDetalhePedido();
    TableModelProdutoEstoque modelProduroEstoque = new TableModelProdutoEstoque();

    Util u = new Util();

    /**
     * Creates new form TelaPedido2
     */
    public TelaPedido2() {

        initComponents();
        lbllogo.setIcon(u.carregaLogo());
        cFunc.carregaComboFuncionario(comboGarcom, "Garçom");

        Calendar c = Calendar.getInstance();
        lblData.setText(u.formataDataBr(c.getTime()));
        bloqueiaCampos();
        // Oculta caixa de pesquisa
        lblPesquisa.setVisible(false);
        txtPesquisa.setVisible(false);
        txtIdGarcom.setVisible(false);
        txtIdMesa.setVisible(false);
        txtNumeroPedido.setVisible(false);
        txtNumeroMesa.setVisible(false);
        txtDescricao.setEnabled(false);
        txtValorUnit.setEnabled(false);
        txtValorTotal.setEnabled(false);
        lblLupa.setVisible(false);
        lblEnviarCozinha.setEnabled(false);
        lblStatusCozinha.setEnabled(false);
        btnAbrirPedido.setEnabled(false);
        lblCargo.setVisible(false);
        lblGerenciarPedido.setEnabled(false);
    }

    public void recebeOperador(String operador, String perfil) {
        lblOperador.setText(operador);
        lblCargo.setText(perfil);
        lblCargo.setVisible(false);
        if ("Gerente".equals(perfil)) {
            lblGerenciarPedido.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtIdGarcom = new javax.swing.JTextField();
        txtIdMesa = new javax.swing.JTextField();
        txtNumeroPedido = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        lblData1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        txtNumeroMesa = new javax.swing.JTextField();
        panelFechar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblStatusCozinha = new javax.swing.JLabel();
        lblEnviarCozinha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGerenciarPedido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblQtd = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtValorUnit = new javax.swing.JTextField();
        lblCodigo1 = new javax.swing.JLabel();
        lblQtd1 = new javax.swing.JLabel();
        lblQtd2 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jTabbedPanePedido = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidosAbertos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetalhePedido = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblListaProduto = new javax.swing.JTable();
        lblLupa = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        comboGarcom = new javax.swing.JComboBox<>();
        btnListar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAbrirPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNumeroMesa = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        txtIdGarcom.setText("idGarcom");
        getContentPane().add(txtIdGarcom);
        txtIdGarcom.setBounds(310, 10, 50, 30);

        txtIdMesa.setText("idMesa");
        getContentPane().add(txtIdMesa);
        txtIdMesa.setBounds(370, 50, 50, 30);

        txtNumeroPedido.setText("nPedido");
        getContentPane().add(txtNumeroPedido);
        txtNumeroPedido.setBounds(370, 10, 50, 30);

        jPanel4.setBackground(new java.awt.Color(38, 53, 61));
        jPanel4.setForeground(new java.awt.Color(52, 73, 94));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/logo.png"))); // NOI18N

        lblData1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        lblData1.setForeground(new java.awt.Color(255, 255, 255));
        lblData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData1.setText("MasterFood");

        lblData.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Calendar32x32.png"))); // NOI18N
        lblData.setText("data");

        lblOperador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblOperador.setForeground(new java.awt.Color(255, 255, 255));
        lblOperador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/usuario_branco.png"))); // NOI18N
        lblOperador.setText("usuário");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(lblData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 300, 700);

        lblData2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        lblData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData2.setText("Lançamento de Pedidos");
        getContentPane().add(lblData2);
        lblData2.setBounds(400, 20, 840, 80);

        txtNumeroMesa.setText("nMesa");
        getContentPane().add(txtNumeroMesa);
        txtNumeroMesa.setBounds(310, 50, 50, 30);

        panelFechar.setBackground(new java.awt.Color(52, 73, 94));
        panelFechar.setForeground(new java.awt.Color(52, 73, 94));
        panelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFecharMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");

        javax.swing.GroupLayout panelFecharLayout = new javax.swing.GroupLayout(panelFechar);
        panelFechar.setLayout(panelFecharLayout);
        panelFecharLayout.setHorizontalGroup(
            panelFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFecharLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelFecharLayout.setVerticalGroup(
            panelFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFecharLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelFechar);
        panelFechar.setBounds(1270, 0, 40, 40);

        lblStatusCozinha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusCozinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/btnCozinha.png"))); // NOI18N
        lblStatusCozinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatusCozinhaMouseClicked(evt);
            }
        });
        getContentPane().add(lblStatusCozinha);
        lblStatusCozinha.setBounds(1010, 610, 70, 48);

        lblEnviarCozinha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnviarCozinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/enviar48x48.png"))); // NOI18N
        lblEnviarCozinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnviarCozinhaMouseClicked(evt);
            }
        });
        getContentPane().add(lblEnviarCozinha);
        lblEnviarCozinha.setBounds(850, 612, 90, 48);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gerenciar Pedido");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(670, 660, 150, 23);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sair");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1140, 660, 70, 20);

        lblGerenciarPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGerenciarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/relatorios48x48.png"))); // NOI18N
        lblGerenciarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGerenciarPedidoMouseClicked(evt);
            }
        });
        getContentPane().add(lblGerenciarPedido);
        lblGerenciarPedido.setBounds(710, 610, 80, 50);

        jLabel8.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel8.setText("Enviar para Cozinha");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(840, 660, 150, 23);

        lblCargo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/perfil3.png"))); // NOI18N
        lblCargo.setText("usuário");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(430, 10, 120, 32);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/power.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1140, 620, 70, 40);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Status Cozinha");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1000, 660, 90, 20);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Produto")));

        lblCodigo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblCodigo.setText("Código");

        lblQtd.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblQtd.setText("Qtd");

        txtQtd.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtQtd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdFocusLost(evt);
            }
        });
        txtQtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtQtdMouseEntered(evt);
            }
        });
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdKeyReleased(evt);
            }
        });

        txtCodigoProduto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtCodigoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoProdutoMouseClicked(evt);
            }
        });
        txtCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoKeyReleased(evt);
            }
        });

        txtDescricao.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N

        txtValorUnit.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtValorUnit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorUnit.setText("0,00");

        lblCodigo1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblCodigo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigo1.setText("Descrição");

        lblQtd1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblQtd1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQtd1.setText("V. Unit R$");

        lblQtd2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lblQtd2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQtd2.setText("Total R$");

        txtValorTotal.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtValorTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal.setText("0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtd)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtd1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtd2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo1))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCodigo))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblQtd)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblQtd1)
                                .addComponent(txtValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblQtd2)
                                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel1);
        jPanel1.setBounds(10, 10, 690, 130);

        lblPesquisa.setText("Pesquisar Produto");
        jPanel6.add(lblPesquisa);
        lblPesquisa.setBounds(10, 140, 120, 14);

        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        jPanel6.add(txtPesquisa);
        txtPesquisa.setBounds(10, 160, 220, 30);

        jTabbedPanePedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPanePedidoMouseClicked(evt);
            }
        });

        tblPedidosAbertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N. MESA", "N. PEDIDO", "DATA", "STATUS", "GARÇOM"
            }
        ));
        tblPedidosAbertos.setRowHeight(25);
        tblPedidosAbertos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosAbertosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPedidosAbertos);

        jTabbedPanePedido.addTab("Pedidos Abertos", jScrollPane2);

        tblDetalhePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDetalhePedido.setRowHeight(25);
        tblDetalhePedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalhePedidoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDetalhePedido);

        jTabbedPanePedido.addTab("Detalhe Pedido", jScrollPane3);

        tblListaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListaProduto.setRowHeight(25);
        tblListaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaProdutoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblListaProduto);

        jTabbedPanePedido.addTab("Lista de Produtos", jScrollPane6);

        jPanel6.add(jTabbedPanePedido);
        jTabbedPanePedido.setBounds(10, 200, 690, 280);

        lblLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/lopa32x32.png"))); // NOI18N
        jPanel6.add(lblLupa);
        lblLupa.setBounds(240, 160, 40, 30);

        lblMensagem.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(153, 153, 153));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(lblMensagem);
        lblMensagem.setBounds(230, 140, 460, 20);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(590, 110, 710, 490);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Garçom")));

        comboGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGarcomActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(204, 204, 204));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/mesa32x32.png"))); // NOI18N
        btnListar.setText("Listar Mesas / Pedidos");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(comboGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jPanel2.setLayout(null);

        btnAbrirPedido.setBackground(new java.awt.Color(204, 204, 204));
        btnAbrirPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bar/imagens/Pedido.png"))); // NOI18N
        btnAbrirPedido.setText("Abrir Pedido");
        btnAbrirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAbrirPedido);
        btnAbrirPedido.setBounds(20, 260, 187, 50);

        tblNumeroMesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNumeroMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Mesas Disponíveis"
            }
        ));
        tblNumeroMesa.setRowHeight(25);
        tblNumeroMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNumeroMesaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNumeroMesa);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 13, 190, 240);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(310, 110, 270, 490);

        setSize(new java.awt.Dimension(1309, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGarcomActionPerformed

        if ("Selecione...".equals(comboGarcom.getSelectedItem().toString())){
            btnListar.setEnabled(false);
        }else {
             btnListar.setEnabled(true);
        }
    }//GEN-LAST:event_comboGarcomActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // Lista todas as mesas livres do funcionário selecionado
        String nomeFunc = comboGarcom.getSelectedItem().toString();
        String idFunc = cFunc.localizaId(nomeFunc);
        txtIdGarcom.setText(cFunc.localizaId(comboGarcom.getSelectedItem().toString()));
        tblNumeroMesa.setModel(DbUtils.resultSetToTableModel(cm.listaMesaLivre(idFunc)));
        tblPedidosAbertos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos(txtIdGarcom.getText())));
        modelPedidos.redimensionaColunas(tblPedidosAbertos);
        btnAbrirPedido.setEnabled(false);
        // Vai para a primeira guia
        jTabbedPanePedido.setSelectedIndex(0);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAbrirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPedidoActionPerformed
        // Abre pedido
        if (cp.temPedido(txtIdMesa.getText())) {
            JOptionPane.showMessageDialog(null, "Esta mesa já possui um pedido escolha outra!");
        } else {
            Pedido p = new Pedido();
            p.setCadMesaId(txtIdMesa.getText());
            String dataAtual = cp.myDataAtual();
            p.setData(dataAtual);
            p.setStatus("0"); // Pedido Aberto
            p.setIdFuncionario(txtIdGarcom.getText());
            //p.setId_pedido(txtNumeroPedido.getText());

            int op = JOptionPane.showConfirmDialog(null, "Confirma a abertura do Pedido?", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if (op == JOptionPane.YES_OPTION) {

                if (cp.geraPedido(p)) {
                    int linha = tblNumeroMesa.getSelectedRow();
                    String numero_mesa = tblNumeroMesa.getModel().getValueAt(linha, 0).toString();
                    JOptionPane.showMessageDialog(null, "Pedido gerado com sucesso!");

                    tblPedidosAbertos.setModel(DbUtils.resultSetToTableModel(cp.listaPedidos(txtIdGarcom.getText())));
                    modelPedidos.redimensionaColunas(tblPedidosAbertos);
                    cm.trocaStatusMesa(numero_mesa, "1");
                    tblNumeroMesa.setModel(DbUtils.resultSetToTableModel(cm.listaMesaLivre(txtIdGarcom.getText())));

                }

            } else {
                JOptionPane.showMessageDialog(null, "Abertura do Pedido cancelada com sucesso!");

            }
        }
    }//GEN-LAST:event_btnAbrirPedidoActionPerformed

    private void tblNumeroMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNumeroMesaMouseClicked
        try {

            // Seleciona uma mesa na tabela
            int linha = tblNumeroMesa.getSelectedRow();

            txtIdMesa.setText(cm.localizaIdMesa(tblNumeroMesa.getModel().getValueAt(linha, 0).toString()));
            txtIdGarcom.setText(cFunc.localizaId(comboGarcom.getSelectedItem().toString()));
            btnAbrirPedido.setEnabled(true);
        } catch (Exception e) {
            System.out.println("br.com.bar.view.TelaPedido2.tblNumeroMesaMouseClicked()" + e);
            btnAbrirPedido.setEnabled(false);
        }

    }//GEN-LAST:event_tblNumeroMesaMouseClicked

    private void tblPedidosAbertosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosAbertosMouseClicked
        // Selciona um pedido
        int linha = tblPedidosAbertos.getSelectedRow();
        //Captura exceção gerada no momento do click na tabela pedidos abertos quando
        // a mesma está vazia.

        try {

            System.out.println("Linha " + linha);
            String numeroMesa = tblPedidosAbertos.getModel().getValueAt(linha, 0).toString();
            txtNumeroMesa.setText(numeroMesa);
            String numPedido = tblPedidosAbertos.getModel().getValueAt(linha, 1).toString();

            tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(numeroMesa, numPedido)));
            modelDetPedido.redimensionaColunas(tblDetalhePedido);

            txtNumeroPedido.setText(numPedido);

            txtIdGarcom.setText(cFunc.localizaId(tblPedidosAbertos.getModel().getValueAt(linha, 4).toString()));
            txtIdMesa.setText(cm.localizaIdMesa(numeroMesa));
            txtCodigoProduto.setEnabled(true);
            txtQtd.setEnabled(true);
            txtCodigoProduto.requestFocus();
            comboGarcom.setSelectedItem(tblPedidosAbertos.getModel().getValueAt(linha, 4).toString());
            jTabbedPanePedido.setSelectedIndex(1);
            txtCodigoProduto.requestFocus();
        } catch (NullPointerException e) {
            System.out.println("br.com.bar.view.TelaPedido2.tblPedidosAbertosMouseClicked()" + e);
        }
    }//GEN-LAST:event_tblPedidosAbertosMouseClicked

    private void jTabbedPanePedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPanePedidoMouseClicked
        // Exibe caixa de pesquisa e lista todos os produtos disponível no estoque

        int index = jTabbedPanePedido.getSelectedIndex();
        if ("Pedidos Abertos".equals(jTabbedPanePedido.getTitleAt(index))) {
            bloqueiaCampos();
            lblPesquisa.setVisible(false);
            txtPesquisa.setVisible(false);
        } else if ("Detalhe Pedido".equals(jTabbedPanePedido.getTitleAt(index))) {
            txtQtd.setEnabled(true);
            txtCodigoProduto.setEnabled(true);
            lblPesquisa.setVisible(false);
            txtPesquisa.setVisible(false);

            tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(txtNumeroMesa.getText(), txtNumeroPedido.getText())));
            modelDetPedido.redimensionaColunas(tblDetalhePedido);
        } else {
            lblPesquisa.setVisible(true);
            txtPesquisa.setVisible(true);
            lblLupa.setEnabled(true);
            txtValorTotal.setText("0,00");
            txtCodigoProduto.setEnabled(false);
            txtQtd.setEnabled(true);

            tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.listaProdutoDisponivel()));
            modelProduroEstoque.redimensionaColunas(tblListaProduto);
        }
        /*
        "Lista de Produtos".equals(jTabbedPanePedido.getTitleAt(index)
        else {
            lblPesquisa.setVisible(false);
            txtPesquisa.setVisible(false);
            lblLupa.setVisible(false);
            txtQtd.setEnabled(false);
           
        }*/
    }//GEN-LAST:event_jTabbedPanePedidoMouseClicked

    private void txtCodigoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProdutoMouseClicked

    }//GEN-LAST:event_txtCodigoProdutoMouseClicked

    private void txtCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoKeyPressed
        // Vai para a caixa quantidade 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //txtIdMesa.setText(cm.localizaIdMesa(comboNumeroMEsa.getSelectedItem().toString()));
            if (txtIdMesa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um pedido!");
            } else {

                Produto produto = new Produto();
                produto.setId(txtCodigoProduto.getText());

                try {

                    Produto pLocalizado = cproduto.localizaProduto(produto);
                    txtDescricao.setText(pLocalizado.getNome());
                    txtValorUnit.setText(String.format("%7.2f", Double.parseDouble(pLocalizado.getValor())));

                    txtQtd.requestFocus();
                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "Produto não localizado!");
                }
            }

        }
    }//GEN-LAST:event_txtCodigoProdutoKeyPressed

    private void txtQtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdMouseClicked
    // Calcula o total da venda 
    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed
        // Verifica se a tecla pressionada é a tecla enter

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("nPedido".equals(txtNumeroPedido.getText())) {
                JOptionPane.showMessageDialog(null, "Selecione um pedido para continuar!", "Nenhum pedido selecionado!", JOptionPane.ERROR_MESSAGE);
            } else {

                adicionaItemNoPedido();
                tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(txtNumeroMesa.getText(), txtNumeroPedido.getText())));
                modelDetPedido.redimensionaColunas(tblDetalhePedido);
                txtCodigoProduto.requestFocus();
                txtValorTotal.setText("0,00");
                //txtValorUnit.setText("0,00");
            }

        }
    }//GEN-LAST:event_txtQtdKeyPressed

    private void tblListaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaProdutoMouseClicked
        // Carega dados do produto
        int linha = tblListaProduto.getSelectedRow();
        txtCodigoProduto.setText(tblListaProduto.getModel().getValueAt(linha, 0).toString());
        txtDescricao.setText(tblListaProduto.getModel().getValueAt(linha, 1).toString());
        txtValorUnit.setText(tblListaProduto.getModel().getValueAt(linha, 3).toString());
        txtQtd.requestFocus();
        txtQtd.setText(null);
        txtQtd.setEnabled(true);
        txtValorTotal.setText("0,00");


    }//GEN-LAST:event_tblListaProdutoMouseClicked

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // Lista o produto localizado pelas inicias do nome
        tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.pesquisarProduto(txtPesquisa.getText())));
        modelProduroEstoque.redimensionaColunas(tblListaProduto);
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        // Vai para a tabela de listagem de produto
        jTabbedPanePedido.setSelectedIndex(2);
        tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.listaProdutoDisponivel()));
        modelProduroEstoque.redimensionaColunas(tblListaProduto);
    }//GEN-LAST:event_txtPesquisaFocusGained

    private void tblDetalhePedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalhePedidoMouseClicked
        // Envia produto para a cozinha
        int linha = tblDetalhePedido.getSelectedRow();
        String idProduto = tblDetalhePedido.getModel().getValueAt(linha, 0).toString();
        System.out.println(idProduto);

        String grupo = cproduto.localizaGrupoProduto(Integer.parseInt(idProduto));
        System.out.println("Grupo:" + grupo);

        if (grupo.toLowerCase().equals("cozinha")) {
            lblEnviarCozinha.setEnabled(true);
            lblStatusCozinha.setEnabled(true);

        } else {
            lblEnviarCozinha.setEnabled(false);
            lblStatusCozinha.setEnabled(false);
        }


    }//GEN-LAST:event_tblDetalhePedidoMouseClicked

    private void panelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFecharMouseClicked
        // Fecha a janela atual se o usuário logado for Gerente
        // Para demais usuário a janela será fechada e chanará a Tela de Login
        if ("Gerente".equals(lblCargo.getText())) {
            this.dispose();
        }else {
            this.dispose();
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_panelFecharMouseClicked

    private void txtQtdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdMouseEntered

    private void lblStatusCozinhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatusCozinhaMouseClicked
        // Chama Tela Cozinha
        if (lblStatusCozinha.isEnabled()) {
            TelaStatusCozinha status = new TelaStatusCozinha();
            status.recebeOperador(comboGarcom.getSelectedItem().toString());
            status.setVisible(true);

        }
    }//GEN-LAST:event_lblStatusCozinhaMouseClicked

    private void lblEnviarCozinhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarCozinhaMouseClicked
        // Envia prato para cozinha
        enviaParaCozinha();


    }//GEN-LAST:event_lblEnviarCozinhaMouseClicked

    private void lblGerenciarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGerenciarPedidoMouseClicked
        if (lblGerenciarPedido.isEnabled()) {

            TelaGerenciarPedido gp = new TelaGerenciarPedido();
            gp.recebeOperador(lblOperador.getText(), lblCargo.getText());
            gp.setVisible(true);
        }
    }//GEN-LAST:event_lblGerenciarPedidoMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // Sai da tela
        if ("Gerente".equals(lblCargo.getText())) {
            this.dispose();
        }else {
            this.dispose();
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdFocusLost

    }//GEN-LAST:event_txtQtdFocusLost

    private void txtCodigoProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoKeyReleased
        // Aceita a penas número        
        txtCodigoProduto.setText(txtCodigoProduto.getText().replaceAll("[^0-9]", ""));
        // Limita o tamanho do campo
        txtCodigoProduto.setText(u.tamanhoMaximo(txtCodigoProduto.getText(), 10));

    }//GEN-LAST:event_txtCodigoProdutoKeyReleased

    private void txtQtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyReleased
        // Aceita apenas número
        txtQtd.setText(txtQtd.getText().replaceAll("[^0-9]", ""));
        txtQtd.setText(u.tamanhoMaximo(txtQtd.getText(), 3));
    }//GEN-LAST:event_txtQtdKeyReleased

    private double calculaPedido() {
        double valor = Double.parseDouble(txtValorUnit.getText().replaceAll(",", "."));
        int qtd = Integer.parseInt(txtQtd.getText());
        double total = valor * qtd;

        return total;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedido2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPedido;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> comboGarcom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPanePedido;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData2;
    private javax.swing.JLabel lblEnviarCozinha;
    private javax.swing.JLabel lblGerenciarPedido;
    private javax.swing.JLabel lblLupa;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblQtd1;
    private javax.swing.JLabel lblQtd2;
    private javax.swing.JLabel lblStatusCozinha;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelFechar;
    private javax.swing.JTable tblDetalhePedido;
    private javax.swing.JTable tblListaProduto;
    private javax.swing.JTable tblNumeroMesa;
    private javax.swing.JTable tblPedidosAbertos;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdGarcom;
    private javax.swing.JTextField txtIdMesa;
    private javax.swing.JTextField txtNumeroMesa;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtValorUnit;
    // End of variables declaration//GEN-END:variables

    private void limpaform() {
        txtCodigoProduto.setText(null);
        txtDescricao.setText(null);
        txtValorUnit.setText(null);
        txtQtd.setText(null);
        txtValorTotal.setText(null);

    }

    private void bloqueiaCampos() {
        txtCodigoProduto.setEnabled(false);
        txtQtd.setEnabled(false);
    }

    // Este método adiciona um item ao pedido e é chamado pela execusão dos 
    // Eventos KeyPressed e LostFocus
    private void adicionaItemNoPedido() {

        try {
            // Caso a quantidade não seja informada pede ao usuário que digite novamente!
            if (txtQtd.getText().isEmpty()) {
                lblMensagem.setText("*Informe uma quantidade válida!");
                lblMensagem.setForeground(Color.red);
                txtQtd.requestFocus();

            } else {
                Double calculoPedido = calculaPedido();
                txtValorTotal.setText(String.format("%9.2f", calculoPedido));
                lblMensagem.setText(null);

                // Verifica se o pedido foi selecionado
                if (txtNumeroPedido.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, selecione um pedido!");
                } else {
                    // Confirma pedido
                    int op = JOptionPane.showConfirmDialog(null, "Confirma a inclusão do produto '" + txtDescricao.getText() + "'?", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

                    if (op == JOptionPane.YES_OPTION) {
                        // Instancia um objeto Produto Pedido
                        ProdutoPedido pp = new ProdutoPedido();
                        // Seta dados no objeto
                        pp.setTbproduto_id(txtCodigoProduto.getText());
                        pp.setQtd(txtQtd.getText());
                        pp.setValorUnit(txtValorUnit.getText().replaceAll(",", "."));
                        pp.setTotal(txtValorTotal.getText().replaceAll(",", "."));
                        pp.setData(cp.myDataAtual());
                        pp.setCadmesa_id(txtIdMesa.getText());
                        pp.setCadpedido_id_pedido(txtNumeroPedido.getText());
                        pp.setTbcadfuncionario_id(txtIdGarcom.getText());

                        ControlerEstoque ec = new ControlerEstoque();
                        int qtdEstoque = ec.temNoEstoque(pp.getTbproduto_id());

                        System.out.println("Qtd: " + qtdEstoque);

                        if (Integer.parseInt(pp.getQtd()) <= qtdEstoque) {
                            // Adiciona o produto ao pedido                 
                            cproduto.adicionaProdutoAoPedido(pp);

                            // Retira o produto do estoque                 
                            ec.retiraEstoque(pp, pp.getQtd());

                            // Registra movimentação 
                            if (est.registraMovimentacao(pp.getTbproduto_id(), pp.getQtd(), est.localizaIdOperacao("Venda"), null)) {
                                System.out.println("Movimentação registrada!");
                            }
                            // Limpa label de mensagem de produto indisponível 
                            lblMensagem.setText(null);

                            bloqueiaCampos();
                            txtCodigoProduto.setEnabled(true);
                            txtQtd.setEnabled(true);

                        } else {
                            // Exibe mensagem de produto indisponpivel no momento
                            lblMensagem.setForeground(Color.red);
                            lblMensagem.setText("*Quantidade insuficiente! " + "Existe apenas " + qtdEstoque + " unidade(s) em estoque.");
                            txtCodigoProduto.requestFocus();
                            //txtCodigoProduto.setText(null);
                            txtQtd.setText(null);

                        }
                        //Atualiza a tabela de detalhe do pedido    
                        tblDetalhePedido.setModel(DbUtils.resultSetToTableModel(cp.detalhePorPedido(txtIdMesa.getText(), txtNumeroPedido.getText())));
                        modelDetPedido.redimensionaColunas(tblDetalhePedido);
                        // Atualiza os produtos disponível no Estoque
                        tblListaProduto.setModel(DbUtils.resultSetToTableModel(cproduto.listaProdutoDisponivel()));
                        modelProduroEstoque.redimensionaColunas(tblListaProduto);
                       // limpaform();
                    }

                }
            }
        } catch (HeadlessException | NumberFormatException e) {
            System.out.println(txtQtd);
            System.out.println("br.com.bar.view.TelaPedido2.txtQtdKeyPressed()" + e);
            lblMensagem.setText("*Quantidade inválida, tente novamente!");
            lblMensagem.setOpaque(false);
            lblMensagem.setForeground(Color.red);
            txtQtd.requestFocus();
        }
    }

    private void enviaParaCozinha() {
        // Envia porduto para a cozinha

        ControlerCozinha cc = new ControlerCozinha(); // Instancia o controler cozinha
        if (lblEnviarCozinha.isEnabled()) {
            lblStatusCozinha.setEnabled(true);
            int linha = tblDetalhePedido.getSelectedRow();

            ArrayList<String> pCozinha = new ArrayList<>();

            //codProduto, produto, qtd, funcionario, mesa, data, status
            pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 1).toString()); // Produto
            pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 0).toString()); // // Código Produto
            pCozinha.add(tblDetalhePedido.getModel().getValueAt(linha, 2).toString()); // Qtd         
            pCozinha.add(comboGarcom.getSelectedItem().toString()); // Nome do Funcionario
            pCozinha.add(txtNumeroMesa.getText()); // Numero da mesa
            pCozinha.add(cp.myDataAtual()); // Data Atual 
            pCozinha.add("Pendente"); // Status Pendente - Liberado
            pCozinha.add(txtNumeroPedido.getText());
            Date dtAtual = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
            pCozinha.add(sdf.format(dtAtual)); // Data Atual            

            int op = JOptionPane.showConfirmDialog(null, "Confirma o envio do prato para a cozinha? ", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if (op == JOptionPane.YES_OPTION) {

                cp.enviaProdutoCozinha(pCozinha);

            }
        }
    }
}
