/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bar.view;

import java.awt.event.KeyEvent;
import javax.swing.JDialog;

/**
 *
 * @author Elias Santana
 */
public class TelaAtualizaItem extends JDialog {

    TelaGerenciarPedido gPedido;
    int qtdPedido;


    public TelaAtualizaItem() {
        initComponents();

    }

    // Armazena a quantidade e o id do item selecionado na tela de Gerenciamento de 
    // Pedido para intes com quantidade maior que 1
    public void recebeQtdItem(TelaGerenciarPedido gp, String qtd) {
        gPedido=gp;
        this.qtdPedido = Integer.parseInt(qtd);      
     
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTítulo = new javax.swing.JLabel();
        txtQtd = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(38, 53, 61));
        jPanel1.setLayout(null);

        lblTítulo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblTítulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTítulo.setText("Exclusão de Itens");
        jPanel1.add(lblTítulo);
        lblTítulo.setBounds(10, 0, 170, 33);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 257, 37);

        txtQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtQtd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
        });
        jPanel2.add(txtQtd);
        txtQtd.setBounds(140, 50, 108, 30);

        jLabel1.setText("Informe a quantidade:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 54, 130, 20);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfirmar);
        btnConfirmar.setBounds(12, 108, 117, 31);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(135, 108, 114, 31);

        lblMsg.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(lblMsg);
        lblMsg.setBounds(12, 83, 237, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );

        setBounds(550, 100, 259, 154);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        //Chama o método valida quantidade
        validaQuantidade();
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validaQuantidade();
        }
    }//GEN-LAST:event_txtQtdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizaItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JFormattedTextField txtQtd;
    // End of variables declaration//GEN-END:variables
     // Pedido qtd: 3 informado=2
    private void validaQuantidade() {
        // Quantidade a ser removida informada pelo usuário
        int qtdInformada = Integer.parseInt(txtQtd.getText());

        // Verifica a quantidade digitada
        if (qtdInformada <= 0 || qtdInformada > qtdPedido) {
            lblMsg.setText("*Quantidade informada inválida!");
        } else {
           
           int qtdAtualizada=qtdPedido-qtdInformada;
           //Devolve quantidade a ser atualizada
           gPedido.recebeNovaQtd(qtdAtualizada);//0
           dispose();
        }
    }
}
